/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { Name } from "../../commons/types/Name";
import { DeclaredTypeName } from "../../types/types/DeclaredTypeName";
import { InlinedWebhookPayloadProperty } from "./InlinedWebhookPayloadProperty";

export const InlinedWebhookPayload: core.serialization.ObjectSchema<
    serializers.InlinedWebhookPayload.Raw,
    RapiddocsIr.InlinedWebhookPayload
> = core.serialization.objectWithoutOptionalProperties({
    name: Name,
    extends: core.serialization.list(DeclaredTypeName),
    properties: core.serialization.list(InlinedWebhookPayloadProperty),
});

export declare namespace InlinedWebhookPayload {
    export interface Raw {
        name: Name.Raw;
        extends: DeclaredTypeName.Raw[];
        properties: InlinedWebhookPayloadProperty.Raw[];
    }
}
