/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface ApiAuth extends RapiddocsIr.WithDocs {
    requirement: RapiddocsIr.AuthSchemesRequirement;
    schemes: RapiddocsIr.AuthScheme[];
}
