/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface OAuthClientCredentials {
    clientIdEnvVar: RapiddocsIr.EnvironmentVariable | undefined;
    clientSecretEnvVar: RapiddocsIr.EnvironmentVariable | undefined;
    tokenPrefix: string | undefined;
    tokenHeader: string | undefined;
    scopes: string[] | undefined;
    tokenEndpoint: RapiddocsIr.OAuthTokenEndpoint;
    refreshEndpoint: RapiddocsIr.OAuthRefreshEndpoint | undefined;
}
