/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export type OAuthConfiguration = RapiddocsIr.OAuthConfiguration.ClientCredentials;

export namespace OAuthConfiguration {
    export interface ClientCredentials extends RapiddocsIr.OAuthClientCredentials, _Utils {
        type: "clientCredentials";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.OAuthConfiguration._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        clientCredentials: (value: RapiddocsIr.OAuthClientCredentials) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const OAuthConfiguration = {
    clientCredentials: (value: RapiddocsIr.OAuthClientCredentials): RapiddocsIr.OAuthConfiguration.ClientCredentials => {
        return {
            ...value,
            type: "clientCredentials",
            _visit: function <_Result>(
                this: RapiddocsIr.OAuthConfiguration.ClientCredentials,
                visitor: RapiddocsIr.OAuthConfiguration._Visitor<_Result>,
            ) {
                return RapiddocsIr.OAuthConfiguration._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsIr.OAuthConfiguration,
        visitor: RapiddocsIr.OAuthConfiguration._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "clientCredentials":
                return visitor.clientCredentials(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
