/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface OAuthRefreshEndpoint {
    endpointReference: RapiddocsIr.EndpointReference;
    requestProperties: RapiddocsIr.OAuthRefreshTokenRequestProperties;
    responseProperties: RapiddocsIr.OAuthAccessTokenResponseProperties;
}
