/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export interface DiscriminatedOneOfSchemaWithExample
    extends RapiddocsOpenapiIr.WithDescription,
        RapiddocsOpenapiIr.WithName,
        RapiddocsOpenapiIr.WithSdkGroupName,
        RapiddocsOpenapiIr.WithAvailability,
        RapiddocsOpenapiIr.WithEncoding,
        RapiddocsOpenapiIr.WithSource,
        RapiddocsOpenapiIr.WithTitle,
        RapiddocsOpenapiIr.WithInline {
    discriminantProperty: string;
    commonProperties: RapiddocsOpenapiIr.CommonPropertyWithExample[];
    schemas: Record<string, RapiddocsOpenapiIr.SchemaWithExample>;
}
