/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export interface JsonResponseWithExample
    extends RapiddocsOpenapiIr.WithDescription,
        RapiddocsOpenapiIr.WithSource,
        RapiddocsOpenapiIr.WithStatusCode {
    schema: RapiddocsOpenapiIr.SchemaWithExample;
    responseProperty: string | undefined;
    fullExamples: RapiddocsOpenapiIr.NamedFullExample[] | undefined;
}
