/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export interface MapSchemaWithExample
    extends RapiddocsOpenapiIr.WithSdkGroupName,
        RapiddocsOpenapiIr.WithName,
        RapiddocsOpenapiIr.WithDescription,
        RapiddocsOpenapiIr.WithAvailability,
        RapiddocsOpenapiIr.WithEncoding,
        RapiddocsOpenapiIr.WithTitle,
        RapiddocsOpenapiIr.WithInline {
    key: RapiddocsOpenapiIr.PrimitiveSchemaWithExample;
    value: RapiddocsOpenapiIr.SchemaWithExample;
    example: unknown | undefined;
}
