/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export interface NullableSchemaWithExample
    extends RapiddocsOpenapiIr.WithSdkGroupName,
        RapiddocsOpenapiIr.WithName,
        RapiddocsOpenapiIr.WithDescription,
        RapiddocsOpenapiIr.WithAvailability,
        RapiddocsOpenapiIr.WithTitle,
        RapiddocsOpenapiIr.WithInline {
    value: RapiddocsOpenapiIr.SchemaWithExample;
}
