/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export type PrimitiveSchemaValueWithExample =
    | RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Int
    | RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Int64
    | RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Uint
    | RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Uint64
    | RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Float
    | RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Double
    | RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.String
    | RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Datetime
    | RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Date_
    | RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Base64
    | RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Boolean;

export namespace PrimitiveSchemaValueWithExample {
    export interface Int extends RapiddocsOpenapiIr.IntWithExample, _Utils {
        type: "int";
    }

    export interface Int64 extends RapiddocsOpenapiIr.Int64WithExample, _Utils {
        type: "int64";
    }

    export interface Uint extends RapiddocsOpenapiIr.UintWithExample, _Utils {
        type: "uint";
    }

    export interface Uint64 extends RapiddocsOpenapiIr.Uint64WithExample, _Utils {
        type: "uint64";
    }

    export interface Float extends RapiddocsOpenapiIr.FloatWithExample, _Utils {
        type: "float";
    }

    export interface Double extends RapiddocsOpenapiIr.DoubleWithExample, _Utils {
        type: "double";
    }

    export interface String extends RapiddocsOpenapiIr.StringSchemaWithExample, _Utils {
        type: "string";
    }

    export interface Datetime extends RapiddocsOpenapiIr.DatetimeWithExample, _Utils {
        type: "datetime";
    }

    export interface Date_ extends RapiddocsOpenapiIr.DateWithExample, _Utils {
        type: "date";
    }

    export interface Base64 extends RapiddocsOpenapiIr.Base64WithExample, _Utils {
        type: "base64";
    }

    export interface Boolean extends RapiddocsOpenapiIr.BooleanWithExample, _Utils {
        type: "boolean";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        int: (value: RapiddocsOpenapiIr.IntWithExample) => _Result;
        int64: (value: RapiddocsOpenapiIr.Int64WithExample) => _Result;
        uint: (value: RapiddocsOpenapiIr.UintWithExample) => _Result;
        uint64: (value: RapiddocsOpenapiIr.Uint64WithExample) => _Result;
        float: (value: RapiddocsOpenapiIr.FloatWithExample) => _Result;
        double: (value: RapiddocsOpenapiIr.DoubleWithExample) => _Result;
        string: (value: RapiddocsOpenapiIr.StringSchemaWithExample) => _Result;
        datetime: (value: RapiddocsOpenapiIr.DatetimeWithExample) => _Result;
        date: (value: RapiddocsOpenapiIr.DateWithExample) => _Result;
        base64: (value: RapiddocsOpenapiIr.Base64WithExample) => _Result;
        boolean: (value: RapiddocsOpenapiIr.BooleanWithExample) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const PrimitiveSchemaValueWithExample = {
    int: (value: RapiddocsOpenapiIr.IntWithExample): RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Int => {
        return {
            ...value,
            type: "int",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Int,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._visit(this, visitor);
            },
        };
    },

    int64: (value: RapiddocsOpenapiIr.Int64WithExample): RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Int64 => {
        return {
            ...value,
            type: "int64",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Int64,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._visit(this, visitor);
            },
        };
    },

    uint: (value: RapiddocsOpenapiIr.UintWithExample): RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Uint => {
        return {
            ...value,
            type: "uint",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Uint,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._visit(this, visitor);
            },
        };
    },

    uint64: (value: RapiddocsOpenapiIr.Uint64WithExample): RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Uint64 => {
        return {
            ...value,
            type: "uint64",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Uint64,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._visit(this, visitor);
            },
        };
    },

    float: (value: RapiddocsOpenapiIr.FloatWithExample): RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Float => {
        return {
            ...value,
            type: "float",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Float,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._visit(this, visitor);
            },
        };
    },

    double: (value: RapiddocsOpenapiIr.DoubleWithExample): RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Double => {
        return {
            ...value,
            type: "double",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Double,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._visit(this, visitor);
            },
        };
    },

    string: (value: RapiddocsOpenapiIr.StringSchemaWithExample): RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.String => {
        return {
            ...value,
            type: "string",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.String,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._visit(this, visitor);
            },
        };
    },

    datetime: (value: RapiddocsOpenapiIr.DatetimeWithExample): RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Datetime => {
        return {
            ...value,
            type: "datetime",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Datetime,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._visit(this, visitor);
            },
        };
    },

    date: (value: RapiddocsOpenapiIr.DateWithExample): RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Date_ => {
        return {
            ...value,
            type: "date",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Date_,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._visit(this, visitor);
            },
        };
    },

    base64: (value: RapiddocsOpenapiIr.Base64WithExample): RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Base64 => {
        return {
            ...value,
            type: "base64",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Base64,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._visit(this, visitor);
            },
        };
    },

    boolean: (value: RapiddocsOpenapiIr.BooleanWithExample): RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Boolean => {
        return {
            ...value,
            type: "boolean",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample.Boolean,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample,
        visitor: RapiddocsOpenapiIr.PrimitiveSchemaValueWithExample._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "int":
                return visitor.int(value);
            case "int64":
                return visitor.int64(value);
            case "uint":
                return visitor.uint(value);
            case "uint64":
                return visitor.uint64(value);
            case "float":
                return visitor.float(value);
            case "double":
                return visitor.double(value);
            case "string":
                return visitor.string(value);
            case "datetime":
                return visitor.datetime(value);
            case "date":
                return visitor.date(value);
            case "base64":
                return visitor.base64(value);
            case "boolean":
                return visitor.boolean(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
