/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export interface UnDiscriminatedOneOfSchemaWithExample
    extends RapiddocsOpenapiIr.WithDescription,
        RapiddocsOpenapiIr.WithName,
        RapiddocsOpenapiIr.WithSdkGroupName,
        RapiddocsOpenapiIr.WithAvailability,
        RapiddocsOpenapiIr.WithEncoding,
        RapiddocsOpenapiIr.WithSource,
        RapiddocsOpenapiIr.WithTitle,
        RapiddocsOpenapiIr.WithInline {
    schemas: RapiddocsOpenapiIr.SchemaWithExample[];
}
