/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export interface WebsocketHandshakeWithExample {
    queryParameters: RapiddocsOpenapiIr.QueryParameterWithExample[];
    headers: RapiddocsOpenapiIr.HeaderWithExample[];
}
