// This file was auto-generated by Rapiddocs from our API Definition.

package client

import (
	core "github.com/unknown/rapiddocs/core"
	internal "github.com/unknown/rapiddocs/internal"
	option "github.com/unknown/rapiddocs/option"
	unknown "github.com/unknown/rapiddocs/unknown"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Unknown *unknown.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:  options.ToHeader(),
		Unknown: unknown.NewClient(opts...),
	}
}
