/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedAudiences from "../../../index";

export interface ImportingType {
    imported: SeedAudiences.Imported;
}
