/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { SupportedSdkLanguageSchema } from "./SupportedSdkLanguageSchema";
import { WithDocsSchema } from "../../commons/types/WithDocsSchema";
import { WithName } from "../../commons/types/WithName";

export const ExampleCodeSampleSchemaSdk: core.serialization.ObjectSchema<
    serializers.ExampleCodeSampleSchemaSdk.Raw,
    RapiddocsDefinition.ExampleCodeSampleSchemaSdk
> = core.serialization
    .object({
        sdk: SupportedSdkLanguageSchema,
        code: core.serialization.string(),
    })
    .extend(WithDocsSchema)
    .extend(WithName);

export declare namespace ExampleCodeSampleSchemaSdk {
    export interface Raw extends WithDocsSchema.Raw, WithName.Raw {
        sdk: SupportedSdkLanguageSchema.Raw;
        code: string;
    }
}
