/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { ExampleTypeReferenceSchema } from "./ExampleTypeReferenceSchema";

export const ExampleBodyResponseSchema: core.serialization.ObjectSchema<
    serializers.ExampleBodyResponseSchema.Raw,
    RapiddocsDefinition.ExampleBodyResponseSchema
> = core.serialization.object({
    error: core.serialization.string().optional(),
    body: ExampleTypeReferenceSchema.optional(),
});

export declare namespace ExampleBodyResponseSchema {
    export interface Raw {
        error?: string | null;
        body?: (ExampleTypeReferenceSchema.Raw | undefined) | null;
    }
}
