/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";

export const ExampleTypeValueSchema: core.serialization.Schema<
    serializers.ExampleTypeValueSchema.Raw,
    RapiddocsDefinition.ExampleTypeValueSchema
> = core.serialization.unknown();

export declare namespace ExampleTypeValueSchema {
    export type Raw = unknown;
}
