/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { ExampleSseEventSchema } from "./ExampleSseEventSchema";

export const ExampleSseResponseSchema: core.serialization.ObjectSchema<
    serializers.ExampleSseResponseSchema.Raw,
    RapiddocsDefinition.ExampleSseResponseSchema
> = core.serialization.object({
    stream: core.serialization.list(ExampleSseEventSchema),
});

export declare namespace ExampleSseResponseSchema {
    export interface Raw {
        stream: ExampleSseEventSchema.Raw[];
    }
}
