/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsDefinition from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const WithDocsSchema: core.serialization.ObjectSchema<
    serializers.rapiddocsDefinition.WithDocsSchema.Raw,
    RapiddocsDefinition.rapiddocsDefinition.WithDocsSchema
> = core.serialization.object({
    docs: core.serialization.string().optional(),
});

export declare namespace WithDocsSchema {
    export interface Raw {
        docs?: string | null;
    }
}
