/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface ExampleWebhookCallSchema extends RapiddocsDefinition.WithName, RapiddocsDefinition.WithDocsSchema {
    id?: string;
    payload?: RapiddocsDefinition.ExampleTypeReferenceSchema;
}
