/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export type ExampleCodeSampleSchema =
    | RapiddocsDefinition.ExampleCodeSampleSchemaSdk
    | RapiddocsDefinition.ExampleCodeSampleSchemaLanguage;
