/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface ExampleTypeSchema extends RapiddocsDefinition.WithName, RapiddocsDefinition.WithDocsSchema {
    value?: RapiddocsDefinition.ExampleTypeValueSchema;
}
