/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface ExampleWebSocketSession extends RapiddocsDefinition.WithName, RapiddocsDefinition.WithDocsSchema {
    "path-parameters"?: Record<string, RapiddocsDefinition.ExampleTypeReferenceSchema | undefined>;
    "query-parameters"?: Record<string, RapiddocsDefinition.ExampleTypeReferenceSchema | undefined>;
    headers?: Record<string, RapiddocsDefinition.ExampleTypeReferenceSchema | undefined>;
    messages: RapiddocsDefinition.ExampleWebSocketMessage[];
}
