/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { ApiConfigurationSchemaInternal } from "./ApiConfigurationSchemaInternal";
import { NamespacedApiConfigurationSchema } from "./NamespacedApiConfigurationSchema";
import { ApiConfigurationV2Schema } from "./ApiConfigurationV2Schema";

export const ApiConfigurationSchema: core.serialization.Schema<
    serializers.ApiConfigurationSchema.Raw,
    RapiddocsDefinition.ApiConfigurationSchema
> = core.serialization.undiscriminatedUnion([
    ApiConfigurationSchemaInternal,
    NamespacedApiConfigurationSchema,
    ApiConfigurationV2Schema,
]);

export declare namespace ApiConfigurationSchema {
    export type Raw =
        | ApiConfigurationSchemaInternal.Raw
        | NamespacedApiConfigurationSchema.Raw
        | ApiConfigurationV2Schema.Raw;
}
