/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";

export const ApiDefinitionPathSchema: core.serialization.Schema<
    serializers.ApiDefinitionPathSchema.Raw,
    RapiddocsDefinition.ApiDefinitionPathSchema
> = core.serialization.string();

export declare namespace ApiDefinitionPathSchema {
    export type Raw = string;
}
