/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { ApiDefinitionSchema } from "./ApiDefinitionSchema";

export const ApiDefinitionList: core.serialization.Schema<
    serializers.ApiDefinitionList.Raw,
    RapiddocsDefinition.ApiDefinitionList
> = core.serialization.list(ApiDefinitionSchema);

export declare namespace ApiDefinitionList {
    export type Raw = ApiDefinitionSchema.Raw[];
}
