/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { ReadmeEndpointObjectSchema } from "./ReadmeEndpointObjectSchema";

export const ReadmeEndpointSchema: core.serialization.Schema<
    serializers.ReadmeEndpointSchema.Raw,
    RapiddocsDefinition.ReadmeEndpointSchema
> = core.serialization.undiscriminatedUnion([core.serialization.string(), ReadmeEndpointObjectSchema]);

export declare namespace ReadmeEndpointSchema {
    export type Raw = string | ReadmeEndpointObjectSchema.Raw;
}
