/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { OpenApiSpecSchema } from "./OpenApiSpecSchema";
import { AsyncApiSpecSchema } from "./AsyncApiSpecSchema";
import { ProtobufSpecSchema } from "./ProtobufSpecSchema";

export const SpecSchema: core.serialization.Schema<serializers.SpecSchema.Raw, RapiddocsDefinition.SpecSchema> =
    core.serialization.undiscriminatedUnion([OpenApiSpecSchema, AsyncApiSpecSchema, ProtobufSpecSchema]);

export declare namespace SpecSchema {
    export type Raw = OpenApiSpecSchema.Raw | AsyncApiSpecSchema.Raw | ProtobufSpecSchema.Raw;
}
