/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../index";

export type ShareId = string & {
    ShareId: void;
};

export function ShareId(value: string): SeedTrace.ShareId {
    return value as unknown as SeedTrace.ShareId;
}
