/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../index";

export interface TestCaseResultWithStdout {
    result: SeedTrace.TestCaseResult;
    stdout: string;
}
