/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../index";

export interface TracedTestCase {
    result: SeedTrace.TestCaseResultWithStdout;
    traceResponsesSize: number;
}
