/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export type SecurityScheme =
    | RapiddocsOpenapiIr.SecurityScheme.Basic
    | RapiddocsOpenapiIr.SecurityScheme.Bearer
    | RapiddocsOpenapiIr.SecurityScheme.Header
    /**
     * parameter sent as a security scheme */
    | RapiddocsOpenapiIr.SecurityScheme.Query
    | RapiddocsOpenapiIr.SecurityScheme.Oauth;

export namespace SecurityScheme {
    export interface Basic extends RapiddocsOpenapiIr.BasicSecurityScheme, _Utils {
        type: "basic";
    }

    export interface Bearer extends RapiddocsOpenapiIr.BearerSecurityScheme, _Utils {
        type: "bearer";
    }

    export interface Header extends RapiddocsOpenapiIr.HeaderSecurityScheme, _Utils {
        type: "header";
    }

    export interface Query extends RapiddocsOpenapiIr.QuerySecurityScheme, _Utils {
        type: "query";
    }

    export interface Oauth extends RapiddocsOpenapiIr.OauthSecurityScheme, _Utils {
        type: "oauth";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsOpenapiIr.SecurityScheme._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        basic: (value: RapiddocsOpenapiIr.BasicSecurityScheme) => _Result;
        bearer: (value: RapiddocsOpenapiIr.BearerSecurityScheme) => _Result;
        header: (value: RapiddocsOpenapiIr.HeaderSecurityScheme) => _Result;
        query: (value: RapiddocsOpenapiIr.QuerySecurityScheme) => _Result;
        oauth: (value: RapiddocsOpenapiIr.OauthSecurityScheme) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const SecurityScheme = {
    basic: (value: RapiddocsOpenapiIr.BasicSecurityScheme): RapiddocsOpenapiIr.SecurityScheme.Basic => {
        return {
            ...value,
            type: "basic",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.SecurityScheme.Basic,
                visitor: RapiddocsOpenapiIr.SecurityScheme._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.SecurityScheme._visit(this, visitor);
            },
        };
    },

    bearer: (value: RapiddocsOpenapiIr.BearerSecurityScheme): RapiddocsOpenapiIr.SecurityScheme.Bearer => {
        return {
            ...value,
            type: "bearer",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.SecurityScheme.Bearer,
                visitor: RapiddocsOpenapiIr.SecurityScheme._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.SecurityScheme._visit(this, visitor);
            },
        };
    },

    header: (value: RapiddocsOpenapiIr.HeaderSecurityScheme): RapiddocsOpenapiIr.SecurityScheme.Header => {
        return {
            ...value,
            type: "header",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.SecurityScheme.Header,
                visitor: RapiddocsOpenapiIr.SecurityScheme._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.SecurityScheme._visit(this, visitor);
            },
        };
    },

    query: (value: RapiddocsOpenapiIr.QuerySecurityScheme): RapiddocsOpenapiIr.SecurityScheme.Query => {
        return {
            ...value,
            type: "query",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.SecurityScheme.Query,
                visitor: RapiddocsOpenapiIr.SecurityScheme._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.SecurityScheme._visit(this, visitor);
            },
        };
    },

    oauth: (value: RapiddocsOpenapiIr.OauthSecurityScheme): RapiddocsOpenapiIr.SecurityScheme.Oauth => {
        return {
            ...value,
            type: "oauth",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.SecurityScheme.Oauth,
                visitor: RapiddocsOpenapiIr.SecurityScheme._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.SecurityScheme._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsOpenapiIr.SecurityScheme,
        visitor: RapiddocsOpenapiIr.SecurityScheme._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "basic":
                return visitor.basic(value);
            case "bearer":
                return visitor.bearer(value);
            case "header":
                return visitor.header(value);
            case "query":
                return visitor.query(value);
            case "oauth":
                return visitor.oauth(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
