/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export interface Tag extends RapiddocsOpenapiIr.WithDescription {
    id: RapiddocsOpenapiIr.TagId;
}
