/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { ValidationSchema } from "../../validation/types/ValidationSchema";

export const WithValidation: core.serialization.ObjectSchema<
    serializers.WithValidation.Raw,
    RapiddocsDefinition.WithValidation
> = core.serialization.object({
    validation: ValidationSchema.optional(),
});

export declare namespace WithValidation {
    export interface Raw {
        validation?: ValidationSchema.Raw | null;
    }
}
