/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";

export const WithAudiences: core.serialization.ObjectSchema<
    serializers.WithAudiences.Raw,
    RapiddocsDefinition.WithAudiences
> = core.serialization.object({
    audiences: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace WithAudiences {
    export interface Raw {
        audiences?: string[] | null;
    }
}
