/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface ErrorDeclarationSchema extends RapiddocsDefinition.WithDocsSchema {
    "status-code": number;
    type?: string;
    examples?: RapiddocsDefinition.ExampleTypeSchema[];
}
