/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../index";

export interface MapType {
    keyType: SeedTrace.VariableType;
    valueType: SeedTrace.VariableType;
}
