/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../../../index";

/**
 * The configuration for the generator. This is a simplified version of the
 * generator-exec GeneratorConfig configuration.
 */
export interface GeneratorConfig {
    /**
     * The name of the API. This is equivalent to the workspace name in the
     * generator-exec configuration.
     */
    apiName: string;
    organization: string;
    customConfig: unknown;
    outputConfig: RapiddocsIr.dynamic.GeneratorOutputConfig;
}
