/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../../../index";

/**
 * The configuration for the output of the generator. This is a simplified version of
 * the generator-exec output.mode configuration.
 */
export type GeneratorOutputConfig =
    | RapiddocsIr.dynamic.GeneratorOutputConfig.Publish
    | RapiddocsIr.dynamic.GeneratorOutputConfig.Local;

export namespace GeneratorOutputConfig {
    export interface Publish extends _Utils {
        type: "publish";
        value: RapiddocsIr.dynamic.PublishInfo;
    }

    export interface Local extends _Utils {
        type: "local";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.dynamic.GeneratorOutputConfig._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        publish: (value: RapiddocsIr.dynamic.PublishInfo) => _Result;
        local: () => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const GeneratorOutputConfig = {
    publish: (value: RapiddocsIr.dynamic.PublishInfo): RapiddocsIr.dynamic.GeneratorOutputConfig.Publish => {
        return {
            value: value,
            type: "publish",
            _visit: function <_Result>(
                this: RapiddocsIr.dynamic.GeneratorOutputConfig.Publish,
                visitor: RapiddocsIr.dynamic.GeneratorOutputConfig._Visitor<_Result>,
            ) {
                return RapiddocsIr.dynamic.GeneratorOutputConfig._visit(this, visitor);
            },
        };
    },

    local: (): RapiddocsIr.dynamic.GeneratorOutputConfig.Local => {
        return {
            type: "local",
            _visit: function <_Result>(
                this: RapiddocsIr.dynamic.GeneratorOutputConfig.Local,
                visitor: RapiddocsIr.dynamic.GeneratorOutputConfig._Visitor<_Result>,
            ) {
                return RapiddocsIr.dynamic.GeneratorOutputConfig._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsIr.dynamic.GeneratorOutputConfig,
        visitor: RapiddocsIr.dynamic.GeneratorOutputConfig._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "publish":
                return visitor.publish(value.value);
            case "local":
                return visitor.local();
            default:
                return visitor._other(value as any);
        }
    },
} as const;
