/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export interface CommonProperty {
    key: string;
    schema: RapiddocsOpenapiIr.Schema;
}
