/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export interface EndpointSdkName {
    /** This is populated by `x-rapiddocs-sdk-method-name` */
    groupName: RapiddocsOpenapiIr.SdkGroupName;
    /** This is populated by `x-rapiddocs-sdk-group-name` */
    methodName: string;
}
