/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export interface FileSchema extends RapiddocsOpenapiIr.WithDescription {
    isOptional: boolean;
    isArray: boolean;
}
