/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export interface HeaderExample {
    name: string;
    value: RapiddocsOpenapiIr.FullExample;
}
