/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export interface HttpEndpointServer {
    /** Populated by `X-Server-Name` */
    name: string | undefined;
    url: string | undefined;
    audiences: string[] | undefined;
}
