/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export type Pagination =
    | RapiddocsOpenapiIr.Pagination.Cursor
    | RapiddocsOpenapiIr.Pagination.Offset
    | RapiddocsOpenapiIr.Pagination.Custom;

export namespace Pagination {
    export interface Cursor extends RapiddocsOpenapiIr.CursorPagination, _Utils {
        type: "cursor";
    }

    export interface Offset extends RapiddocsOpenapiIr.OffsetPagination, _Utils {
        type: "offset";
    }

    export interface Custom extends RapiddocsOpenapiIr.CustomPagination, _Utils {
        type: "custom";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsOpenapiIr.Pagination._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        cursor: (value: RapiddocsOpenapiIr.CursorPagination) => _Result;
        offset: (value: RapiddocsOpenapiIr.OffsetPagination) => _Result;
        custom: (value: RapiddocsOpenapiIr.CustomPagination) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const Pagination = {
    cursor: (value: RapiddocsOpenapiIr.CursorPagination): RapiddocsOpenapiIr.Pagination.Cursor => {
        return {
            ...value,
            type: "cursor",
            _visit <_Result>(
                this: RapiddocsOpenapiIr.Pagination.Cursor,
                visitor: RapiddocsOpenapiIr.Pagination._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.Pagination._visit(this, visitor);
            },
        };
    },

    offset: (value: RapiddocsOpenapiIr.OffsetPagination): RapiddocsOpenapiIr.Pagination.Offset => {
        return {
            ...value,
            type: "offset",
            _visit <_Result>(
                this: RapiddocsOpenapiIr.Pagination.Offset,
                visitor: RapiddocsOpenapiIr.Pagination._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.Pagination._visit(this, visitor);
            },
        };
    },

    custom: (value: RapiddocsOpenapiIr.CustomPagination): RapiddocsOpenapiIr.Pagination.Custom => {
        return {
            ...value,
            type: "custom",
            _visit <_Result>(
                this: RapiddocsOpenapiIr.Pagination.Custom,
                visitor: RapiddocsOpenapiIr.Pagination._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.Pagination._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsOpenapiIr.Pagination,
        visitor: RapiddocsOpenapiIr.Pagination._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "cursor":
                return visitor.cursor(value);
            case "offset":
                return visitor.offset(value);
            case "custom":
                return visitor.custom(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
