/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export interface PathParameter
    extends RapiddocsOpenapiIr.WithDescription,
        RapiddocsOpenapiIr.WithAvailability,
        RapiddocsOpenapiIr.WithSource {
    name: string;
    schema: RapiddocsOpenapiIr.Schema;
    variableReference: string | undefined;
    /** Populated by `x-rapiddocs-parameter-name` on a parameter object. */
    parameterNameOverride: string | undefined;
}
