/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export type PrimitiveSchemaValue =
    | RapiddocsOpenapiIr.PrimitiveSchemaValue.Int
    | RapiddocsOpenapiIr.PrimitiveSchemaValue.Int64
    | RapiddocsOpenapiIr.PrimitiveSchemaValue.Uint
    | RapiddocsOpenapiIr.PrimitiveSchemaValue.Uint64
    | RapiddocsOpenapiIr.PrimitiveSchemaValue.Float
    | RapiddocsOpenapiIr.PrimitiveSchemaValue.Double
    | RapiddocsOpenapiIr.PrimitiveSchemaValue.String
    | RapiddocsOpenapiIr.PrimitiveSchemaValue.Datetime
    | RapiddocsOpenapiIr.PrimitiveSchemaValue.Date_
    | RapiddocsOpenapiIr.PrimitiveSchemaValue.Base64
    | RapiddocsOpenapiIr.PrimitiveSchemaValue.Boolean;

export namespace PrimitiveSchemaValue {
    export interface Int extends RapiddocsOpenapiIr.IntSchema, _Utils {
        type: "int";
    }

    export interface Int64 extends RapiddocsOpenapiIr.LongSchema, _Utils {
        type: "int64";
    }

    export interface Uint extends _Utils {
        type: "uint";
    }

    export interface Uint64 extends _Utils {
        type: "uint64";
    }

    export interface Float extends _Utils {
        type: "float";
    }

    export interface Double extends RapiddocsOpenapiIr.DoubleSchema, _Utils {
        type: "double";
    }

    export interface String extends RapiddocsOpenapiIr.StringSchema, _Utils {
        type: "string";
    }

    export interface Datetime extends _Utils {
        type: "datetime";
    }

    export interface Date_ extends _Utils {
        type: "date";
    }

    export interface Base64 extends _Utils {
        type: "base64";
    }

    export interface Boolean extends RapiddocsOpenapiIr.BooleanSchema, _Utils {
        type: "boolean";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsOpenapiIr.PrimitiveSchemaValue._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        int: (value: RapiddocsOpenapiIr.IntSchema) => _Result;
        int64: (value: RapiddocsOpenapiIr.LongSchema) => _Result;
        uint: () => _Result;
        uint64: () => _Result;
        float: () => _Result;
        double: (value: RapiddocsOpenapiIr.DoubleSchema) => _Result;
        string: (value: RapiddocsOpenapiIr.StringSchema) => _Result;
        datetime: () => _Result;
        date: () => _Result;
        base64: () => _Result;
        boolean: (value: RapiddocsOpenapiIr.BooleanSchema) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const PrimitiveSchemaValue = {
    int: (value: RapiddocsOpenapiIr.IntSchema): RapiddocsOpenapiIr.PrimitiveSchemaValue.Int => {
        return {
            ...value,
            type: "int",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValue.Int,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValue._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValue._visit(this, visitor);
            },
        };
    },

    int64: (value: RapiddocsOpenapiIr.LongSchema): RapiddocsOpenapiIr.PrimitiveSchemaValue.Int64 => {
        return {
            ...value,
            type: "int64",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValue.Int64,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValue._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValue._visit(this, visitor);
            },
        };
    },

    uint: (): RapiddocsOpenapiIr.PrimitiveSchemaValue.Uint => {
        return {
            type: "uint",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValue.Uint,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValue._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValue._visit(this, visitor);
            },
        };
    },

    uint64: (): RapiddocsOpenapiIr.PrimitiveSchemaValue.Uint64 => {
        return {
            type: "uint64",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValue.Uint64,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValue._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValue._visit(this, visitor);
            },
        };
    },

    float: (): RapiddocsOpenapiIr.PrimitiveSchemaValue.Float => {
        return {
            type: "float",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValue.Float,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValue._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValue._visit(this, visitor);
            },
        };
    },

    double: (value: RapiddocsOpenapiIr.DoubleSchema): RapiddocsOpenapiIr.PrimitiveSchemaValue.Double => {
        return {
            ...value,
            type: "double",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValue.Double,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValue._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValue._visit(this, visitor);
            },
        };
    },

    string: (value: RapiddocsOpenapiIr.StringSchema): RapiddocsOpenapiIr.PrimitiveSchemaValue.String => {
        return {
            ...value,
            type: "string",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValue.String,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValue._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValue._visit(this, visitor);
            },
        };
    },

    datetime: (): RapiddocsOpenapiIr.PrimitiveSchemaValue.Datetime => {
        return {
            type: "datetime",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValue.Datetime,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValue._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValue._visit(this, visitor);
            },
        };
    },

    date: (): RapiddocsOpenapiIr.PrimitiveSchemaValue.Date_ => {
        return {
            type: "date",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValue.Date_,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValue._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValue._visit(this, visitor);
            },
        };
    },

    base64: (): RapiddocsOpenapiIr.PrimitiveSchemaValue.Base64 => {
        return {
            type: "base64",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValue.Base64,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValue._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValue._visit(this, visitor);
            },
        };
    },

    boolean: (value: RapiddocsOpenapiIr.BooleanSchema): RapiddocsOpenapiIr.PrimitiveSchemaValue.Boolean => {
        return {
            ...value,
            type: "boolean",
            _visit: function <_Result>(
                this: RapiddocsOpenapiIr.PrimitiveSchemaValue.Boolean,
                visitor: RapiddocsOpenapiIr.PrimitiveSchemaValue._Visitor<_Result>,
            ) {
                return RapiddocsOpenapiIr.PrimitiveSchemaValue._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsOpenapiIr.PrimitiveSchemaValue,
        visitor: RapiddocsOpenapiIr.PrimitiveSchemaValue._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "int":
                return visitor.int(value);
            case "int64":
                return visitor.int64(value);
            case "uint":
                return visitor.uint();
            case "uint64":
                return visitor.uint64();
            case "float":
                return visitor.float();
            case "double":
                return visitor.double(value);
            case "string":
                return visitor.string(value);
            case "datetime":
                return visitor.datetime();
            case "date":
                return visitor.date();
            case "base64":
                return visitor.base64();
            case "boolean":
                return visitor.boolean(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
