/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export interface ReferencedSchema
    extends RapiddocsOpenapiIr.WithDescription,
        RapiddocsOpenapiIr.WithName,
        RapiddocsOpenapiIr.WithSdkGroupName,
        RapiddocsOpenapiIr.WithAvailability,
        RapiddocsOpenapiIr.WithSource,
        RapiddocsOpenapiIr.WithTitle {
    schema: RapiddocsOpenapiIr.SchemaId;
}
