/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export interface TextResponse
    extends RapiddocsOpenapiIr.WithDescription,
        RapiddocsOpenapiIr.WithSource,
        RapiddocsOpenapiIr.WithStatusCode {}
