/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";

export const ProtobufSourceSchema: core.serialization.ObjectSchema<
    serializers.ProtobufSourceSchema.Raw,
    RapiddocsDefinition.ProtobufSourceSchema
> = core.serialization.object({
    proto: core.serialization.string(),
});

export declare namespace ProtobufSourceSchema {
    export interface Raw {
        proto: string;
    }
}
