/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

/**
 * @example
 *     {
 *         s3Key: "s3Key"
 *     }
 */
export interface GetPresignedUrlRequest {
    s3Key: string;
}
