/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { VersionValue } from "./VersionValue";
import { VersionDeclarationHeaderSchema } from "./VersionDeclarationHeaderSchema";

export const VersionDeclarationSchema: core.serialization.ObjectSchema<
    serializers.VersionDeclarationSchema.Raw,
    RapiddocsDefinition.VersionDeclarationSchema
> = core.serialization.object({
    default: core.serialization.string().optional(),
    values: core.serialization.list(VersionValue),
    header: VersionDeclarationHeaderSchema,
});

export declare namespace VersionDeclarationSchema {
    export interface Raw {
        default?: string | null;
        values: VersionValue.Raw[];
        header: VersionDeclarationHeaderSchema.Raw;
    }
}
