/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";

export const VersionDeclarationHeaderObjectSchema: core.serialization.ObjectSchema<
    serializers.VersionDeclarationHeaderObjectSchema.Raw,
    RapiddocsDefinition.VersionDeclarationHeaderObjectSchema
> = core.serialization.object({
    name: core.serialization.string().optional(),
    env: core.serialization.string().optional(),
    value: core.serialization.string(),
});

export declare namespace VersionDeclarationHeaderObjectSchema {
    export interface Raw {
        name?: string | null;
        env?: string | null;
        value: string;
    }
}
