/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

/**
 * The available set of versions for the API. This is used to generate a special
 * enum that can be used to specify the version of the API to use.
 */
export type ApiVersionScheme = RapiddocsIr.ApiVersionScheme.Header;

export namespace ApiVersionScheme {
    export interface Header extends RapiddocsIr.HeaderApiVersionScheme, _Utils {
        type: "header";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.ApiVersionScheme._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        header: (value: RapiddocsIr.HeaderApiVersionScheme) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const ApiVersionScheme = {
    header: (value: RapiddocsIr.HeaderApiVersionScheme): RapiddocsIr.ApiVersionScheme.Header => {
        return {
            ...value,
            type: "header",
            _visit: function <_Result>(
                this: RapiddocsIr.ApiVersionScheme.Header,
                visitor: RapiddocsIr.ApiVersionScheme._Visitor<_Result>,
            ) {
                return RapiddocsIr.ApiVersionScheme._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(value: RapiddocsIr.ApiVersionScheme, visitor: RapiddocsIr.ApiVersionScheme._Visitor<_Result>): _Result => {
        switch (value.type) {
            case "header":
                return visitor.header(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
