/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface PlatformHeaders {
    language: string;
    sdkName: string;
    sdkVersion: string;
    userAgent: RapiddocsIr.UserAgent | undefined;
}
