/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface ServiceTypeReferenceInfo {
    /** Types referenced by exactly one service. */
    typesReferencedOnlyByService: Record<RapiddocsIr.ServiceId, RapiddocsIr.TypeId[]>;
    /** Types referenced by either zero or multiple services. */
    sharedTypes: RapiddocsIr.TypeId[];
}
