/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../index";

export interface SubmitRequestV2 {
    submissionId: SeedTrace.SubmissionId;
    language: SeedTrace.Language;
    submissionFiles: SeedTrace.SubmissionFileInfo[];
    problemId: SeedTrace.ProblemId;
    problemVersion?: number;
    userId?: string;
}
