/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";

export const StatusCodeBasedErrorDiscrimination: core.serialization.ObjectSchema<
    serializers.StatusCodeBasedErrorDiscrimination.Raw,
    RapiddocsDefinition.StatusCodeBasedErrorDiscrimination
> = core.serialization.object({
    strategy: core.serialization.stringLiteral("status-code"),
});

export declare namespace StatusCodeBasedErrorDiscrimination {
    export interface Raw {
        strategy: "status-code";
    }
}
