/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsDefinition from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { TypeReferenceDeclarationWithName } from "../../types/types/TypeReferenceDeclarationWithName";

export const TypeReferenceDeclarationWithEnvOverrideSchema: core.serialization.ObjectSchema<
    serializers.rapiddocsDefinition.TypeReferenceDeclarationWithEnvOverrideSchema.Raw,
    RapiddocsDefinition.rapiddocsDefinition.TypeReferenceDeclarationWithEnvOverrideSchema
> = core.serialization
    .object({
        env: core.serialization.string().optional(),
    })
    .extend(TypeReferenceDeclarationWithName);

export declare namespace TypeReferenceDeclarationWithEnvOverrideSchema {
    export interface Raw extends TypeReferenceDeclarationWithName.Raw {
        env?: string | null;
    }
}
