/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export class SeedAuthEnvironmentVariablesTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, SeedAuthEnvironmentVariablesTimeoutError.prototype);
    }
}
