/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export const SeedSingleUrlEnvironmentDefaultEnvironment = {
    Production: "https://production.com/api",
    Staging: "https://staging.com/api",
} as const;

export type SeedSingleUrlEnvironmentDefaultEnvironment =
    | typeof SeedSingleUrlEnvironmentDefaultEnvironment.Production
    | typeof SeedSingleUrlEnvironmentDefaultEnvironment.Staging;
