# This file was auto-generated by Rapiddocs from our API Definition.

from .resources import Circle, Color, Shape, Square, UndiscriminatedShape, types

__all__ = ["Circle", "Color", "Shape", "Square", "UndiscriminatedShape", "types"]
