/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedPagination from "../../../index";

export type SearchRequestQuery = SeedPagination.SingleFilterSearchRequest | SeedPagination.MultipleFilterSearchRequest;
