/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export type ReservedKeywordEnum = "is" | "as";
export const ReservedKeywordEnum = {
    Is: "is",
    As: "as",
} as const;
