/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";

export const PropertyKey: core.serialization.Schema<serializers.PropertyKey.Raw, RapiddocsOpenapiIr.PropertyKey> =
    core.serialization.string();

export declare namespace PropertyKey {
    export type Raw = string;
}
