/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedPagination from "../../../../index";

export interface ListUsersBodyCursorPaginationRequest {
    pagination?: SeedPagination.WithCursor;
}
