# This file was auto-generated by Rapiddocs from our API Definition.

from ......core.exceptions.rapiddocs_http_exception import RapiddocsHTTPException
from ..types.nested_object_with_optional_field import NestedObjectWithOptionalField


class NestedObjectWithOptionalFieldError(RapiddocsHTTPException):
    def __init__(self, error: NestedObjectWithOptionalField):
        super().__init__(
            status_code=400, name="NestedObjectWithOptionalFieldError", content=error
        )
