/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

/**
 * @example
 *     {
 *         clientId: "client_id",
 *         clientSecret: "client_secret",
 *         scope: "scope"
 *     }
 */
export interface GetTokenRequest {
    clientId: string;
    clientSecret: string;
    scope?: string;
}
