/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface Webhook extends RapiddocsIr.Declaration {
    id: RapiddocsIr.WebhookId;
    name: RapiddocsIr.WebhookName;
    displayName: string | undefined;
    method: RapiddocsIr.WebhookHttpMethod;
    headers: RapiddocsIr.HttpHeader[];
    payload: RapiddocsIr.WebhookPayload;
    examples: RapiddocsIr.ExampleWebhookCall[] | undefined;
}
