/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../../../index";

export interface TestCaseImplementation {
    description: SeedTrace.v2.TestCaseImplementationDescription;
    function: SeedTrace.v2.TestCaseFunction;
}
