/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */
package com.seed.nullable;

public final class TestClient {
    public void test() {
        // Add tests here and mark this file in .rapiddocsignore
        assert true;
    }
}
