# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/rapiddocs/main/rapiddocs.schema.json

imports:
  folderBCommons: ../folder-b/common.yml

service:
  auth: false
  audiences:
    - partner
  base-path: /
  endpoints:
    getDirectThread:
      path: ""
      method: GET
      response: Response

types:
  Response:
    properties:
      foo: optional<folderBCommons.Foo>
