/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export interface PostmanPublishTarget {
    apiKey: string;
    workspaceId: string;
    collectionId: string | undefined;
}
