/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsConjure from "../../../../api/index";
import * as core from "../../../../core";
import { ConjureTypes } from "../../types/types/ConjureTypes";
import { ConjureServiceName } from "./ConjureServiceName";
import { ConjureService } from "../../services/types/ConjureService";

export const DefinitionFile: core.serialization.ObjectSchema<
    serializers.DefinitionFile.Raw,
    RapiddocsConjure.DefinitionFile
> = core.serialization.objectWithoutOptionalProperties({
    types: ConjureTypes.optional(),
    services: core.serialization.record(ConjureServiceName, ConjureService).optional(),
});

export declare namespace DefinitionFile {
    export interface Raw {
        types?: ConjureTypes.Raw | null;
        services?: Record<ConjureServiceName.Raw, ConjureService.Raw> | null;
    }
}
