/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export class SeedWebsocketTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, SeedWebsocketTimeoutError.prototype);
    }
}
