/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsIr from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { PublishInfo } from "./PublishInfo";

export const GeneratorOutputConfig: core.serialization.Schema<
    serializers.dynamic.GeneratorOutputConfig.Raw,
    RapiddocsIr.dynamic.GeneratorOutputConfig
> = core.serialization
    .union("type", {
        publish: core.serialization.object({
            value: PublishInfo,
        }),
        local: core.serialization.object({}),
    })
    .transform<RapiddocsIr.dynamic.GeneratorOutputConfig>({
        transform: (value) => {
            switch (value.type) {
                case "publish":
                    return RapiddocsIr.dynamic.GeneratorOutputConfig.publish(value.value);
                case "local":
                    return RapiddocsIr.dynamic.GeneratorOutputConfig.local();
                default:
                    return value as RapiddocsIr.dynamic.GeneratorOutputConfig;
            }
        },
        untransform: ({ _visit, ...value }) => value as any,
    });

export declare namespace GeneratorOutputConfig {
    export type Raw = GeneratorOutputConfig.Publish | GeneratorOutputConfig.Local;

    export interface Publish {
        type: "publish";
        value: PublishInfo.Raw;
    }

    export interface Local {
        type: "local";
    }
}
