/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsIr from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const MavenPublishInfo: core.serialization.ObjectSchema<
    serializers.dynamic.MavenPublishInfo.Raw,
    RapiddocsIr.dynamic.MavenPublishInfo
> = core.serialization.objectWithoutOptionalProperties({
    version: core.serialization.string(),
    coordinate: core.serialization.string(),
    repoUrl: core.serialization.string().optional(),
});

export declare namespace MavenPublishInfo {
    export interface Raw {
        version: string;
        coordinate: string;
        repoUrl?: string | null;
    }
}
