/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsIr from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { GoPublishInfo } from "./GoPublishInfo";
import { MavenPublishInfo } from "./MavenPublishInfo";
import { NpmPublishInfo } from "./NpmPublishInfo";
import { NugetPublishInfo } from "./NugetPublishInfo";
import { PypiPublishInfo } from "./PypiPublishInfo";
import { RubyGemsPublishInfo } from "./RubyGemsPublishInfo";

export const PublishInfo: core.serialization.Schema<serializers.dynamic.PublishInfo.Raw, RapiddocsIr.dynamic.PublishInfo> =
    core.serialization
        .union("type", {
            go: GoPublishInfo,
            maven: MavenPublishInfo,
            npm: NpmPublishInfo,
            nuget: NugetPublishInfo,
            pypi: PypiPublishInfo,
            rubygems: RubyGemsPublishInfo,
        })
        .transform<RapiddocsIr.dynamic.PublishInfo>({
            transform: (value) => {
                switch (value.type) {
                    case "go":
                        return RapiddocsIr.dynamic.PublishInfo.go(value);
                    case "maven":
                        return RapiddocsIr.dynamic.PublishInfo.maven(value);
                    case "npm":
                        return RapiddocsIr.dynamic.PublishInfo.npm(value);
                    case "nuget":
                        return RapiddocsIr.dynamic.PublishInfo.nuget(value);
                    case "pypi":
                        return RapiddocsIr.dynamic.PublishInfo.pypi(value);
                    case "rubygems":
                        return RapiddocsIr.dynamic.PublishInfo.rubygems(value);
                    default:
                        return value as RapiddocsIr.dynamic.PublishInfo;
                }
            },
            untransform: ({ _visit, ...value }) => value as any,
        });

export declare namespace PublishInfo {
    export type Raw =
        | PublishInfo.Go
        | PublishInfo.Maven
        | PublishInfo.Npm
        | PublishInfo.Nuget
        | PublishInfo.Pypi
        | PublishInfo.Rubygems;

    export interface Go extends GoPublishInfo.Raw {
        type: "go";
    }

    export interface Maven extends MavenPublishInfo.Raw {
        type: "maven";
    }

    export interface Npm extends NpmPublishInfo.Raw {
        type: "npm";
    }

    export interface Nuget extends NugetPublishInfo.Raw {
        type: "nuget";
    }

    export interface Pypi extends PypiPublishInfo.Raw {
        type: "pypi";
    }

    export interface Rubygems extends RubyGemsPublishInfo.Raw {
        type: "rubygems";
    }
}
