/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsDefinition from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { StringValidationSchema } from "./StringValidationSchema";
import { NumberValidationSchema } from "./NumberValidationSchema";

export const ValidationSchema: core.serialization.Schema<
    serializers.rapiddocsDefinition.ValidationSchema.Raw,
    RapiddocsDefinition.rapiddocsDefinition.ValidationSchema
> = core.serialization.undiscriminatedUnion([StringValidationSchema, NumberValidationSchema]);

export declare namespace ValidationSchema {
    export type Raw = StringValidationSchema.Raw | NumberValidationSchema.Raw;
}
