/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedApi from "../index";

export interface BaseResource {
    id: string;
    relatedResources: SeedApi.ResourceList[];
    memo: SeedApi.Memo;
}
