/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDocsConfig from "../../../index";

export interface AnalyticsConfig {
    segment?: RapiddocsDocsConfig.SegmentConfig;
    fullstory?: RapiddocsDocsConfig.FullStoryAnalyticsConfig;
    intercom?: RapiddocsDocsConfig.IntercomConfig;
    posthog?: RapiddocsDocsConfig.PostHogConfig;
    gtm?: RapiddocsDocsConfig.GtmConfig;
    ga4?: RapiddocsDocsConfig.GoogleAnalytics4Config;
}
