/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDocsConfig from "../../../index";

export type ApiReferencePackageConfiguration =
    | RapiddocsDocsConfig.ApiReferenceLayoutItem[]
    | RapiddocsDocsConfig.ApiReferencePackageConfigurationWithOptions;
