/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDocsConfig from "../../../index";

/**
 * This background image is used to customize the appearance of your docs site.
 */
export type BackgroundImageConfiguration = string | RapiddocsDocsConfig.BackgroundImageThemedConfig;
