/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export type ContentAlignment = "center" | "left";
export const ContentAlignment = {
    Center: "center",
    Left: "left",
} as const;
