/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDocsConfig from "../../../index";

export interface DocsInstance {
    url: string;
    customDomain?: RapiddocsDocsConfig.CustomDomain;
    /** This config option is no longer used. Please reach out to the Rapiddocs Team if you want to enable private docs. */
    private?: boolean;
    /** If `edit-this-page` is set, Rapiddocs will add an "Edit this page" link to the bottom of each page that links to the given GitHub repository. */
    editThisPage?: RapiddocsDocsConfig.EditThisPageConfig;
}
