/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export interface GithubEditThisPageConfig {
    /** @default: `github.com` */
    host?: string;
    owner: string;
    repo: string;
    /** @default: `main` */
    branch?: string;
}
