/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDocsConfig from "../../../index";

export interface JsFileConfigSettings {
    path: string;
    strategy?: RapiddocsDocsConfig.JsScriptStrategy;
}
