/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDocsConfig from "../../../index";

export type NavbarLink =
    | RapiddocsDocsConfig.NavbarLink.Filled
    | RapiddocsDocsConfig.NavbarLink.Outlined
    | RapiddocsDocsConfig.NavbarLink.Minimal
    | RapiddocsDocsConfig.NavbarLink.Github
    | RapiddocsDocsConfig.NavbarLink.Primary
    | RapiddocsDocsConfig.NavbarLink.Secondary;

export namespace NavbarLink {
    export interface Filled extends RapiddocsDocsConfig.NavbarLinkConfig {
        type: "filled";
    }

    export interface Outlined extends RapiddocsDocsConfig.NavbarLinkConfig {
        type: "outlined";
    }

    export interface Minimal extends RapiddocsDocsConfig.NavbarLinkConfig {
        type: "minimal";
    }

    export interface Github {
        type: "github";
        value: RapiddocsDocsConfig.NavbarGithubConfig;
    }

    export interface Primary extends RapiddocsDocsConfig.NavbarLinkConfig {
        type: "primary";
    }

    export interface Secondary extends RapiddocsDocsConfig.NavbarLinkConfig {
        type: "secondary";
    }
}
