/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDocsConfig from "../../../index";

/**
 * Audience can either be a string or list of strings
 * i.e. `audience: internal` or `audience: [internal, beta]`
 */
export type Role = RapiddocsDocsConfig.RoleId | RapiddocsDocsConfig.RoleId[];
