/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDocsConfig from "../../../index";

/**
 * This snippets config object is meant to allow users to specify a specific package for the snippets,
 * and optionally a version for that package. If you pass in a string, that should be the name of the package.
 */
export type SnippetLanguageConfiguration = string | RapiddocsDocsConfig.VersionedSnippetLanguageConfiguration;
