/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDocsConfig from "../../../index";

export interface TabbedNavigationItem {
    tab: RapiddocsDocsConfig.TabId;
    /** If `href` is set, `layout` must be null. */
    layout?: RapiddocsDocsConfig.NavigationItem[];
}
