/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDocsConfig from "../../../index";

export interface TabConfig extends RapiddocsDocsConfig.WithPermissions, RapiddocsDocsConfig.WithFeatureFlags {
    displayName: string;
    icon?: string;
    slug?: string;
    skipSlug?: boolean;
    hidden?: boolean;
    /**
     * If `href` is set, clicking on the tab will redirect to the given URL.
     *
     * Tabs with `href` must not have children in the navigation config.
     */
    href?: string;
    changelog?: RapiddocsDocsConfig.ChangelogFolderRelativePath;
}
