/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export type TabsPlacement = "header" | "sidebar";
export const TabsPlacement = {
    Header: "header",
    Sidebar: "sidebar",
} as const;
