/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export type VersionAvailability = "deprecated" | "ga" | "stable" | "beta";
export const VersionAvailability = {
    Deprecated: "deprecated",
    Ga: "ga",
    Stable: "stable",
    Beta: "beta",
} as const;
