/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface WebhookSchema
    extends RapiddocsDefinition.WithAvailability,
        RapiddocsDefinition.WithAudiences,
        RapiddocsDefinition.WithDocsSchema,
        RapiddocsDefinition.WithDisplayName {
    method: RapiddocsDefinition.WebhookMethodSchema;
    headers?: Record<string, RapiddocsDefinition.HttpHeaderSchema>;
    payload: RapiddocsDefinition.WebhookPayloadSchema;
    examples?: RapiddocsDefinition.ExampleWebhookCallSchema[];
}
