/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsDefinition from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { AvailabilityStatusSchema } from "./AvailabilityStatusSchema";

export const AvailabilitySchema: core.serialization.ObjectSchema<
    serializers.rapiddocsDefinition.AvailabilitySchema.Raw,
    RapiddocsDefinition.rapiddocsDefinition.AvailabilitySchema
> = core.serialization.object({
    status: AvailabilityStatusSchema,
    message: core.serialization.string().optional(),
});

export declare namespace AvailabilitySchema {
    export interface Raw {
        status: AvailabilityStatusSchema.Raw;
        message?: string | null;
    }
}
