/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsDefinition from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { AvailabilityStatusSchema } from "./AvailabilityStatusSchema";
import { AvailabilitySchema } from "./AvailabilitySchema";

export const AvailabilityUnionSchema: core.serialization.Schema<
    serializers.rapiddocsDefinition.AvailabilityUnionSchema.Raw,
    RapiddocsDefinition.rapiddocsDefinition.AvailabilityUnionSchema
> = core.serialization.undiscriminatedUnion([AvailabilityStatusSchema, AvailabilitySchema]);

export declare namespace AvailabilityUnionSchema {
    export type Raw = AvailabilityStatusSchema.Raw | AvailabilitySchema.Raw;
}
