# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/rapiddocs/main/rapiddocs.schema.json

imports:
  commons: commons.yml
types:
  EnvironmentId: string
  EnvironmentBaseUrlId: string
  EnvironmentUrl: string
  EnvironmentsConfig:
    properties:
      defaultEnvironment: optional<EnvironmentId>
      environments: Environments
  Environments:
    union:
      singleBaseUrl: SingleBaseUrlEnvironments
      multipleBaseUrls: MultipleBaseUrlsEnvironments
  SingleBaseUrlEnvironments:
    properties:
      environments: list<SingleBaseUrlEnvironment>
  SingleBaseUrlEnvironment:
    extends: commons.WithDocs
    properties:
      id: EnvironmentId
      name: commons.Name
      url: EnvironmentUrl
  MultipleBaseUrlsEnvironments:
    properties:
      baseUrls: list<EnvironmentBaseUrlWithId>
      environments: list<MultipleBaseUrlsEnvironment>
  MultipleBaseUrlsEnvironment:
    extends: commons.WithDocs
    properties:
      id: EnvironmentId
      name: commons.Name
      urls: map<EnvironmentBaseUrlId, EnvironmentUrl>
  EnvironmentBaseUrlWithId:
    properties:
      id: EnvironmentBaseUrlId
      name: commons.Name
