/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";

export const MavenOutputSignatureSchema: core.serialization.ObjectSchema<
    serializers.MavenOutputSignatureSchema.Raw,
    RapiddocsDefinition.MavenOutputSignatureSchema
> = core.serialization.object({
    keyId: core.serialization.string(),
    password: core.serialization.string(),
    secretKey: core.serialization.string(),
});

export declare namespace MavenOutputSignatureSchema {
    export interface Raw {
        keyId: string;
        password: string;
        secretKey: string;
    }
}
