/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";

export const NpmOutputLocationSchema: core.serialization.ObjectSchema<
    serializers.NpmOutputLocationSchema.Raw,
    RapiddocsDefinition.NpmOutputLocationSchema
> = core.serialization.object({
    url: core.serialization.string().optional(),
    "package-name": core.serialization.string(),
    token: core.serialization.string().optional(),
});

export declare namespace NpmOutputLocationSchema {
    export interface Raw {
        url?: string | null;
        "package-name": string;
        token?: string | null;
    }
}
