/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../../../index";

export type AvailabilityUnionSchema =
    | RapiddocsDefinition.rapiddocsDefinition.AvailabilityStatusSchema
    | RapiddocsDefinition.rapiddocsDefinition.AvailabilitySchema;
