/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export type MultipleFilterSearchRequestOperator = "AND" | "OR";
export const MultipleFilterSearchRequestOperator = {
    And: "AND",
    Or: "OR",
} as const;
