// This file was auto-generated by Rapiddocs from our API Definition.

package authenvironmentvariables

type HeaderAuthRequest struct {
	// Specifies the endpoint key.
	XEndpointHeader string `json:"-" url:"-"`
}
