// This file was auto-generated by Rapiddocs from our API Definition.

package client

import (
	core "github.com/circular-references/rapiddocs/core"
	internal "github.com/circular-references/rapiddocs/internal"
	option "github.com/circular-references/rapiddocs/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}
