/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { NameAndWireValue } from "../../commons/types/NameAndWireValue";

export const Constants: core.serialization.ObjectSchema<serializers.Constants.Raw, RapiddocsIr.Constants> =
    core.serialization.objectWithoutOptionalProperties({
        errorInstanceIdKey: NameAndWireValue,
    });

export declare namespace Constants {
    export interface Raw {
        errorInstanceIdKey: NameAndWireValue.Raw;
    }
}
