/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedExhaustive from "../../../../../index";

export interface NestedObjectWithOptionalField {
    string?: string;
    NestedObject?: SeedExhaustive.types.ObjectWithOptionalField;
}
