/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface VersionDeclarationSchema {
    default?: string;
    values: RapiddocsDefinition.VersionValue[];
    header: RapiddocsDefinition.VersionDeclarationHeaderSchema;
}
