/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface VersionValueDetailed extends RapiddocsDefinition.WithDocsSchema, RapiddocsDefinition.WithName {
    value: string;
}
