/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedObject from "../../index";

export interface GetUndiscriminatedUnionRequest {
    bar: SeedObject.UndiscriminatedUnion1;
    foo: string;
}
