/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedObject from "../../index";

export interface PostRootRequest {
    bar: SeedObject.RequestTypeInlineType1;
    foo: string;
}
