/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedFileUpload from "../../../../index";

export interface WithContentTypeRequest {
    foo: string;
    bar: SeedFileUpload.MyObject;
    fooBar?: SeedFileUpload.MyObject;
}
