/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export type AliasListInline = AliasListInline.Item[];

export namespace AliasListInline {
    export interface Item {
        foo: string;
        bar: string;
    }
}
