/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { PublishTarget } from "./PublishTarget";

export const DirectPublish: core.serialization.ObjectSchema<serializers.DirectPublish.Raw, RapiddocsIr.DirectPublish> =
    core.serialization.objectWithoutOptionalProperties({
        target: PublishTarget,
    });

export declare namespace DirectPublish {
    export interface Raw {
        target: PublishTarget.Raw;
    }
}
