/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { PublishTarget } from "./PublishTarget";

export const GithubPublish: core.serialization.ObjectSchema<serializers.GithubPublish.Raw, RapiddocsIr.GithubPublish> =
    core.serialization.objectWithoutOptionalProperties({
        owner: core.serialization.string(),
        repo: core.serialization.string(),
        target: PublishTarget,
    });

export declare namespace GithubPublish {
    export interface Raw {
        owner: string;
        repo: string;
        target: PublishTarget.Raw;
    }
}
