/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsConjure from "../../../index";

export interface ConjureTypes {
    conjureImports: Record<string, string> | undefined;
    definitions: RapiddocsConjure.ConjureDefinitions | undefined;
}
