/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsConjure from "../../../index";

export interface ConjureTypeWithDocs {
    type: RapiddocsConjure.ConjureType;
    docs: string | undefined;
}
