/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { CsharpProtobufFileOptions } from "./CsharpProtobufFileOptions";

export const ProtobufFileOptions: core.serialization.ObjectSchema<
    serializers.ProtobufFileOptions.Raw,
    RapiddocsIr.ProtobufFileOptions
> = core.serialization.objectWithoutOptionalProperties({
    csharp: CsharpProtobufFileOptions.optional(),
});

export declare namespace ProtobufFileOptions {
    export interface Raw {
        csharp?: CsharpProtobufFileOptions.Raw | null;
    }
}
