/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const WellKnownProtobufType: core.serialization.Schema<
    serializers.WellKnownProtobufType.Raw,
    RapiddocsIr.WellKnownProtobufType
> = core.serialization
    .union("type", {
        any: core.serialization.object({}),
        api: core.serialization.object({}),
        boolValue: core.serialization.object({}),
        bytesValue: core.serialization.object({}),
        doubleValue: core.serialization.object({}),
        duration: core.serialization.object({}),
        empty: core.serialization.object({}),
        enum: core.serialization.object({}),
        enumValue: core.serialization.object({}),
        field: core.serialization.object({}),
        fieldCardinality: core.serialization.object({}),
        fieldKind: core.serialization.object({}),
        fieldMask: core.serialization.object({}),
        floatValue: core.serialization.object({}),
        int32Value: core.serialization.object({}),
        int64Value: core.serialization.object({}),
        listValue: core.serialization.object({}),
        method: core.serialization.object({}),
        mixin: core.serialization.object({}),
        nullValue: core.serialization.object({}),
        option: core.serialization.object({}),
        sourceContext: core.serialization.object({}),
        stringValue: core.serialization.object({}),
        struct: core.serialization.object({}),
        syntax: core.serialization.object({}),
        timestamp: core.serialization.object({}),
        type: core.serialization.object({}),
        uint32Value: core.serialization.object({}),
        uint64Value: core.serialization.object({}),
        value: core.serialization.object({}),
    })
    .transform<RapiddocsIr.WellKnownProtobufType>({
        transform: (value) => {
            switch (value.type) {
                case "any":
                    return RapiddocsIr.WellKnownProtobufType.any();
                case "api":
                    return RapiddocsIr.WellKnownProtobufType.api();
                case "boolValue":
                    return RapiddocsIr.WellKnownProtobufType.boolValue();
                case "bytesValue":
                    return RapiddocsIr.WellKnownProtobufType.bytesValue();
                case "doubleValue":
                    return RapiddocsIr.WellKnownProtobufType.doubleValue();
                case "duration":
                    return RapiddocsIr.WellKnownProtobufType.duration();
                case "empty":
                    return RapiddocsIr.WellKnownProtobufType.empty();
                case "enum":
                    return RapiddocsIr.WellKnownProtobufType.enum();
                case "enumValue":
                    return RapiddocsIr.WellKnownProtobufType.enumValue();
                case "field":
                    return RapiddocsIr.WellKnownProtobufType.field();
                case "fieldCardinality":
                    return RapiddocsIr.WellKnownProtobufType.fieldCardinality();
                case "fieldKind":
                    return RapiddocsIr.WellKnownProtobufType.fieldKind();
                case "fieldMask":
                    return RapiddocsIr.WellKnownProtobufType.fieldMask();
                case "floatValue":
                    return RapiddocsIr.WellKnownProtobufType.floatValue();
                case "int32Value":
                    return RapiddocsIr.WellKnownProtobufType.int32Value();
                case "int64Value":
                    return RapiddocsIr.WellKnownProtobufType.int64Value();
                case "listValue":
                    return RapiddocsIr.WellKnownProtobufType.listValue();
                case "method":
                    return RapiddocsIr.WellKnownProtobufType.method();
                case "mixin":
                    return RapiddocsIr.WellKnownProtobufType.mixin();
                case "nullValue":
                    return RapiddocsIr.WellKnownProtobufType.nullValue();
                case "option":
                    return RapiddocsIr.WellKnownProtobufType.option();
                case "sourceContext":
                    return RapiddocsIr.WellKnownProtobufType.sourceContext();
                case "stringValue":
                    return RapiddocsIr.WellKnownProtobufType.stringValue();
                case "struct":
                    return RapiddocsIr.WellKnownProtobufType.struct();
                case "syntax":
                    return RapiddocsIr.WellKnownProtobufType.syntax();
                case "timestamp":
                    return RapiddocsIr.WellKnownProtobufType.timestamp();
                case "type":
                    return RapiddocsIr.WellKnownProtobufType.type();
                case "uint32Value":
                    return RapiddocsIr.WellKnownProtobufType.uint32Value();
                case "uint64Value":
                    return RapiddocsIr.WellKnownProtobufType.uint64Value();
                case "value":
                    return RapiddocsIr.WellKnownProtobufType.value();
                default:
                    return value as RapiddocsIr.WellKnownProtobufType;
            }
        },
        untransform: ({ _visit, ...value }) => value as any,
    });

export declare namespace WellKnownProtobufType {
    export type Raw =
        | WellKnownProtobufType.Any
        | WellKnownProtobufType.Api
        | WellKnownProtobufType.BoolValue
        | WellKnownProtobufType.BytesValue
        | WellKnownProtobufType.DoubleValue
        | WellKnownProtobufType.Duration
        | WellKnownProtobufType.Empty
        | WellKnownProtobufType.Enum
        | WellKnownProtobufType.EnumValue
        | WellKnownProtobufType.Field
        | WellKnownProtobufType.FieldCardinality
        | WellKnownProtobufType.FieldKind
        | WellKnownProtobufType.FieldMask
        | WellKnownProtobufType.FloatValue
        | WellKnownProtobufType.Int32Value
        | WellKnownProtobufType.Int64Value
        | WellKnownProtobufType.ListValue
        | WellKnownProtobufType.Method
        | WellKnownProtobufType.Mixin
        | WellKnownProtobufType.NullValue
        | WellKnownProtobufType.Option
        | WellKnownProtobufType.SourceContext
        | WellKnownProtobufType.StringValue
        | WellKnownProtobufType.Struct
        | WellKnownProtobufType.Syntax
        | WellKnownProtobufType.Timestamp
        | WellKnownProtobufType.Type
        | WellKnownProtobufType.Uint32Value
        | WellKnownProtobufType.Uint64Value
        | WellKnownProtobufType.Value;

    export interface Any {
        type: "any";
    }

    export interface Api {
        type: "api";
    }

    export interface BoolValue {
        type: "boolValue";
    }

    export interface BytesValue {
        type: "bytesValue";
    }

    export interface DoubleValue {
        type: "doubleValue";
    }

    export interface Duration {
        type: "duration";
    }

    export interface Empty {
        type: "empty";
    }

    export interface Enum {
        type: "enum";
    }

    export interface EnumValue {
        type: "enumValue";
    }

    export interface Field {
        type: "field";
    }

    export interface FieldCardinality {
        type: "fieldCardinality";
    }

    export interface FieldKind {
        type: "fieldKind";
    }

    export interface FieldMask {
        type: "fieldMask";
    }

    export interface FloatValue {
        type: "floatValue";
    }

    export interface Int32Value {
        type: "int32Value";
    }

    export interface Int64Value {
        type: "int64Value";
    }

    export interface ListValue {
        type: "listValue";
    }

    export interface Method {
        type: "method";
    }

    export interface Mixin {
        type: "mixin";
    }

    export interface NullValue {
        type: "nullValue";
    }

    export interface Option {
        type: "option";
    }

    export interface SourceContext {
        type: "sourceContext";
    }

    export interface StringValue {
        type: "stringValue";
    }

    export interface Struct {
        type: "struct";
    }

    export interface Syntax {
        type: "syntax";
    }

    export interface Timestamp {
        type: "timestamp";
    }

    export interface Type {
        type: "type";
    }

    export interface Uint32Value {
        type: "uint32Value";
    }

    export interface Uint64Value {
        type: "uint64Value";
    }

    export interface Value {
        type: "value";
    }
}
