/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export interface StringValidationSchema {
    minLength?: number;
    maxLength?: number;
    pattern?: string;
    format?: string;
}
