/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../../../index";

export type ValidationSchema =
    | RapiddocsDefinition.rapiddocsDefinition.StringValidationSchema
    | RapiddocsDefinition.rapiddocsDefinition.NumberValidationSchema;
