/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../../../../../index";

export interface TestCaseImplementationDescription {
    boards: SeedTrace.v2.v3.TestCaseImplementationDescriptionBoard[];
}
