/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../../../index";

export interface FileUploadRequestBody {
    properties: RapiddocsIr.dynamic.FileUploadRequestBodyProperty[];
}
