/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../../../index";

export type FileUploadRequestBodyProperty =
    | RapiddocsIr.dynamic.FileUploadRequestBodyProperty.File_
    | RapiddocsIr.dynamic.FileUploadRequestBodyProperty.FileArray
    | RapiddocsIr.dynamic.FileUploadRequestBodyProperty.BodyProperty;

export namespace FileUploadRequestBodyProperty {
    export interface File_ extends RapiddocsIr.NameAndWireValue, _Utils {
        type: "file";
    }

    export interface FileArray extends RapiddocsIr.NameAndWireValue, _Utils {
        type: "fileArray";
    }

    export interface BodyProperty extends RapiddocsIr.dynamic.NamedParameter, _Utils {
        type: "bodyProperty";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.dynamic.FileUploadRequestBodyProperty._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        file: (value: RapiddocsIr.NameAndWireValue) => _Result;
        fileArray: (value: RapiddocsIr.NameAndWireValue) => _Result;
        bodyProperty: (value: RapiddocsIr.dynamic.NamedParameter) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const FileUploadRequestBodyProperty = {
    file: (value: RapiddocsIr.NameAndWireValue): RapiddocsIr.dynamic.FileUploadRequestBodyProperty.File_ => {
        return {
            ...value,
            type: "file",
            _visit: function <_Result>(
                this: RapiddocsIr.dynamic.FileUploadRequestBodyProperty.File_,
                visitor: RapiddocsIr.dynamic.FileUploadRequestBodyProperty._Visitor<_Result>,
            ) {
                return RapiddocsIr.dynamic.FileUploadRequestBodyProperty._visit(this, visitor);
            },
        };
    },

    fileArray: (value: RapiddocsIr.NameAndWireValue): RapiddocsIr.dynamic.FileUploadRequestBodyProperty.FileArray => {
        return {
            ...value,
            type: "fileArray",
            _visit: function <_Result>(
                this: RapiddocsIr.dynamic.FileUploadRequestBodyProperty.FileArray,
                visitor: RapiddocsIr.dynamic.FileUploadRequestBodyProperty._Visitor<_Result>,
            ) {
                return RapiddocsIr.dynamic.FileUploadRequestBodyProperty._visit(this, visitor);
            },
        };
    },

    bodyProperty: (value: RapiddocsIr.dynamic.NamedParameter): RapiddocsIr.dynamic.FileUploadRequestBodyProperty.BodyProperty => {
        return {
            ...value,
            type: "bodyProperty",
            _visit: function <_Result>(
                this: RapiddocsIr.dynamic.FileUploadRequestBodyProperty.BodyProperty,
                visitor: RapiddocsIr.dynamic.FileUploadRequestBodyProperty._Visitor<_Result>,
            ) {
                return RapiddocsIr.dynamic.FileUploadRequestBodyProperty._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsIr.dynamic.FileUploadRequestBodyProperty,
        visitor: RapiddocsIr.dynamic.FileUploadRequestBodyProperty._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "file":
                return visitor.file(value);
            case "fileArray":
                return visitor.fileArray(value);
            case "bodyProperty":
                return visitor.bodyProperty(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
