/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../../../index";

export type InlinedRequestBody =
    | RapiddocsIr.dynamic.InlinedRequestBody.Properties
    | RapiddocsIr.dynamic.InlinedRequestBody.Referenced
    | RapiddocsIr.dynamic.InlinedRequestBody.FileUpload;

export namespace InlinedRequestBody {
    export interface Properties extends _Utils {
        type: "properties";
        value: RapiddocsIr.dynamic.NamedParameter[];
    }

    export interface Referenced extends RapiddocsIr.dynamic.ReferencedRequestBody, _Utils {
        type: "referenced";
    }

    export interface FileUpload extends RapiddocsIr.dynamic.FileUploadRequestBody, _Utils {
        type: "fileUpload";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.dynamic.InlinedRequestBody._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        properties: (value: RapiddocsIr.dynamic.NamedParameter[]) => _Result;
        referenced: (value: RapiddocsIr.dynamic.ReferencedRequestBody) => _Result;
        fileUpload: (value: RapiddocsIr.dynamic.FileUploadRequestBody) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const InlinedRequestBody = {
    properties: (value: RapiddocsIr.dynamic.NamedParameter[]): RapiddocsIr.dynamic.InlinedRequestBody.Properties => {
        return {
            value: value,
            type: "properties",
            _visit: function <_Result>(
                this: RapiddocsIr.dynamic.InlinedRequestBody.Properties,
                visitor: RapiddocsIr.dynamic.InlinedRequestBody._Visitor<_Result>,
            ) {
                return RapiddocsIr.dynamic.InlinedRequestBody._visit(this, visitor);
            },
        };
    },

    referenced: (value: RapiddocsIr.dynamic.ReferencedRequestBody): RapiddocsIr.dynamic.InlinedRequestBody.Referenced => {
        return {
            ...value,
            type: "referenced",
            _visit: function <_Result>(
                this: RapiddocsIr.dynamic.InlinedRequestBody.Referenced,
                visitor: RapiddocsIr.dynamic.InlinedRequestBody._Visitor<_Result>,
            ) {
                return RapiddocsIr.dynamic.InlinedRequestBody._visit(this, visitor);
            },
        };
    },

    fileUpload: (value: RapiddocsIr.dynamic.FileUploadRequestBody): RapiddocsIr.dynamic.InlinedRequestBody.FileUpload => {
        return {
            ...value,
            type: "fileUpload",
            _visit: function <_Result>(
                this: RapiddocsIr.dynamic.InlinedRequestBody.FileUpload,
                visitor: RapiddocsIr.dynamic.InlinedRequestBody._Visitor<_Result>,
            ) {
                return RapiddocsIr.dynamic.InlinedRequestBody._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsIr.dynamic.InlinedRequestBody,
        visitor: RapiddocsIr.dynamic.InlinedRequestBody._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "properties":
                return visitor.properties(value.value);
            case "referenced":
                return visitor.referenced(value);
            case "fileUpload":
                return visitor.fileUpload(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
