/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface AuthVariable extends RapiddocsDefinition.WithEnvironmentVariable, RapiddocsDefinition.WithName {}
