/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface BasicAuthSchemeSchema extends RapiddocsDefinition.WithDocsSchema {
    scheme: "basic";
    username?: RapiddocsDefinition.AuthVariable;
    password?: RapiddocsDefinition.AuthVariable;
}
