/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface OAuthGetTokenEndpointSchema {
    /** The endpoint to get the access token, such as 'auth.get_token */
    endpoint: string;
    "request-properties"?: RapiddocsDefinition.OAuthAccessTokenRequestPropertiesSchema;
    "response-properties"?: RapiddocsDefinition.OAuthAccessTokenResponsePropertiesSchema;
}
