/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedNullable from "../../../index";

export interface User {
    name: string;
    tags?: string[];
    metadata?: SeedNullable.Metadata;
}
