/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface ApiConfigurationV2Schema
    extends RapiddocsDefinition.rapiddocsDefinition.WithHeadersSchema,
        RapiddocsDefinition.rapiddocsDefinition.WithEnvironmentsSchema {
    auth?: RapiddocsDefinition.rapiddocsDefinition.ApiAuthSchema;
    specs: RapiddocsDefinition.ApiConfigurationV2SpecsSchema;
}
