/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface AsyncApiSpecSchema {
    asyncapi: string;
    origin?: string;
    overrides?: string;
    namespace?: string;
    settings?: RapiddocsDefinition.AsyncApiSettingsSchema;
}
