/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface GeneratorsOpenApiObjectSchema {
    path: string;
    origin?: string;
    overrides?: string;
    "disable-examples"?: boolean;
    settings: RapiddocsDefinition.OpenApiSettingsSchema;
}
