/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export interface OpenApiFilterSchema {
    /** Endpoints to include in the generated SDK (e.g. "POST /users"). */
    endpoints?: string[];
}
