/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface ReadmeSchema {
    bannerLink?: string;
    introduction?: string;
    apiReferenceLink?: string;
    /** If set, use this endpoint's snippet as the default whenever possible */
    defaultEndpoint?: RapiddocsDefinition.ReadmeEndpointSchema;
    /** Specifies a list of endpoints associated with the feature */
    features?: Record<string, RapiddocsDefinition.ReadmeEndpointSchema[]>;
}
