/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface WebSocketChannelSchema extends RapiddocsDefinition.DeclarationSchema, RapiddocsDefinition.WithDisplayName {
    auth: boolean;
    url?: string;
    path: string;
    headers?: Record<string, RapiddocsDefinition.HttpHeaderSchema>;
    "path-parameters"?: Record<string, RapiddocsDefinition.HttpPathParameterSchema>;
    "query-parameters"?: Record<string, RapiddocsDefinition.HttpQueryParameterSchema>;
    messages?: Record<string, RapiddocsDefinition.WebSocketChannelMessageSchema>;
    examples?: RapiddocsDefinition.ExampleWebSocketSession[];
}
