/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */
import express from "express";
import { CompletionsService } from "./api/resources/completions/service/CompletionsService";
export declare function register(expressApp: express.Express | express.Router, services: {
    completions: CompletionsService;
}): void;
