/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { ValidationSchema } from "../../validation/types/ValidationSchema";
import { BaseTypeDeclarationSchema } from "./BaseTypeDeclarationSchema";

export const AliasSchema: core.serialization.ObjectSchema<serializers.AliasSchema.Raw, RapiddocsDefinition.AliasSchema> =
    core.serialization
        .object({
            type: core.serialization.string(),
            validation: ValidationSchema.optional(),
        })
        .extend(BaseTypeDeclarationSchema);

export declare namespace AliasSchema {
    export interface Raw extends BaseTypeDeclarationSchema.Raw {
        type: string;
        validation?: ValidationSchema.Raw | null;
    }
}
