/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { CasingOverridesSchema } from "./CasingOverridesSchema";
import { WithDocsSchema } from "../../commons/types/WithDocsSchema";
import { WithName } from "../../commons/types/WithName";

export const EnumValueSchema: core.serialization.ObjectSchema<
    serializers.EnumValueSchema.Raw,
    RapiddocsDefinition.EnumValueSchema
> = core.serialization
    .object({
        value: core.serialization.string(),
        casing: CasingOverridesSchema.optional(),
    })
    .extend(WithDocsSchema)
    .extend(WithName);

export declare namespace EnumValueSchema {
    export interface Raw extends WithDocsSchema.Raw, WithName.Raw {
        value: string;
        casing?: CasingOverridesSchema.Raw | null;
    }
}
