/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { EnumValueSchema } from "./EnumValueSchema";

export const EnumValue: core.serialization.Schema<serializers.EnumValue.Raw, RapiddocsDefinition.EnumValue> =
    core.serialization.undiscriminatedUnion([core.serialization.string(), EnumValueSchema]);

export declare namespace EnumValue {
    export type Raw = string | EnumValueSchema.Raw;
}
