/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";

export const ObjectPropertyAccess: core.serialization.Schema<
    serializers.ObjectPropertyAccess.Raw,
    RapiddocsDefinition.ObjectPropertyAccess
> = core.serialization.enum_(["read-only", "write-only"]);

export declare namespace ObjectPropertyAccess {
    export type Raw = "read-only" | "write-only";
}
