/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";

export const ObjectExtendsSchema: core.serialization.Schema<
    serializers.ObjectExtendsSchema.Raw,
    RapiddocsDefinition.ObjectExtendsSchema
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace ObjectExtendsSchema {
    export type Raw = string | string[];
}
