/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { BaseTypeReferenceSchema } from "./BaseTypeReferenceSchema";
import { WithName } from "../../commons/types/WithName";
import { WithAudiences } from "../../commons/types/WithAudiences";

export const TypeReferenceDetailedSchema: core.serialization.ObjectSchema<
    serializers.TypeReferenceDetailedSchema.Raw,
    RapiddocsDefinition.TypeReferenceDetailedSchema
> = core.serialization
    .object({
        type: core.serialization.string(),
    })
    .extend(BaseTypeReferenceSchema)
    .extend(WithName)
    .extend(WithAudiences);

export declare namespace TypeReferenceDetailedSchema {
    export interface Raw extends BaseTypeReferenceSchema.Raw, WithName.Raw, WithAudiences.Raw {
        type: string;
    }
}
