/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface DefinitionFileSchema extends RapiddocsDefinition.WithDocsSchema {
    imports?: Record<string, string>;
    types?: Record<string, RapiddocsDefinition.TypeDeclarationSchema>;
    service?: RapiddocsDefinition.HttpServiceSchema;
    errors?: Record<string, RapiddocsDefinition.ErrorDeclarationSchema>;
    webhooks?: Record<string, RapiddocsDefinition.WebhookSchema>;
    channel?: RapiddocsDefinition.WebSocketChannelSchema;
}
