/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface PackageMarkerFileSchema extends RapiddocsDefinition.DefinitionFileSchema {
    navigation?: RapiddocsDefinition.Navigation;
    export?: RapiddocsDefinition.Export;
}
