/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface RootApiFileSchema
    extends RapiddocsDefinition.WithDocsSchema,
        RapiddocsDefinition.WithDisplayName,
        RapiddocsDefinition.WithEnvironmentsSchema,
        RapiddocsDefinition.WithAuthSchema,
        RapiddocsDefinition.WithHeadersSchema {
    name: string;
    imports?: Record<string, string>;
    "error-discrimination"?: RapiddocsDefinition.ErrorDiscriminationSchema;
    audiences?: string[];
    errors?: string[];
    "base-path"?: string;
    "path-parameters"?: Record<string, RapiddocsDefinition.HttpPathParameterSchema>;
    "idempotency-headers"?: Record<string, RapiddocsDefinition.HttpHeaderSchema>;
    variables?: Record<string, RapiddocsDefinition.VariableDeclarationSchema>;
    pagination?: RapiddocsDefinition.PaginationSchema;
    version?: RapiddocsDefinition.VersionDeclarationSchema;
}
