/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsIr from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const InlinedRequestMetadata: core.serialization.ObjectSchema<
    serializers.dynamic.InlinedRequestMetadata.Raw,
    RapiddocsIr.dynamic.InlinedRequestMetadata
> = core.serialization.objectWithoutOptionalProperties({
    includePathParameters: core.serialization.boolean(),
    onlyPathParameters: core.serialization.boolean(),
});

export declare namespace InlinedRequestMetadata {
    export interface Raw {
        includePathParameters: boolean;
        onlyPathParameters: boolean;
    }
}
