/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsIr from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { Name } from "../../../../commons/types/Name";
import { ReferencedRequestBodyType } from "./ReferencedRequestBodyType";

export const ReferencedRequestBody: core.serialization.ObjectSchema<
    serializers.dynamic.ReferencedRequestBody.Raw,
    RapiddocsIr.dynamic.ReferencedRequestBody
> = core.serialization.objectWithoutOptionalProperties({
    bodyKey: Name,
    bodyType: ReferencedRequestBodyType,
});

export declare namespace ReferencedRequestBody {
    export interface Raw {
        bodyKey: Name.Raw;
        bodyType: ReferencedRequestBodyType.Raw;
    }
}
