/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsIr from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { BodyRequest } from "./BodyRequest";
import { InlinedRequest } from "./InlinedRequest";

export const Request: core.serialization.Schema<serializers.dynamic.Request.Raw, RapiddocsIr.dynamic.Request> =
    core.serialization
        .union("type", {
            body: BodyRequest,
            inlined: InlinedRequest,
        })
        .transform<RapiddocsIr.dynamic.Request>({
            transform: (value) => {
                switch (value.type) {
                    case "body":
                        return RapiddocsIr.dynamic.Request.body(value);
                    case "inlined":
                        return RapiddocsIr.dynamic.Request.inlined(value);
                    default:
                        return value as RapiddocsIr.dynamic.Request;
                }
            },
            untransform: ({ _visit, ...value }) => value as any,
        });

export declare namespace Request {
    export type Raw = Request.Body | Request.Inlined;

    export interface Body extends BodyRequest.Raw {
        type: "body";
    }

    export interface Inlined extends InlinedRequest.Raw {
        type: "inlined";
    }
}
