/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedAliasExtends from "../index";

/**
 * @example
 *     {
 *         parent: "Property from the parent"
 *     }
 */
export type AliasType = SeedAliasExtends.Parent;
