/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import express from "express";

export abstract class SeedPathParametersError extends Error {
    constructor(public readonly errorName?: string) {
        super();
        Object.setPrototypeOf(this, SeedPathParametersError.prototype);
    }

    public abstract send(res: express.Response): Promise<void>;
}
