/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface DoubleType {
    default: number | undefined;
    validation: RapiddocsIr.DoubleValidationRules | undefined;
}
