/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface EnumValue extends RapiddocsIr.Declaration {
    name: RapiddocsIr.NameAndWireValue;
}
