/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface ExampleMapContainer {
    map: RapiddocsIr.ExampleKeyValuePair[];
    keyType: RapiddocsIr.TypeReference;
    valueType: RapiddocsIr.TypeReference;
}
