/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface ExampleSetContainer {
    set: RapiddocsIr.ExampleTypeReference[];
    itemType: RapiddocsIr.TypeReference;
}
