/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface ExampleType extends RapiddocsIr.WithJsonExample, RapiddocsIr.WithDocs {
    name: RapiddocsIr.Name | undefined;
    shape: RapiddocsIr.ExampleTypeShape;
}
