/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export type Literal = RapiddocsIr.Literal.String | RapiddocsIr.Literal.Boolean;

export namespace Literal {
    export interface String extends _Utils {
        type: "string";
        string: string;
    }

    export interface Boolean extends _Utils {
        type: "boolean";
        boolean: boolean;
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.Literal._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        string: (value: string) => _Result;
        boolean: (value: boolean) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const Literal = {
    string: (value: string): RapiddocsIr.Literal.String => {
        return {
            string: value,
            type: "string",
            _visit: function <_Result>(this: RapiddocsIr.Literal.String, visitor: RapiddocsIr.Literal._Visitor<_Result>) {
                return RapiddocsIr.Literal._visit(this, visitor);
            },
        };
    },

    boolean: (value: boolean): RapiddocsIr.Literal.Boolean => {
        return {
            boolean: value,
            type: "boolean",
            _visit: function <_Result>(this: RapiddocsIr.Literal.Boolean, visitor: RapiddocsIr.Literal._Visitor<_Result>) {
                return RapiddocsIr.Literal._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(value: RapiddocsIr.Literal, visitor: RapiddocsIr.Literal._Visitor<_Result>): _Result => {
        switch (value.type) {
            case "string":
                return visitor.string(value.string);
            case "boolean":
                return visitor.boolean(value.boolean);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
