/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface ObjectTypeDeclaration {
    /** A list of other types to inherit from */
    extends: RapiddocsIr.DeclaredTypeName[];
    properties: RapiddocsIr.ObjectProperty[];
    /** A list of properties that all the parents of this object have. */
    extendedProperties: RapiddocsIr.ObjectProperty[] | undefined;
    /** Whether to allow extra properties on the object. */
    extraProperties: boolean;
}
