/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export type PrimitiveTypeV2 =
    | RapiddocsIr.PrimitiveTypeV2.Integer
    | RapiddocsIr.PrimitiveTypeV2.Long
    | RapiddocsIr.PrimitiveTypeV2.Uint
    | RapiddocsIr.PrimitiveTypeV2.Uint64
    | RapiddocsIr.PrimitiveTypeV2.Float
    | RapiddocsIr.PrimitiveTypeV2.Double
    | RapiddocsIr.PrimitiveTypeV2.Boolean
    | RapiddocsIr.PrimitiveTypeV2.String
    | RapiddocsIr.PrimitiveTypeV2.Date_
    | RapiddocsIr.PrimitiveTypeV2.DateTime
    | RapiddocsIr.PrimitiveTypeV2.Uuid
    | RapiddocsIr.PrimitiveTypeV2.Base64
    | RapiddocsIr.PrimitiveTypeV2.BigInteger;

export namespace PrimitiveTypeV2 {
    export interface Integer extends RapiddocsIr.IntegerType, _Utils {
        type: "integer";
    }

    export interface Long extends RapiddocsIr.LongType, _Utils {
        type: "long";
    }

    export interface Uint extends RapiddocsIr.UintType, _Utils {
        type: "uint";
    }

    export interface Uint64 extends RapiddocsIr.Uint64Type, _Utils {
        type: "uint64";
    }

    export interface Float extends RapiddocsIr.FloatType, _Utils {
        type: "float";
    }

    export interface Double extends RapiddocsIr.DoubleType, _Utils {
        type: "double";
    }

    export interface Boolean extends RapiddocsIr.BooleanType, _Utils {
        type: "boolean";
    }

    export interface String extends RapiddocsIr.StringType, _Utils {
        type: "string";
    }

    export interface Date_ extends RapiddocsIr.DateType, _Utils {
        type: "date";
    }

    export interface DateTime extends RapiddocsIr.DateTimeType, _Utils {
        type: "dateTime";
    }

    export interface Uuid extends RapiddocsIr.UuidType, _Utils {
        type: "uuid";
    }

    export interface Base64 extends RapiddocsIr.Base64Type, _Utils {
        type: "base64";
    }

    export interface BigInteger extends RapiddocsIr.BigIntegerType, _Utils {
        type: "bigInteger";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.PrimitiveTypeV2._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        integer: (value: RapiddocsIr.IntegerType) => _Result;
        long: (value: RapiddocsIr.LongType) => _Result;
        uint: (value: RapiddocsIr.UintType) => _Result;
        uint64: (value: RapiddocsIr.Uint64Type) => _Result;
        float: (value: RapiddocsIr.FloatType) => _Result;
        double: (value: RapiddocsIr.DoubleType) => _Result;
        boolean: (value: RapiddocsIr.BooleanType) => _Result;
        string: (value: RapiddocsIr.StringType) => _Result;
        date: (value: RapiddocsIr.DateType) => _Result;
        dateTime: (value: RapiddocsIr.DateTimeType) => _Result;
        uuid: (value: RapiddocsIr.UuidType) => _Result;
        base64: (value: RapiddocsIr.Base64Type) => _Result;
        bigInteger: (value: RapiddocsIr.BigIntegerType) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const PrimitiveTypeV2 = {
    integer: (value: RapiddocsIr.IntegerType): RapiddocsIr.PrimitiveTypeV2.Integer => {
        return {
            ...value,
            type: "integer",
            _visit: function <_Result>(
                this: RapiddocsIr.PrimitiveTypeV2.Integer,
                visitor: RapiddocsIr.PrimitiveTypeV2._Visitor<_Result>,
            ) {
                return RapiddocsIr.PrimitiveTypeV2._visit(this, visitor);
            },
        };
    },

    long: (value: RapiddocsIr.LongType): RapiddocsIr.PrimitiveTypeV2.Long => {
        return {
            ...value,
            type: "long",
            _visit: function <_Result>(
                this: RapiddocsIr.PrimitiveTypeV2.Long,
                visitor: RapiddocsIr.PrimitiveTypeV2._Visitor<_Result>,
            ) {
                return RapiddocsIr.PrimitiveTypeV2._visit(this, visitor);
            },
        };
    },

    uint: (value: RapiddocsIr.UintType): RapiddocsIr.PrimitiveTypeV2.Uint => {
        return {
            ...value,
            type: "uint",
            _visit: function <_Result>(
                this: RapiddocsIr.PrimitiveTypeV2.Uint,
                visitor: RapiddocsIr.PrimitiveTypeV2._Visitor<_Result>,
            ) {
                return RapiddocsIr.PrimitiveTypeV2._visit(this, visitor);
            },
        };
    },

    uint64: (value: RapiddocsIr.Uint64Type): RapiddocsIr.PrimitiveTypeV2.Uint64 => {
        return {
            ...value,
            type: "uint64",
            _visit: function <_Result>(
                this: RapiddocsIr.PrimitiveTypeV2.Uint64,
                visitor: RapiddocsIr.PrimitiveTypeV2._Visitor<_Result>,
            ) {
                return RapiddocsIr.PrimitiveTypeV2._visit(this, visitor);
            },
        };
    },

    float: (value: RapiddocsIr.FloatType): RapiddocsIr.PrimitiveTypeV2.Float => {
        return {
            ...value,
            type: "float",
            _visit: function <_Result>(
                this: RapiddocsIr.PrimitiveTypeV2.Float,
                visitor: RapiddocsIr.PrimitiveTypeV2._Visitor<_Result>,
            ) {
                return RapiddocsIr.PrimitiveTypeV2._visit(this, visitor);
            },
        };
    },

    double: (value: RapiddocsIr.DoubleType): RapiddocsIr.PrimitiveTypeV2.Double => {
        return {
            ...value,
            type: "double",
            _visit: function <_Result>(
                this: RapiddocsIr.PrimitiveTypeV2.Double,
                visitor: RapiddocsIr.PrimitiveTypeV2._Visitor<_Result>,
            ) {
                return RapiddocsIr.PrimitiveTypeV2._visit(this, visitor);
            },
        };
    },

    boolean: (value: RapiddocsIr.BooleanType): RapiddocsIr.PrimitiveTypeV2.Boolean => {
        return {
            ...value,
            type: "boolean",
            _visit: function <_Result>(
                this: RapiddocsIr.PrimitiveTypeV2.Boolean,
                visitor: RapiddocsIr.PrimitiveTypeV2._Visitor<_Result>,
            ) {
                return RapiddocsIr.PrimitiveTypeV2._visit(this, visitor);
            },
        };
    },

    string: (value: RapiddocsIr.StringType): RapiddocsIr.PrimitiveTypeV2.String => {
        return {
            ...value,
            type: "string",
            _visit: function <_Result>(
                this: RapiddocsIr.PrimitiveTypeV2.String,
                visitor: RapiddocsIr.PrimitiveTypeV2._Visitor<_Result>,
            ) {
                return RapiddocsIr.PrimitiveTypeV2._visit(this, visitor);
            },
        };
    },

    date: (value: RapiddocsIr.DateType): RapiddocsIr.PrimitiveTypeV2.Date_ => {
        return {
            ...value,
            type: "date",
            _visit: function <_Result>(
                this: RapiddocsIr.PrimitiveTypeV2.Date_,
                visitor: RapiddocsIr.PrimitiveTypeV2._Visitor<_Result>,
            ) {
                return RapiddocsIr.PrimitiveTypeV2._visit(this, visitor);
            },
        };
    },

    dateTime: (value: RapiddocsIr.DateTimeType): RapiddocsIr.PrimitiveTypeV2.DateTime => {
        return {
            ...value,
            type: "dateTime",
            _visit: function <_Result>(
                this: RapiddocsIr.PrimitiveTypeV2.DateTime,
                visitor: RapiddocsIr.PrimitiveTypeV2._Visitor<_Result>,
            ) {
                return RapiddocsIr.PrimitiveTypeV2._visit(this, visitor);
            },
        };
    },

    uuid: (value: RapiddocsIr.UuidType): RapiddocsIr.PrimitiveTypeV2.Uuid => {
        return {
            ...value,
            type: "uuid",
            _visit: function <_Result>(
                this: RapiddocsIr.PrimitiveTypeV2.Uuid,
                visitor: RapiddocsIr.PrimitiveTypeV2._Visitor<_Result>,
            ) {
                return RapiddocsIr.PrimitiveTypeV2._visit(this, visitor);
            },
        };
    },

    base64: (value: RapiddocsIr.Base64Type): RapiddocsIr.PrimitiveTypeV2.Base64 => {
        return {
            ...value,
            type: "base64",
            _visit: function <_Result>(
                this: RapiddocsIr.PrimitiveTypeV2.Base64,
                visitor: RapiddocsIr.PrimitiveTypeV2._Visitor<_Result>,
            ) {
                return RapiddocsIr.PrimitiveTypeV2._visit(this, visitor);
            },
        };
    },

    bigInteger: (value: RapiddocsIr.BigIntegerType): RapiddocsIr.PrimitiveTypeV2.BigInteger => {
        return {
            ...value,
            type: "bigInteger",
            _visit: function <_Result>(
                this: RapiddocsIr.PrimitiveTypeV2.BigInteger,
                visitor: RapiddocsIr.PrimitiveTypeV2._Visitor<_Result>,
            ) {
                return RapiddocsIr.PrimitiveTypeV2._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(value: RapiddocsIr.PrimitiveTypeV2, visitor: RapiddocsIr.PrimitiveTypeV2._Visitor<_Result>): _Result => {
        switch (value.type) {
            case "integer":
                return visitor.integer(value);
            case "long":
                return visitor.long(value);
            case "uint":
                return visitor.uint(value);
            case "uint64":
                return visitor.uint64(value);
            case "float":
                return visitor.float(value);
            case "double":
                return visitor.double(value);
            case "boolean":
                return visitor.boolean(value);
            case "string":
                return visitor.string(value);
            case "date":
                return visitor.date(value);
            case "dateTime":
                return visitor.dateTime(value);
            case "uuid":
                return visitor.uuid(value);
            case "base64":
                return visitor.base64(value);
            case "bigInteger":
                return visitor.bigInteger(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
