/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export type ResolvedTypeReference =
    | RapiddocsIr.ResolvedTypeReference.Container
    | RapiddocsIr.ResolvedTypeReference.Named
    | RapiddocsIr.ResolvedTypeReference.Primitive
    | RapiddocsIr.ResolvedTypeReference.Unknown;

export namespace ResolvedTypeReference {
    export interface Container extends _Utils {
        type: "container";
        container: RapiddocsIr.ContainerType;
    }

    export interface Named extends RapiddocsIr.ResolvedNamedType, _Utils {
        type: "named";
    }

    export interface Primitive extends _Utils {
        type: "primitive";
        primitive: RapiddocsIr.PrimitiveType;
    }

    export interface Unknown extends _Utils {
        type: "unknown";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.ResolvedTypeReference._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        container: (value: RapiddocsIr.ContainerType) => _Result;
        named: (value: RapiddocsIr.ResolvedNamedType) => _Result;
        primitive: (value: RapiddocsIr.PrimitiveType) => _Result;
        unknown: () => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const ResolvedTypeReference = {
    container: (value: RapiddocsIr.ContainerType): RapiddocsIr.ResolvedTypeReference.Container => {
        return {
            container: value,
            type: "container",
            _visit: function <_Result>(
                this: RapiddocsIr.ResolvedTypeReference.Container,
                visitor: RapiddocsIr.ResolvedTypeReference._Visitor<_Result>,
            ) {
                return RapiddocsIr.ResolvedTypeReference._visit(this, visitor);
            },
        };
    },

    named: (value: RapiddocsIr.ResolvedNamedType): RapiddocsIr.ResolvedTypeReference.Named => {
        return {
            ...value,
            type: "named",
            _visit: function <_Result>(
                this: RapiddocsIr.ResolvedTypeReference.Named,
                visitor: RapiddocsIr.ResolvedTypeReference._Visitor<_Result>,
            ) {
                return RapiddocsIr.ResolvedTypeReference._visit(this, visitor);
            },
        };
    },

    primitive: (value: RapiddocsIr.PrimitiveType): RapiddocsIr.ResolvedTypeReference.Primitive => {
        return {
            primitive: value,
            type: "primitive",
            _visit: function <_Result>(
                this: RapiddocsIr.ResolvedTypeReference.Primitive,
                visitor: RapiddocsIr.ResolvedTypeReference._Visitor<_Result>,
            ) {
                return RapiddocsIr.ResolvedTypeReference._visit(this, visitor);
            },
        };
    },

    unknown: (): RapiddocsIr.ResolvedTypeReference.Unknown => {
        return {
            type: "unknown",
            _visit: function <_Result>(
                this: RapiddocsIr.ResolvedTypeReference.Unknown,
                visitor: RapiddocsIr.ResolvedTypeReference._Visitor<_Result>,
            ) {
                return RapiddocsIr.ResolvedTypeReference._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsIr.ResolvedTypeReference,
        visitor: RapiddocsIr.ResolvedTypeReference._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "container":
                return visitor.container(value.container);
            case "named":
                return visitor.named(value);
            case "primitive":
                return visitor.primitive(value.primitive);
            case "unknown":
                return visitor.unknown();
            default:
                return visitor._other(value as any);
        }
    },
} as const;
