/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface SingleUnionType extends RapiddocsIr.WithDocs {
    discriminantValue: RapiddocsIr.NameAndWireValue;
    shape: RapiddocsIr.SingleUnionTypeProperties;
    displayName: string | undefined;
    availability: RapiddocsIr.Availability | undefined;
}
