/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

/**
 * The original source of the declared type (e.g. a `.proto` file).
 */
export type Source = RapiddocsIr.Source.Proto;

export namespace Source {
    export interface Proto extends _Utils {
        type: "proto";
        value: RapiddocsIr.ProtobufType;
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.Source._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        proto: (value: RapiddocsIr.ProtobufType) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const Source = {
    proto: (value: RapiddocsIr.ProtobufType): RapiddocsIr.Source.Proto => {
        return {
            value: value,
            type: "proto",
            _visit: function <_Result>(this: RapiddocsIr.Source.Proto, visitor: RapiddocsIr.Source._Visitor<_Result>) {
                return RapiddocsIr.Source._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(value: RapiddocsIr.Source, visitor: RapiddocsIr.Source._Visitor<_Result>): _Result => {
        switch (value.type) {
            case "proto":
                return visitor.proto(value.value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
