/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export interface StringValidationRules {
    format: string | undefined;
    pattern: string | undefined;
    minLength: number | undefined;
    maxLength: number | undefined;
}
