/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

/**
 * A type, which is a name and a shape
 */
export interface TypeDeclaration extends RapiddocsIr.Declaration {
    name: RapiddocsIr.DeclaredTypeName;
    shape: RapiddocsIr.Type;
    autogeneratedExamples: RapiddocsIr.ExampleType[];
    userProvidedExamples: RapiddocsIr.ExampleType[];
    /** All other named types that this type references (directly or indirectly) */
    referencedTypes: Set<RapiddocsIr.TypeId>;
    encoding: RapiddocsIr.Encoding | undefined;
    source: RapiddocsIr.Source | undefined;
    /** Whether to try and inline the type declaration */
    inline: boolean | undefined;
}
