/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface UnionTypeDeclaration {
    discriminant: RapiddocsIr.NameAndWireValue;
    /** A list of other types to inherit from */
    extends: RapiddocsIr.DeclaredTypeName[];
    types: RapiddocsIr.SingleUnionType[];
    baseProperties: RapiddocsIr.ObjectProperty[];
}
