/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsDefinition from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ProtobufTypeSchema } from "./ProtobufTypeSchema";

export const EncodingSchema: core.serialization.ObjectSchema<
    serializers.rapiddocsDefinition.EncodingSchema.Raw,
    RapiddocsDefinition.rapiddocsDefinition.EncodingSchema
> = core.serialization.object({
    proto: ProtobufTypeSchema.optional(),
});

export declare namespace EncodingSchema {
    export interface Raw {
        proto?: ProtobufTypeSchema.Raw | null;
    }
}
