/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export type PrimitiveValue = "STRING" | "NUMBER";
export const PrimitiveValue = {
    String: "STRING",
    Number: "NUMBER",
} as const;
