/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

/**
 * A Protobuf type declaration.
 */
export type ProtobufType = RapiddocsIr.ProtobufType.WellKnown | RapiddocsIr.ProtobufType.UserDefined;

export namespace ProtobufType {
    export interface WellKnown extends _Utils {
        type: "wellKnown";
        value: RapiddocsIr.WellKnownProtobufType;
    }

    export interface UserDefined extends RapiddocsIr.UserDefinedProtobufType, _Utils {
        type: "userDefined";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.ProtobufType._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        wellKnown: (value: RapiddocsIr.WellKnownProtobufType) => _Result;
        userDefined: (value: RapiddocsIr.UserDefinedProtobufType) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const ProtobufType = {
    wellKnown: (value: RapiddocsIr.WellKnownProtobufType): RapiddocsIr.ProtobufType.WellKnown => {
        return {
            value: value,
            type: "wellKnown",
            _visit: function <_Result>(
                this: RapiddocsIr.ProtobufType.WellKnown,
                visitor: RapiddocsIr.ProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.ProtobufType._visit(this, visitor);
            },
        };
    },

    userDefined: (value: RapiddocsIr.UserDefinedProtobufType): RapiddocsIr.ProtobufType.UserDefined => {
        return {
            ...value,
            type: "userDefined",
            _visit: function <_Result>(
                this: RapiddocsIr.ProtobufType.UserDefined,
                visitor: RapiddocsIr.ProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.ProtobufType._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(value: RapiddocsIr.ProtobufType, visitor: RapiddocsIr.ProtobufType._Visitor<_Result>): _Result => {
        switch (value.type) {
            case "wellKnown":
                return visitor.wellKnown(value.value);
            case "userDefined":
                return visitor.userDefined(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
