/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

/**
 * The set of well-known types supported by Protobuf. These types are often included
 * in the target runtime library, so they usually require special handling.
 *
 * The full list of well-known types can be found at https://protobuf.dev/reference/protobuf/google.protobuf
 */
export type WellKnownProtobufType =
    | RapiddocsIr.WellKnownProtobufType.Any
    | RapiddocsIr.WellKnownProtobufType.Api
    | RapiddocsIr.WellKnownProtobufType.BoolValue
    | RapiddocsIr.WellKnownProtobufType.BytesValue
    | RapiddocsIr.WellKnownProtobufType.DoubleValue
    | RapiddocsIr.WellKnownProtobufType.Duration
    | RapiddocsIr.WellKnownProtobufType.Empty
    | RapiddocsIr.WellKnownProtobufType.Enum
    | RapiddocsIr.WellKnownProtobufType.EnumValue
    | RapiddocsIr.WellKnownProtobufType.Field
    | RapiddocsIr.WellKnownProtobufType.FieldCardinality
    | RapiddocsIr.WellKnownProtobufType.FieldKind
    | RapiddocsIr.WellKnownProtobufType.FieldMask
    | RapiddocsIr.WellKnownProtobufType.FloatValue
    | RapiddocsIr.WellKnownProtobufType.Int32Value
    | RapiddocsIr.WellKnownProtobufType.Int64Value
    | RapiddocsIr.WellKnownProtobufType.ListValue
    | RapiddocsIr.WellKnownProtobufType.Method
    | RapiddocsIr.WellKnownProtobufType.Mixin
    | RapiddocsIr.WellKnownProtobufType.NullValue
    | RapiddocsIr.WellKnownProtobufType.Option
    | RapiddocsIr.WellKnownProtobufType.SourceContext
    | RapiddocsIr.WellKnownProtobufType.StringValue
    | RapiddocsIr.WellKnownProtobufType.Struct
    | RapiddocsIr.WellKnownProtobufType.Syntax
    | RapiddocsIr.WellKnownProtobufType.Timestamp
    | RapiddocsIr.WellKnownProtobufType.Type
    | RapiddocsIr.WellKnownProtobufType.Uint32Value
    | RapiddocsIr.WellKnownProtobufType.Uint64Value
    | RapiddocsIr.WellKnownProtobufType.Value;

export namespace WellKnownProtobufType {
    export interface Any extends _Utils {
        type: "any";
    }

    export interface Api extends _Utils {
        type: "api";
    }

    export interface BoolValue extends _Utils {
        type: "boolValue";
    }

    export interface BytesValue extends _Utils {
        type: "bytesValue";
    }

    export interface DoubleValue extends _Utils {
        type: "doubleValue";
    }

    export interface Duration extends _Utils {
        type: "duration";
    }

    export interface Empty extends _Utils {
        type: "empty";
    }

    export interface Enum extends _Utils {
        type: "enum";
    }

    export interface EnumValue extends _Utils {
        type: "enumValue";
    }

    export interface Field extends _Utils {
        type: "field";
    }

    export interface FieldCardinality extends _Utils {
        type: "fieldCardinality";
    }

    export interface FieldKind extends _Utils {
        type: "fieldKind";
    }

    export interface FieldMask extends _Utils {
        type: "fieldMask";
    }

    export interface FloatValue extends _Utils {
        type: "floatValue";
    }

    export interface Int32Value extends _Utils {
        type: "int32Value";
    }

    export interface Int64Value extends _Utils {
        type: "int64Value";
    }

    export interface ListValue extends _Utils {
        type: "listValue";
    }

    export interface Method extends _Utils {
        type: "method";
    }

    export interface Mixin extends _Utils {
        type: "mixin";
    }

    export interface NullValue extends _Utils {
        type: "nullValue";
    }

    export interface Option extends _Utils {
        type: "option";
    }

    export interface SourceContext extends _Utils {
        type: "sourceContext";
    }

    export interface StringValue extends _Utils {
        type: "stringValue";
    }

    export interface Struct extends _Utils {
        type: "struct";
    }

    export interface Syntax extends _Utils {
        type: "syntax";
    }

    export interface Timestamp extends _Utils {
        type: "timestamp";
    }

    export interface Type extends _Utils {
        type: "type";
    }

    export interface Uint32Value extends _Utils {
        type: "uint32Value";
    }

    export interface Uint64Value extends _Utils {
        type: "uint64Value";
    }

    export interface Value extends _Utils {
        type: "value";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        any: () => _Result;
        api: () => _Result;
        boolValue: () => _Result;
        bytesValue: () => _Result;
        doubleValue: () => _Result;
        duration: () => _Result;
        empty: () => _Result;
        enum: () => _Result;
        enumValue: () => _Result;
        field: () => _Result;
        fieldCardinality: () => _Result;
        fieldKind: () => _Result;
        fieldMask: () => _Result;
        floatValue: () => _Result;
        int32Value: () => _Result;
        int64Value: () => _Result;
        listValue: () => _Result;
        method: () => _Result;
        mixin: () => _Result;
        nullValue: () => _Result;
        option: () => _Result;
        sourceContext: () => _Result;
        stringValue: () => _Result;
        struct: () => _Result;
        syntax: () => _Result;
        timestamp: () => _Result;
        type: () => _Result;
        uint32Value: () => _Result;
        uint64Value: () => _Result;
        value: () => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const WellKnownProtobufType = {
    any: (): RapiddocsIr.WellKnownProtobufType.Any => {
        return {
            type: "any",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Any,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    api: (): RapiddocsIr.WellKnownProtobufType.Api => {
        return {
            type: "api",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Api,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    boolValue: (): RapiddocsIr.WellKnownProtobufType.BoolValue => {
        return {
            type: "boolValue",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.BoolValue,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    bytesValue: (): RapiddocsIr.WellKnownProtobufType.BytesValue => {
        return {
            type: "bytesValue",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.BytesValue,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    doubleValue: (): RapiddocsIr.WellKnownProtobufType.DoubleValue => {
        return {
            type: "doubleValue",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.DoubleValue,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    duration: (): RapiddocsIr.WellKnownProtobufType.Duration => {
        return {
            type: "duration",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Duration,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    empty: (): RapiddocsIr.WellKnownProtobufType.Empty => {
        return {
            type: "empty",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Empty,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    enum: (): RapiddocsIr.WellKnownProtobufType.Enum => {
        return {
            type: "enum",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Enum,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    enumValue: (): RapiddocsIr.WellKnownProtobufType.EnumValue => {
        return {
            type: "enumValue",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.EnumValue,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    field: (): RapiddocsIr.WellKnownProtobufType.Field => {
        return {
            type: "field",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Field,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    fieldCardinality: (): RapiddocsIr.WellKnownProtobufType.FieldCardinality => {
        return {
            type: "fieldCardinality",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.FieldCardinality,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    fieldKind: (): RapiddocsIr.WellKnownProtobufType.FieldKind => {
        return {
            type: "fieldKind",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.FieldKind,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    fieldMask: (): RapiddocsIr.WellKnownProtobufType.FieldMask => {
        return {
            type: "fieldMask",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.FieldMask,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    floatValue: (): RapiddocsIr.WellKnownProtobufType.FloatValue => {
        return {
            type: "floatValue",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.FloatValue,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    int32Value: (): RapiddocsIr.WellKnownProtobufType.Int32Value => {
        return {
            type: "int32Value",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Int32Value,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    int64Value: (): RapiddocsIr.WellKnownProtobufType.Int64Value => {
        return {
            type: "int64Value",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Int64Value,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    listValue: (): RapiddocsIr.WellKnownProtobufType.ListValue => {
        return {
            type: "listValue",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.ListValue,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    method: (): RapiddocsIr.WellKnownProtobufType.Method => {
        return {
            type: "method",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Method,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    mixin: (): RapiddocsIr.WellKnownProtobufType.Mixin => {
        return {
            type: "mixin",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Mixin,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    nullValue: (): RapiddocsIr.WellKnownProtobufType.NullValue => {
        return {
            type: "nullValue",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.NullValue,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    option: (): RapiddocsIr.WellKnownProtobufType.Option => {
        return {
            type: "option",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Option,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    sourceContext: (): RapiddocsIr.WellKnownProtobufType.SourceContext => {
        return {
            type: "sourceContext",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.SourceContext,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    stringValue: (): RapiddocsIr.WellKnownProtobufType.StringValue => {
        return {
            type: "stringValue",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.StringValue,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    struct: (): RapiddocsIr.WellKnownProtobufType.Struct => {
        return {
            type: "struct",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Struct,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    syntax: (): RapiddocsIr.WellKnownProtobufType.Syntax => {
        return {
            type: "syntax",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Syntax,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    timestamp: (): RapiddocsIr.WellKnownProtobufType.Timestamp => {
        return {
            type: "timestamp",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Timestamp,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    type: (): RapiddocsIr.WellKnownProtobufType.Type => {
        return {
            type: "type",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Type,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    uint32Value: (): RapiddocsIr.WellKnownProtobufType.Uint32Value => {
        return {
            type: "uint32Value",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Uint32Value,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    uint64Value: (): RapiddocsIr.WellKnownProtobufType.Uint64Value => {
        return {
            type: "uint64Value",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Uint64Value,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    value: (): RapiddocsIr.WellKnownProtobufType.Value => {
        return {
            type: "value",
            _visit: function <_Result>(
                this: RapiddocsIr.WellKnownProtobufType.Value,
                visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
            ) {
                return RapiddocsIr.WellKnownProtobufType._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsIr.WellKnownProtobufType,
        visitor: RapiddocsIr.WellKnownProtobufType._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "any":
                return visitor.any();
            case "api":
                return visitor.api();
            case "boolValue":
                return visitor.boolValue();
            case "bytesValue":
                return visitor.bytesValue();
            case "doubleValue":
                return visitor.doubleValue();
            case "duration":
                return visitor.duration();
            case "empty":
                return visitor.empty();
            case "enum":
                return visitor.enum();
            case "enumValue":
                return visitor.enumValue();
            case "field":
                return visitor.field();
            case "fieldCardinality":
                return visitor.fieldCardinality();
            case "fieldKind":
                return visitor.fieldKind();
            case "fieldMask":
                return visitor.fieldMask();
            case "floatValue":
                return visitor.floatValue();
            case "int32Value":
                return visitor.int32Value();
            case "int64Value":
                return visitor.int64Value();
            case "listValue":
                return visitor.listValue();
            case "method":
                return visitor.method();
            case "mixin":
                return visitor.mixin();
            case "nullValue":
                return visitor.nullValue();
            case "option":
                return visitor.option();
            case "sourceContext":
                return visitor.sourceContext();
            case "stringValue":
                return visitor.stringValue();
            case "struct":
                return visitor.struct();
            case "syntax":
                return visitor.syntax();
            case "timestamp":
                return visitor.timestamp();
            case "type":
                return visitor.type();
            case "uint32Value":
                return visitor.uint32Value();
            case "uint64Value":
                return visitor.uint64Value();
            case "value":
                return visitor.value();
            default:
                return visitor._other(value as any);
        }
    },
} as const;
