/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../../../index";

export interface BasicAuthSchemeSchema extends RapiddocsDefinition.rapiddocsDefinition.WithDocsSchema {
    scheme: "basic";
    username?: RapiddocsDefinition.rapiddocsDefinition.AuthVariable;
    password?: RapiddocsDefinition.rapiddocsDefinition.AuthVariable;
}
