/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../../../index";

export interface HeaderAuthSchemeSchema
    extends RapiddocsDefinition.rapiddocsDefinition.WithEnvironmentVariable,
        RapiddocsDefinition.rapiddocsDefinition.WithName,
        RapiddocsDefinition.rapiddocsDefinition.WithDocsSchema {
    header: string;
    /** Defaults to string */
    type?: string;
    prefix?: string;
}
