/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export interface OAuthAccessTokenRequestPropertiesSchema {
    /** The property name for the client ID. */
    "client-id"?: string;
    /** The property name for the client secret. */
    "client-secret"?: string;
    /** The property name for the scopes. */
    scopes?: string;
}
