// This file was auto-generated by Rapiddocs from our API Definition.

package client

import (
	basicauth "github.com/basic-auth/rapiddocs/basicauth"
	core "github.com/basic-auth/rapiddocs/core"
	internal "github.com/basic-auth/rapiddocs/internal"
	option "github.com/basic-auth/rapiddocs/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	BasicAuth *basicauth.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:    options.ToHeader(),
		BasicAuth: basicauth.NewClient(opts...),
	}
}
