/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsIr from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const EnvironmentVariable: core.serialization.Schema<
    serializers.generatorExec.EnvironmentVariable.Raw,
    RapiddocsIr.generatorExec.EnvironmentVariable
> = core.serialization.string();

export declare namespace EnvironmentVariable {
    export type Raw = string;
}
