/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsIr from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { PublishingMetadata } from "./PublishingMetadata";
import { OutputMode } from "./OutputMode";

export const GeneratorOutputConfig: core.serialization.ObjectSchema<
    serializers.generatorExec.GeneratorOutputConfig.Raw,
    RapiddocsIr.generatorExec.GeneratorOutputConfig
> = core.serialization.objectWithoutOptionalProperties({
    path: core.serialization.string(),
    snippetFilepath: core.serialization.string().optional(),
    snippetTemplateFilepath: core.serialization.string().optional(),
    publishingMetadata: PublishingMetadata.optional(),
    mode: OutputMode,
});

export declare namespace GeneratorOutputConfig {
    export interface Raw {
        path: string;
        snippetFilepath?: string | null;
        snippetTemplateFilepath?: string | null;
        publishingMetadata?: PublishingMetadata.Raw | null;
        mode: OutputMode.Raw;
    }
}
