/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsIr from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { MavenRegistryConfig } from "./MavenRegistryConfig";
import { NpmRegistryConfig } from "./NpmRegistryConfig";

export const GeneratorRegistriesConfig: core.serialization.ObjectSchema<
    serializers.generatorExec.GeneratorRegistriesConfig.Raw,
    RapiddocsIr.generatorExec.GeneratorRegistriesConfig
> = core.serialization.objectWithoutOptionalProperties({
    maven: MavenRegistryConfig,
    npm: NpmRegistryConfig,
});

export declare namespace GeneratorRegistriesConfig {
    export interface Raw {
        maven: MavenRegistryConfig.Raw;
        npm: NpmRegistryConfig.Raw;
    }
}
