/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsIr from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { EnvironmentVariable } from "./EnvironmentVariable";

export const NpmGithubPublishInfo: core.serialization.ObjectSchema<
    serializers.generatorExec.NpmGithubPublishInfo.Raw,
    RapiddocsIr.generatorExec.NpmGithubPublishInfo
> = core.serialization.objectWithoutOptionalProperties({
    registryUrl: core.serialization.string(),
    packageName: core.serialization.string(),
    tokenEnvironmentVariable: EnvironmentVariable,
    shouldGeneratePublishWorkflow: core.serialization.boolean().optional(),
});

export declare namespace NpmGithubPublishInfo {
    export interface Raw {
        registryUrl: string;
        packageName: string;
        tokenEnvironmentVariable: EnvironmentVariable.Raw;
        shouldGeneratePublishWorkflow?: boolean | null;
    }
}
