/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsIr from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { OutputMetadataAuthor } from "./OutputMetadataAuthor";

export const OutputMetadata: core.serialization.ObjectSchema<
    serializers.generatorExec.OutputMetadata.Raw,
    RapiddocsIr.generatorExec.OutputMetadata
> = core.serialization.objectWithoutOptionalProperties({
    description: core.serialization.string().optional(),
    authors: core.serialization.list(OutputMetadataAuthor).optional(),
});

export declare namespace OutputMetadata {
    export interface Raw {
        description?: string | null;
        authors?: OutputMetadataAuthor.Raw[] | null;
    }
}
