/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsIr from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const PostmanConfig: core.serialization.ObjectSchema<
    serializers.generatorExec.PostmanConfig.Raw,
    RapiddocsIr.generatorExec.PostmanConfig
> = core.serialization.objectWithoutOptionalProperties({
    apiKey: core.serialization.string(),
    workspaceId: core.serialization.string(),
});

export declare namespace PostmanConfig {
    export interface Raw {
        apiKey: string;
        workspaceId: string;
    }
}
