/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export type Environments = RapiddocsIr.Environments.SingleBaseUrl | RapiddocsIr.Environments.MultipleBaseUrls;

export namespace Environments {
    export interface SingleBaseUrl extends RapiddocsIr.SingleBaseUrlEnvironments, _Utils {
        type: "singleBaseUrl";
    }

    export interface MultipleBaseUrls extends RapiddocsIr.MultipleBaseUrlsEnvironments, _Utils {
        type: "multipleBaseUrls";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.Environments._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        singleBaseUrl: (value: RapiddocsIr.SingleBaseUrlEnvironments) => _Result;
        multipleBaseUrls: (value: RapiddocsIr.MultipleBaseUrlsEnvironments) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const Environments = {
    singleBaseUrl: (value: RapiddocsIr.SingleBaseUrlEnvironments): RapiddocsIr.Environments.SingleBaseUrl => {
        return {
            ...value,
            type: "singleBaseUrl",
            _visit: function <_Result>(
                this: RapiddocsIr.Environments.SingleBaseUrl,
                visitor: RapiddocsIr.Environments._Visitor<_Result>,
            ) {
                return RapiddocsIr.Environments._visit(this, visitor);
            },
        };
    },

    multipleBaseUrls: (value: RapiddocsIr.MultipleBaseUrlsEnvironments): RapiddocsIr.Environments.MultipleBaseUrls => {
        return {
            ...value,
            type: "multipleBaseUrls",
            _visit: function <_Result>(
                this: RapiddocsIr.Environments.MultipleBaseUrls,
                visitor: RapiddocsIr.Environments._Visitor<_Result>,
            ) {
                return RapiddocsIr.Environments._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(value: RapiddocsIr.Environments, visitor: RapiddocsIr.Environments._Visitor<_Result>): _Result => {
        switch (value.type) {
            case "singleBaseUrl":
                return visitor.singleBaseUrl(value);
            case "multipleBaseUrls":
                return visitor.multipleBaseUrls(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
