openapi: 3.0.3
info:
  title: Test API
  version: 1.0.0
servers:
  - url: https://localhost
tags:
  - name: dataservice
paths:
  /foo:
    post:
      tag: dataservice
      x-rapiddocs-sdk-group-name:
        - dataservice
      x-rapiddocs-sdk-method-name: foo
      operationId: foo
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object

components:
  securitySchemes: {}
