/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsOpenapiIr from "../../../index";

export interface KeyValuePair {
    key: RapiddocsOpenapiIr.PrimitiveExample;
    value: RapiddocsOpenapiIr.FullExample;
}
