/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsDefinition from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { OAuthAccessTokenRequestPropertiesSchema } from "./OAuthAccessTokenRequestPropertiesSchema";
import { OAuthAccessTokenResponsePropertiesSchema } from "./OAuthAccessTokenResponsePropertiesSchema";

export const OAuthGetTokenEndpointSchema: core.serialization.ObjectSchema<
    serializers.rapiddocsDefinition.OAuthGetTokenEndpointSchema.Raw,
    RapiddocsDefinition.rapiddocsDefinition.OAuthGetTokenEndpointSchema
> = core.serialization.object({
    endpoint: core.serialization.string(),
    "request-properties": OAuthAccessTokenRequestPropertiesSchema.optional(),
    "response-properties": OAuthAccessTokenResponsePropertiesSchema.optional(),
});

export declare namespace OAuthGetTokenEndpointSchema {
    export interface Raw {
        endpoint: string;
        "request-properties"?: OAuthAccessTokenRequestPropertiesSchema.Raw | null;
        "response-properties"?: OAuthAccessTokenResponsePropertiesSchema.Raw | null;
    }
}
