// This file was auto-generated by Rapiddocs from our API Definition.

package client

import (
	core "github.com/nullable/rapiddocs/core"
	internal "github.com/nullable/rapiddocs/internal"
	nullable "github.com/nullable/rapiddocs/nullable"
	option "github.com/nullable/rapiddocs/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Nullable *nullable.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:   options.ToHeader(),
		Nullable: nullable.NewClient(opts...),
	}
}
