# This file was auto-generated by Rapiddocs from our API Definition.

from ....core.exceptions.rapiddocs_http_exception import RapiddocsHTTPException
from ..types.playlist_id_not_found_error_body import PlaylistIdNotFoundErrorBody


class PlaylistIdNotFoundError(RapiddocsHTTPException):
    def __init__(self, error: PlaylistIdNotFoundErrorBody):
        super().__init__(status_code=404, name="PlaylistIdNotFoundError", content=error)
