/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";

export const OAuthAccessTokenRequestPropertiesSchema: core.serialization.ObjectSchema<
    serializers.OAuthAccessTokenRequestPropertiesSchema.Raw,
    RapiddocsDefinition.OAuthAccessTokenRequestPropertiesSchema
> = core.serialization.object({
    "client-id": core.serialization.string().optional(),
    "client-secret": core.serialization.string().optional(),
    scopes: core.serialization.string().optional(),
});

export declare namespace OAuthAccessTokenRequestPropertiesSchema {
    export interface Raw {
        "client-id"?: string | null;
        "client-secret"?: string | null;
        scopes?: string | null;
    }
}
