/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { ExampleEndpointCall } from "./ExampleEndpointCall";

export const AutogeneratedEndpointExample: core.serialization.ObjectSchema<
    serializers.AutogeneratedEndpointExample.Raw,
    RapiddocsIr.AutogeneratedEndpointExample
> = core.serialization.objectWithoutOptionalProperties({
    example: ExampleEndpointCall,
});

export declare namespace AutogeneratedEndpointExample {
    export interface Raw {
        example: ExampleEndpointCall.Raw;
    }
}
