/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { WithDocs } from "../../commons/types/WithDocs";

export const BytesRequest: core.serialization.ObjectSchema<serializers.BytesRequest.Raw, RapiddocsIr.BytesRequest> =
    core.serialization
        .objectWithoutOptionalProperties({
            isOptional: core.serialization.boolean(),
            contentType: core.serialization.string().optional(),
        })
        .extend(WithDocs);

export declare namespace BytesRequest {
    export interface Raw extends WithDocs.Raw {
        isOptional: boolean;
        contentType?: string | null;
    }
}
