/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { Name } from "../../commons/types/Name";

export const EndpointName: core.serialization.ObjectSchema<serializers.EndpointName.Raw, RapiddocsIr.EndpointName> = Name;

export declare namespace EndpointName {
    export type Raw = Name.Raw;
}
