/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { FileUploadBodyPropertyEncoding } from "./FileUploadBodyPropertyEncoding";
import { InlinedRequestBodyProperty } from "./InlinedRequestBodyProperty";

export const FileUploadBodyProperty: core.serialization.ObjectSchema<
    serializers.FileUploadBodyProperty.Raw,
    RapiddocsIr.FileUploadBodyProperty
> = core.serialization
    .objectWithoutOptionalProperties({
        contentType: core.serialization.string().optional(),
        style: FileUploadBodyPropertyEncoding.optional(),
    })
    .extend(InlinedRequestBodyProperty);

export declare namespace FileUploadBodyProperty {
    export interface Raw extends InlinedRequestBodyProperty.Raw {
        contentType?: string | null;
        style?: FileUploadBodyPropertyEncoding.Raw | null;
    }
}
