/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { NameAndWireValue } from "../../commons/types/NameAndWireValue";
import { WithDocs } from "../../commons/types/WithDocs";

export const FilePropertySingle: core.serialization.ObjectSchema<
    serializers.FilePropertySingle.Raw,
    RapiddocsIr.FilePropertySingle
> = core.serialization
    .objectWithoutOptionalProperties({
        key: NameAndWireValue,
        isOptional: core.serialization.boolean(),
        contentType: core.serialization.string().optional(),
    })
    .extend(WithDocs);

export declare namespace FilePropertySingle {
    export interface Raw extends WithDocs.Raw {
        key: NameAndWireValue.Raw;
        isOptional: boolean;
        contentType?: string | null;
    }
}
