/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { ProtobufService } from "../../proto/types/ProtobufService";

export const GrpcTransport: core.serialization.ObjectSchema<serializers.GrpcTransport.Raw, RapiddocsIr.GrpcTransport> =
    core.serialization.objectWithoutOptionalProperties({
        service: ProtobufService,
    });

export declare namespace GrpcTransport {
    export interface Raw {
        service: ProtobufService.Raw;
    }
}
