/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { HttpPathPart } from "./HttpPathPart";

export const HttpPath: core.serialization.ObjectSchema<serializers.HttpPath.Raw, RapiddocsIr.HttpPath> =
    core.serialization.objectWithoutOptionalProperties({
        head: core.serialization.string(),
        parts: core.serialization.list(HttpPathPart),
    });

export declare namespace HttpPath {
    export interface Raw {
        head: string;
        parts: HttpPathPart.Raw[];
    }
}
