/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { NameAndWireValue } from "../../commons/types/NameAndWireValue";
import { Declaration } from "../../commons/types/Declaration";

export const HttpHeader: core.serialization.ObjectSchema<serializers.HttpHeader.Raw, RapiddocsIr.HttpHeader> =
    core.serialization
        .objectWithoutOptionalProperties({
            name: NameAndWireValue,
            valueType: core.serialization.lazy(() => serializers.TypeReference),
            env: core.serialization.string().optional(),
        })
        .extend(Declaration);

export declare namespace HttpHeader {
    export interface Raw extends Declaration.Raw {
        name: NameAndWireValue.Raw;
        valueType: serializers.TypeReference.Raw;
        env?: string | null;
    }
}
