/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { JsonResponseBody } from "./JsonResponseBody";
import { JsonResponseBodyWithProperty } from "./JsonResponseBodyWithProperty";

export const JsonResponse: core.serialization.Schema<serializers.JsonResponse.Raw, RapiddocsIr.JsonResponse> =
    core.serialization
        .union("type", {
            response: JsonResponseBody,
            nestedPropertyAsResponse: JsonResponseBodyWithProperty,
        })
        .transform<RapiddocsIr.JsonResponse>({
            transform: (value) => {
                switch (value.type) {
                    case "response":
                        return RapiddocsIr.JsonResponse.response(value);
                    case "nestedPropertyAsResponse":
                        return RapiddocsIr.JsonResponse.nestedPropertyAsResponse(value);
                    default:
                        return value as RapiddocsIr.JsonResponse;
                }
            },
            untransform: ({ _visit, ...value }) => value as any,
        });

export declare namespace JsonResponse {
    export type Raw = JsonResponse.Response | JsonResponse.NestedPropertyAsResponse;

    export interface Response extends JsonResponseBody.Raw {
        type: "response";
    }

    export interface NestedPropertyAsResponse extends JsonResponseBodyWithProperty.Raw {
        type: "nestedPropertyAsResponse";
    }
}
