/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { ObjectProperty } from "../../types/types/ObjectProperty";
import { WithDocs } from "../../commons/types/WithDocs";

export const JsonResponseBodyWithProperty: core.serialization.ObjectSchema<
    serializers.JsonResponseBodyWithProperty.Raw,
    RapiddocsIr.JsonResponseBodyWithProperty
> = core.serialization
    .objectWithoutOptionalProperties({
        responseBodyType: core.serialization.lazy(() => serializers.TypeReference),
        responseProperty: ObjectProperty.optional(),
    })
    .extend(WithDocs);

export declare namespace JsonResponseBodyWithProperty {
    export interface Raw extends WithDocs.Raw {
        responseBodyType: serializers.TypeReference.Raw;
        responseProperty?: ObjectProperty.Raw | null;
    }
}
