/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { Name } from "../../commons/types/Name";
import { RequestPropertyValue } from "./RequestPropertyValue";

export const RequestProperty: core.serialization.ObjectSchema<serializers.RequestProperty.Raw, RapiddocsIr.RequestProperty> =
    core.serialization.objectWithoutOptionalProperties({
        propertyPath: core.serialization.list(Name).optional(),
        property: RequestPropertyValue,
    });

export declare namespace RequestProperty {
    export interface Raw {
        propertyPath?: Name.Raw[] | null;
        property: RequestPropertyValue.Raw;
    }
}
