/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { ResponseError } from "./ResponseError";

export const ResponseErrors: core.serialization.Schema<serializers.ResponseErrors.Raw, RapiddocsIr.ResponseErrors> =
    core.serialization.list(ResponseError);

export declare namespace ResponseErrors {
    export type Raw = ResponseError.Raw[];
}
