/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { SdkRequestBodyType } from "./SdkRequestBodyType";
import { SdkRequestWrapper } from "./SdkRequestWrapper";

export const SdkRequestShape: core.serialization.Schema<serializers.SdkRequestShape.Raw, RapiddocsIr.SdkRequestShape> =
    core.serialization
        .union("type", {
            justRequestBody: core.serialization.object({
                value: SdkRequestBodyType,
            }),
            wrapper: SdkRequestWrapper,
        })
        .transform<RapiddocsIr.SdkRequestShape>({
            transform: (value) => {
                switch (value.type) {
                    case "justRequestBody":
                        return RapiddocsIr.SdkRequestShape.justRequestBody(value.value);
                    case "wrapper":
                        return RapiddocsIr.SdkRequestShape.wrapper(value);
                    default:
                        return value as RapiddocsIr.SdkRequestShape;
                }
            },
            untransform: ({ _visit, ...value }) => value as any,
        });

export declare namespace SdkRequestShape {
    export type Raw = SdkRequestShape.JustRequestBody | SdkRequestShape.Wrapper;

    export interface JustRequestBody {
        type: "justRequestBody";
        value: SdkRequestBodyType.Raw;
    }

    export interface Wrapper extends SdkRequestWrapper.Raw {
        type: "wrapper";
    }
}
