/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const SupportedSdkLanguage: core.serialization.Schema<
    serializers.SupportedSdkLanguage.Raw,
    RapiddocsIr.SupportedSdkLanguage
> = core.serialization.enum_(["curl", "python", "javascript", "typescript", "go", "ruby", "csharp", "java"]);

export declare namespace SupportedSdkLanguage {
    export type Raw = "curl" | "python" | "javascript" | "typescript" | "go" | "ruby" | "csharp" | "java";
}
