/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../index";

export interface BuildingExecutorResponse {
    submissionId: SeedTrace.SubmissionId;
    status: SeedTrace.ExecutionSessionStatus;
}
