/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../index";

export interface WorkspaceRanResponse {
    submissionId: SeedTrace.SubmissionId;
    runDetails: SeedTrace.WorkspaceRunDetails;
}
