/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export class SeedStreamingTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, SeedStreamingTimeoutError.prototype);
    }
}
