// This file was auto-generated by Rapiddocs from our API Definition.

package api

import (
	core "github.com/imdb/rapiddocs/core"
	internal "github.com/imdb/rapiddocs/internal"
	option "github.com/imdb/rapiddocs/option"
	http "net/http"
)

type Acme struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Imdb *ImdbClient
}

func New(opts ...option.RequestOption) *Acme {
	options := core.NewRequestOptions(opts...)
	return &Acme{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
		Imdb:   NewImdbClient(opts...),
	}
}
