/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { NameAndWireValue } from "../../commons/types/NameAndWireValue";
import { WithDocsAndAvailability } from "../../commons/types/WithDocsAndAvailability";

export const InlinedWebSocketMessageBodyProperty: core.serialization.ObjectSchema<
    serializers.InlinedWebSocketMessageBodyProperty.Raw,
    RapiddocsIr.InlinedWebSocketMessageBodyProperty
> = core.serialization
    .objectWithoutOptionalProperties({
        name: NameAndWireValue,
        valueType: core.serialization.lazy(() => serializers.TypeReference),
    })
    .extend(WithDocsAndAvailability);

export declare namespace InlinedWebSocketMessageBodyProperty {
    export interface Raw extends WithDocsAndAvailability.Raw {
        name: NameAndWireValue.Raw;
        valueType: serializers.TypeReference.Raw;
    }
}
