/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { Name } from "../../commons/types/Name";

export const WebSocketName: core.serialization.ObjectSchema<serializers.WebSocketName.Raw, RapiddocsIr.WebSocketName> = Name;

export declare namespace WebSocketName {
    export type Raw = Name.Raw;
}
