/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../../index";

export interface StoreTracedTestCaseRequest {
    result: SeedTrace.TestCaseResultWithStdout;
    traceResponses: SeedTrace.TraceResponse[];
}
