/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { HeaderApiVersionScheme } from "./HeaderApiVersionScheme";

export const ApiVersionScheme: core.serialization.Schema<serializers.ApiVersionScheme.Raw, RapiddocsIr.ApiVersionScheme> =
    core.serialization
        .union("type", {
            header: HeaderApiVersionScheme,
        })
        .transform<RapiddocsIr.ApiVersionScheme>({
            transform: (value) => {
                switch (value.type) {
                    case "header":
                        return RapiddocsIr.ApiVersionScheme.header(value);
                    default:
                        return value as RapiddocsIr.ApiVersionScheme;
                }
            },
            untransform: ({ _visit, ...value }) => value as any,
        });

export declare namespace ApiVersionScheme {
    export type Raw = ApiVersionScheme.Header;

    export interface Header extends HeaderApiVersionScheme.Raw {
        type: "header";
    }
}
