/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { ApiDefinitionSourceId } from "./ApiDefinitionSourceId";

export const ProtoSource: core.serialization.ObjectSchema<serializers.ProtoSource.Raw, RapiddocsIr.ProtoSource> =
    core.serialization.objectWithoutOptionalProperties({
        id: ApiDefinitionSourceId,
        protoRootUrl: core.serialization.string(),
    });

export declare namespace ProtoSource {
    export interface Raw {
        id: ApiDefinitionSourceId.Raw;
        protoRootUrl: string;
    }
}
