/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { ApiDefinitionSource } from "./ApiDefinitionSource";

export const SourceConfig: core.serialization.ObjectSchema<serializers.SourceConfig.Raw, RapiddocsIr.SourceConfig> =
    core.serialization.objectWithoutOptionalProperties({
        sources: core.serialization.list(ApiDefinitionSource),
    });

export declare namespace SourceConfig {
    export interface Raw {
        sources: ApiDefinitionSource.Raw[];
    }
}
