/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const EnvironmentBaseUrlId: core.serialization.Schema<
    serializers.EnvironmentBaseUrlId.Raw,
    RapiddocsIr.EnvironmentBaseUrlId
> = core.serialization.string();

export declare namespace EnvironmentBaseUrlId {
    export type Raw = string;
}
