/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const EnvironmentUrl: core.serialization.Schema<serializers.EnvironmentUrl.Raw, RapiddocsIr.EnvironmentUrl> =
    core.serialization.string();

export declare namespace EnvironmentUrl {
    export type Raw = string;
}
