/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsConjure from "../../../index";

export type ConjureAuthDefinition = RapiddocsConjure.ConjureAuthDefinitionType | string;
