/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsConjure from "../../../index";

export interface ConjureArgumentWithParamType extends RapiddocsConjure.WithDocs {
    paramType: RapiddocsConjure.ConjureParamType;
    type: string;
}
