/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export class SeedSingleUrlEnvironmentNoDefaultTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, SeedSingleUrlEnvironmentNoDefaultTimeoutError.prototype);
    }
}
