/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

package resources.dummy;

import org.springframework.web.bind.annotation.RequestMapping;

@RequestMapping(
    path = "/"
)
public interface DummyService {
}
