/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../../../index";

export type GeneratorEnvironment =
    | RapiddocsIr.generatorExec.GeneratorEnvironment.Local
    | RapiddocsIr.generatorExec.GeneratorEnvironment.Remote;

export namespace GeneratorEnvironment {
    export interface Local extends _Utils {
        type: "local";
    }

    export interface Remote extends RapiddocsIr.generatorExec.RemoteGeneratorEnvironment, _Utils {
        type: "remote";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.generatorExec.GeneratorEnvironment._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        local: () => _Result;
        remote: (value: RapiddocsIr.generatorExec.RemoteGeneratorEnvironment) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const GeneratorEnvironment = {
    local: (): RapiddocsIr.generatorExec.GeneratorEnvironment.Local => {
        return {
            type: "local",
            _visit: function <_Result>(
                this: RapiddocsIr.generatorExec.GeneratorEnvironment.Local,
                visitor: RapiddocsIr.generatorExec.GeneratorEnvironment._Visitor<_Result>,
            ) {
                return RapiddocsIr.generatorExec.GeneratorEnvironment._visit(this, visitor);
            },
        };
    },

    remote: (
        value: RapiddocsIr.generatorExec.RemoteGeneratorEnvironment,
    ): RapiddocsIr.generatorExec.GeneratorEnvironment.Remote => {
        return {
            ...value,
            type: "remote",
            _visit: function <_Result>(
                this: RapiddocsIr.generatorExec.GeneratorEnvironment.Remote,
                visitor: RapiddocsIr.generatorExec.GeneratorEnvironment._Visitor<_Result>,
            ) {
                return RapiddocsIr.generatorExec.GeneratorEnvironment._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsIr.generatorExec.GeneratorEnvironment,
        visitor: RapiddocsIr.generatorExec.GeneratorEnvironment._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "local":
                return visitor.local();
            case "remote":
                return visitor.remote(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
