/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../../../index";

export type LicenseConfig = RapiddocsIr.generatorExec.LicenseConfig.Basic | RapiddocsIr.generatorExec.LicenseConfig.Custom;

export namespace LicenseConfig {
    export interface Basic extends RapiddocsIr.generatorExec.BasicLicense, _Utils {
        type: "basic";
    }

    export interface Custom extends RapiddocsIr.generatorExec.CustomLicense, _Utils {
        type: "custom";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.generatorExec.LicenseConfig._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        basic: (value: RapiddocsIr.generatorExec.BasicLicense) => _Result;
        custom: (value: RapiddocsIr.generatorExec.CustomLicense) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const LicenseConfig = {
    basic: (value: RapiddocsIr.generatorExec.BasicLicense): RapiddocsIr.generatorExec.LicenseConfig.Basic => {
        return {
            ...value,
            type: "basic",
            _visit: function <_Result>(
                this: RapiddocsIr.generatorExec.LicenseConfig.Basic,
                visitor: RapiddocsIr.generatorExec.LicenseConfig._Visitor<_Result>,
            ) {
                return RapiddocsIr.generatorExec.LicenseConfig._visit(this, visitor);
            },
        };
    },

    custom: (value: RapiddocsIr.generatorExec.CustomLicense): RapiddocsIr.generatorExec.LicenseConfig.Custom => {
        return {
            ...value,
            type: "custom",
            _visit: function <_Result>(
                this: RapiddocsIr.generatorExec.LicenseConfig.Custom,
                visitor: RapiddocsIr.generatorExec.LicenseConfig._Visitor<_Result>,
            ) {
                return RapiddocsIr.generatorExec.LicenseConfig._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsIr.generatorExec.LicenseConfig,
        visitor: RapiddocsIr.generatorExec.LicenseConfig._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "basic":
                return visitor.basic(value);
            case "custom":
                return visitor.custom(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
