/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../../../index";

export interface NugetGithubPublishInfo {
    registryUrl: string;
    packageName: string;
    apiKeyEnvironmentVariable: RapiddocsIr.generatorExec.EnvironmentVariable;
    shouldGeneratePublishWorkflow: boolean | undefined;
}
