/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../../../index";

export type OutputMode =
    | RapiddocsIr.generatorExec.OutputMode.Publish
    | RapiddocsIr.generatorExec.OutputMode.DownloadFiles
    | RapiddocsIr.generatorExec.OutputMode.Github;

export namespace OutputMode {
    export interface Publish extends RapiddocsIr.generatorExec.GeneratorPublishConfig, _Utils {
        type: "publish";
    }

    export interface DownloadFiles extends _Utils {
        type: "downloadFiles";
    }

    export interface Github extends RapiddocsIr.generatorExec.GithubOutputMode, _Utils {
        type: "github";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.generatorExec.OutputMode._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        publish: (value: RapiddocsIr.generatorExec.GeneratorPublishConfig) => _Result;
        downloadFiles: () => _Result;
        github: (value: RapiddocsIr.generatorExec.GithubOutputMode) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const OutputMode = {
    publish: (value: RapiddocsIr.generatorExec.GeneratorPublishConfig): RapiddocsIr.generatorExec.OutputMode.Publish => {
        return {
            ...value,
            type: "publish",
            _visit: function <_Result>(
                this: RapiddocsIr.generatorExec.OutputMode.Publish,
                visitor: RapiddocsIr.generatorExec.OutputMode._Visitor<_Result>,
            ) {
                return RapiddocsIr.generatorExec.OutputMode._visit(this, visitor);
            },
        };
    },

    downloadFiles: (): RapiddocsIr.generatorExec.OutputMode.DownloadFiles => {
        return {
            type: "downloadFiles",
            _visit: function <_Result>(
                this: RapiddocsIr.generatorExec.OutputMode.DownloadFiles,
                visitor: RapiddocsIr.generatorExec.OutputMode._Visitor<_Result>,
            ) {
                return RapiddocsIr.generatorExec.OutputMode._visit(this, visitor);
            },
        };
    },

    github: (value: RapiddocsIr.generatorExec.GithubOutputMode): RapiddocsIr.generatorExec.OutputMode.Github => {
        return {
            ...value,
            type: "github",
            _visit: function <_Result>(
                this: RapiddocsIr.generatorExec.OutputMode.Github,
                visitor: RapiddocsIr.generatorExec.OutputMode._Visitor<_Result>,
            ) {
                return RapiddocsIr.generatorExec.OutputMode._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsIr.generatorExec.OutputMode,
        visitor: RapiddocsIr.generatorExec.OutputMode._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "publish":
                return visitor.publish(value);
            case "downloadFiles":
                return visitor.downloadFiles();
            case "github":
                return visitor.github(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
