/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

/**
 * This should effectively be deprecated in favor of a more specific configuration per-output mode (pypi, maven, etc.).
 */
export interface PublishingMetadata {
    packageDescription: string | undefined;
    publisherEmail: string | undefined;
    referenceUrl: string | undefined;
    publisherName: string | undefined;
}
