# This file was auto-generated by Rapiddocs from our API Definition.

from ....core.exceptions.rapiddocs_http_exception import RapiddocsHTTPException
from ..types.property_based_error_test_body import PropertyBasedErrorTestBody


class PropertyBasedErrorTest(RapiddocsHTTPException):
    def __init__(self, error: PropertyBasedErrorTestBody):
        super().__init__(status_code=400, name="PropertyBasedErrorTest", content=error)
