/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../../../index";

export interface EnumType {
    declaration: RapiddocsIr.dynamic.Declaration;
    values: RapiddocsIr.NameAndWireValue[];
}
