/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../../../index";

export type SingleDiscriminatedUnionType =
    | RapiddocsIr.dynamic.SingleDiscriminatedUnionType.SamePropertiesAsObject
    | RapiddocsIr.dynamic.SingleDiscriminatedUnionType.SingleProperty
    | RapiddocsIr.dynamic.SingleDiscriminatedUnionType.NoProperties;

export namespace SingleDiscriminatedUnionType {
    export interface SamePropertiesAsObject extends RapiddocsIr.dynamic.SingleDiscriminatedUnionTypeObject, _Utils {
        type: "samePropertiesAsObject";
    }

    export interface SingleProperty extends RapiddocsIr.dynamic.SingleDiscriminatedUnionTypeSingleProperty, _Utils {
        type: "singleProperty";
    }

    export interface NoProperties extends RapiddocsIr.dynamic.SingleDiscriminatedUnionTypeNoProperties, _Utils {
        type: "noProperties";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.dynamic.SingleDiscriminatedUnionType._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        samePropertiesAsObject: (value: RapiddocsIr.dynamic.SingleDiscriminatedUnionTypeObject) => _Result;
        singleProperty: (value: RapiddocsIr.dynamic.SingleDiscriminatedUnionTypeSingleProperty) => _Result;
        noProperties: (value: RapiddocsIr.dynamic.SingleDiscriminatedUnionTypeNoProperties) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const SingleDiscriminatedUnionType = {
    samePropertiesAsObject: (
        value: RapiddocsIr.dynamic.SingleDiscriminatedUnionTypeObject,
    ): RapiddocsIr.dynamic.SingleDiscriminatedUnionType.SamePropertiesAsObject => {
        return {
            ...value,
            type: "samePropertiesAsObject",
            _visit: function <_Result>(
                this: RapiddocsIr.dynamic.SingleDiscriminatedUnionType.SamePropertiesAsObject,
                visitor: RapiddocsIr.dynamic.SingleDiscriminatedUnionType._Visitor<_Result>,
            ) {
                return RapiddocsIr.dynamic.SingleDiscriminatedUnionType._visit(this, visitor);
            },
        };
    },

    singleProperty: (
        value: RapiddocsIr.dynamic.SingleDiscriminatedUnionTypeSingleProperty,
    ): RapiddocsIr.dynamic.SingleDiscriminatedUnionType.SingleProperty => {
        return {
            ...value,
            type: "singleProperty",
            _visit: function <_Result>(
                this: RapiddocsIr.dynamic.SingleDiscriminatedUnionType.SingleProperty,
                visitor: RapiddocsIr.dynamic.SingleDiscriminatedUnionType._Visitor<_Result>,
            ) {
                return RapiddocsIr.dynamic.SingleDiscriminatedUnionType._visit(this, visitor);
            },
        };
    },

    noProperties: (
        value: RapiddocsIr.dynamic.SingleDiscriminatedUnionTypeNoProperties,
    ): RapiddocsIr.dynamic.SingleDiscriminatedUnionType.NoProperties => {
        return {
            ...value,
            type: "noProperties",
            _visit: function <_Result>(
                this: RapiddocsIr.dynamic.SingleDiscriminatedUnionType.NoProperties,
                visitor: RapiddocsIr.dynamic.SingleDiscriminatedUnionType._Visitor<_Result>,
            ) {
                return RapiddocsIr.dynamic.SingleDiscriminatedUnionType._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsIr.dynamic.SingleDiscriminatedUnionType,
        visitor: RapiddocsIr.dynamic.SingleDiscriminatedUnionType._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "samePropertiesAsObject":
                return visitor.samePropertiesAsObject(value);
            case "singleProperty":
                return visitor.singleProperty(value);
            case "noProperties":
                return visitor.noProperties(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
