// This file was auto-generated by Rapiddocs from our API Definition.

package client

import (
	core "github.com/literal/rapiddocs/core"
	headers "github.com/literal/rapiddocs/headers"
	inlined "github.com/literal/rapiddocs/inlined"
	internal "github.com/literal/rapiddocs/internal"
	option "github.com/literal/rapiddocs/option"
	path "github.com/literal/rapiddocs/path"
	query "github.com/literal/rapiddocs/query"
	reference "github.com/literal/rapiddocs/reference"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Headers   *headers.Client
	Inlined   *inlined.Client
	Path      *path.Client
	Query     *query.Client
	Reference *reference.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:    options.ToHeader(),
		Headers:   headers.NewClient(opts...),
		Inlined:   inlined.NewClient(opts...),
		Path:      path.NewClient(opts...),
		Query:     query.NewClient(opts...),
		Reference: reference.NewClient(opts...),
	}
}
