/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../../../index";

export type MultipleEnvironmentUrlValues = Record<RapiddocsIr.EnvironmentBaseUrlId, RapiddocsIr.EnvironmentUrl>;
