/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";

export const NamespaceId: core.serialization.Schema<serializers.NamespaceId.Raw, RapiddocsOpenapiIr.NamespaceId> =
    core.serialization.string();

export declare namespace NamespaceId {
    export type Raw = string;
}
