/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";

export const OpenApiSource: core.serialization.ObjectSchema<
    serializers.OpenApiSource.Raw,
    RapiddocsOpenapiIr.OpenApiSource
> = core.serialization.objectWithoutOptionalProperties({
    file: core.serialization.string(),
});

export declare namespace OpenApiSource {
    export interface Raw {
        file: string;
    }
}
