/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";
import { SdkGroup } from "./SdkGroup";

export const SdkGroupName: core.serialization.Schema<serializers.SdkGroupName.Raw, RapiddocsOpenapiIr.SdkGroupName> =
    core.serialization.list(SdkGroup);

export declare namespace SdkGroupName {
    export type Raw = SdkGroup.Raw[];
}
