/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";

export const StatusCode: core.serialization.Schema<serializers.StatusCode.Raw, RapiddocsOpenapiIr.StatusCode> =
    core.serialization.number();

export declare namespace StatusCode {
    export type Raw = number;
}
