/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";
import { TagId } from "./TagId";
import { WithDescription } from "./WithDescription";

export const Tag: core.serialization.ObjectSchema<serializers.Tag.Raw, RapiddocsOpenapiIr.Tag> = core.serialization
    .objectWithoutOptionalProperties({
        id: TagId,
    })
    .extend(WithDescription);

export declare namespace Tag {
    export interface Raw extends WithDescription.Raw {
        id: TagId.Raw;
    }
}
