/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";
import { Encoding } from "./Encoding";

export const WithEncoding: core.serialization.ObjectSchema<serializers.WithEncoding.Raw, RapiddocsOpenapiIr.WithEncoding> =
    core.serialization.objectWithoutOptionalProperties({
        encoding: Encoding.optional(),
    });

export declare namespace WithEncoding {
    export interface Raw {
        encoding?: Encoding.Raw | null;
    }
}
