/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";

export const WithName: core.serialization.ObjectSchema<serializers.WithName.Raw, RapiddocsOpenapiIr.WithName> =
    core.serialization.objectWithoutOptionalProperties({
        nameOverride: core.serialization.string().optional(),
        generatedName: core.serialization.string(),
    });

export declare namespace WithName {
    export interface Raw {
        nameOverride?: string | null;
        generatedName: string;
    }
}
