/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";
import { Availability } from "../../finalIr/types/Availability";

export const WithAvailability: core.serialization.ObjectSchema<
    serializers.WithAvailability.Raw,
    RapiddocsOpenapiIr.WithAvailability
> = core.serialization.objectWithoutOptionalProperties({
    availability: Availability.optional(),
});

export declare namespace WithAvailability {
    export interface Raw {
        availability?: Availability.Raw | null;
    }
}
