/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";

export const GithubLicenseCustomSchema: core.serialization.ObjectSchema<
    serializers.GithubLicenseCustomSchema.Raw,
    RapiddocsDefinition.GithubLicenseCustomSchema
> = core.serialization.object({
    custom: core.serialization.string(),
});

export declare namespace GithubLicenseCustomSchema {
    export interface Raw {
        custom: string;
    }
}
