/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDocsConfig from "../../../../api/index";
import * as core from "../../../../core";

export const ChangelogFolderRelativePath: core.serialization.Schema<
    serializers.ChangelogFolderRelativePath.Raw,
    RapiddocsDocsConfig.ChangelogFolderRelativePath
> = core.serialization.string();

export declare namespace ChangelogFolderRelativePath {
    export type Raw = string;
}
