/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDocsConfig from "../../../../api/index";
import * as core from "../../../../core";

export const ContentAlignment: core.serialization.Schema<
    serializers.ContentAlignment.Raw,
    RapiddocsDocsConfig.ContentAlignment
> = core.serialization.enum_(["center", "left"]);

export declare namespace ContentAlignment {
    export type Raw = "center" | "left";
}
