/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDocsConfig from "../../../../api/index";
import * as core from "../../../../core";

export const CssConfig: core.serialization.Schema<serializers.CssConfig.Raw, RapiddocsDocsConfig.CssConfig> =
    core.serialization.undiscriminatedUnion([
        core.serialization.string(),
        core.serialization.list(core.serialization.string()),
    ]);

export declare namespace CssConfig {
    export type Raw = string | string[];
}
