/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDocsConfig from "../../../../api/index";
import * as core from "../../../../core";

export const ExperimentalConfig: core.serialization.ObjectSchema<
    serializers.ExperimentalConfig.Raw,
    RapiddocsDocsConfig.ExperimentalConfig
> = core.serialization.object({
    mdxComponents: core.serialization.property(
        "mdx-components",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    disableStreamToggle: core.serialization.property("disable-stream-toggle", core.serialization.boolean().optional()),
    openapiParserV2: core.serialization.property("openapi-parser-v2", core.serialization.boolean().optional()),
    openapiParserV3: core.serialization.property("openapi-parser-v3", core.serialization.boolean().optional()),
});

export declare namespace ExperimentalConfig {
    export interface Raw {
        "mdx-components"?: string[] | null;
        "disable-stream-toggle"?: boolean | null;
        "openapi-parser-v2"?: boolean | null;
        "openapi-parser-v3"?: boolean | null;
    }
}
