/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDocsConfig from "../../../../api/index";
import * as core from "../../../../core";
import { FeatureFlag } from "./FeatureFlag";

export const FeatureFlagConfiguration: core.serialization.Schema<
    serializers.FeatureFlagConfiguration.Raw,
    RapiddocsDocsConfig.FeatureFlagConfiguration
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    FeatureFlag,
    core.serialization.list(FeatureFlag),
]);

export declare namespace FeatureFlagConfiguration {
    export type Raw = string | FeatureFlag.Raw | FeatureFlag.Raw[];
}
