/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDocsConfig from "../../../../api/index";
import * as core from "../../../../core";
import { FontConfigVariant } from "./FontConfigVariant";

export const FontConfigPath: core.serialization.Schema<serializers.FontConfigPath.Raw, RapiddocsDocsConfig.FontConfigPath> =
    core.serialization.undiscriminatedUnion([core.serialization.string(), FontConfigVariant]);

export declare namespace FontConfigPath {
    export type Raw = string | FontConfigVariant.Raw;
}
