/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDocsConfig from "../../../../api/index";
import * as core from "../../../../core";

export const GoogleAnalytics4Config: core.serialization.ObjectSchema<
    serializers.GoogleAnalytics4Config.Raw,
    RapiddocsDocsConfig.GoogleAnalytics4Config
> = core.serialization.object({
    measurementId: core.serialization.property("measurement-id", core.serialization.string()),
});

export declare namespace GoogleAnalytics4Config {
    export interface Raw {
        "measurement-id": string;
    }
}
