/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDocsConfig from "../../../../api/index";
import * as core from "../../../../core";

export const GtmConfig: core.serialization.ObjectSchema<serializers.GtmConfig.Raw, RapiddocsDocsConfig.GtmConfig> =
    core.serialization.object({
        containerId: core.serialization.property("container-id", core.serialization.string()),
    });

export declare namespace GtmConfig {
    export interface Raw {
        "container-id": string;
    }
}
