/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDocsConfig from "../../../../api/index";
import * as core from "../../../../core";
import { JsConfigOptions } from "./JsConfigOptions";

export const JsConfig: core.serialization.Schema<serializers.JsConfig.Raw, RapiddocsDocsConfig.JsConfig> =
    core.serialization.undiscriminatedUnion([JsConfigOptions, core.serialization.list(JsConfigOptions)]);

export declare namespace JsConfig {
    export type Raw = JsConfigOptions.Raw | JsConfigOptions.Raw[];
}
