/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDocsConfig from "../../../../api/index";
import * as core from "../../../../core";
import { JsFileConfigSettings } from "./JsFileConfigSettings";

export const JsFileConfig: core.serialization.Schema<serializers.JsFileConfig.Raw, RapiddocsDocsConfig.JsFileConfig> =
    core.serialization.undiscriminatedUnion([core.serialization.string(), JsFileConfigSettings]);

export declare namespace JsFileConfig {
    export type Raw = string | JsFileConfigSettings.Raw;
}
