/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDocsConfig from "../../../../api/index";
import * as core from "../../../../core";

export const JsScriptStrategy: core.serialization.Schema<
    serializers.JsScriptStrategy.Raw,
    RapiddocsDocsConfig.JsScriptStrategy
> = core.serialization.enum_(["beforeInteractive", "afterInteractive", "lazyOnload"]);

export declare namespace JsScriptStrategy {
    export type Raw = "beforeInteractive" | "afterInteractive" | "lazyOnload";
}
