/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDocsConfig from "../../../../api/index";
import * as core from "../../../../core";

export const NavbarLinkConfig: core.serialization.ObjectSchema<
    serializers.NavbarLinkConfig.Raw,
    RapiddocsDocsConfig.NavbarLinkConfig
> = core.serialization.object({
    href: core.serialization.string().optional(),
    url: core.serialization.string().optional(),
    text: core.serialization.string().optional(),
    icon: core.serialization.string().optional(),
    rightIcon: core.serialization.string().optional(),
    rounded: core.serialization.boolean().optional(),
});

export declare namespace NavbarLinkConfig {
    export interface Raw {
        href?: string | null;
        url?: string | null;
        text?: string | null;
        icon?: string | null;
        rightIcon?: string | null;
        rounded?: boolean | null;
    }
}
