/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDocsConfig from "../../../../api/index";
import * as core from "../../../../core";
import { PlaygroundButtonSettings } from "./PlaygroundButtonSettings";

export const PlaygroundSettings: core.serialization.ObjectSchema<
    serializers.PlaygroundSettings.Raw,
    RapiddocsDocsConfig.PlaygroundSettings
> = core.serialization.object({
    environments: core.serialization.list(core.serialization.string()).optional(),
    button: PlaygroundButtonSettings.optional(),
    oauth: core.serialization.boolean().optional(),
    limitWebsocketMessagesPerConnection: core.serialization.property(
        "limit-websocket-messages-per-connection",
        core.serialization.number().optional(),
    ),
});

export declare namespace PlaygroundSettings {
    export interface Raw {
        environments?: string[] | null;
        button?: PlaygroundButtonSettings.Raw | null;
        oauth?: boolean | null;
        "limit-websocket-messages-per-connection"?: number | null;
    }
}
