/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDocsConfig from "../../../../api/index";
import * as core from "../../../../core";

export const PlaygroundButtonSettings: core.serialization.ObjectSchema<
    serializers.PlaygroundButtonSettings.Raw,
    RapiddocsDocsConfig.PlaygroundButtonSettings
> = core.serialization.object({
    href: core.serialization.string().optional(),
});

export declare namespace PlaygroundButtonSettings {
    export interface Raw {
        href?: string | null;
    }
}
