/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDocsConfig from "../../../../api/index";
import * as core from "../../../../core";

export const SearchbarPlacement: core.serialization.Schema<
    serializers.SearchbarPlacement.Raw,
    RapiddocsDocsConfig.SearchbarPlacement
> = core.serialization.enum_(["header", "header-tabs", "sidebar"]);

export declare namespace SearchbarPlacement {
    export type Raw = "header" | "header-tabs" | "sidebar";
}
