/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDocsConfig from "../../../../api/index";
import * as core from "../../../../core";

export const SegmentConfig: core.serialization.ObjectSchema<
    serializers.SegmentConfig.Raw,
    RapiddocsDocsConfig.SegmentConfig
> = core.serialization.object({
    writeKey: core.serialization.property("write-key", core.serialization.string()),
});

export declare namespace SegmentConfig {
    export interface Raw {
        "write-key": string;
    }
}
