/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDocsConfig from "../../../../api/index";
import * as core from "../../../../core";

export const UntabbedNavigationConfig: core.serialization.Schema<
    serializers.UntabbedNavigationConfig.Raw,
    RapiddocsDocsConfig.UntabbedNavigationConfig
> = core.serialization.list(core.serialization.lazy(() => serializers.NavigationItem));

export declare namespace UntabbedNavigationConfig {
    export type Raw = serializers.NavigationItem.Raw[];
}
