# This file was auto-generated by Rapiddocs from our API Definition.

from ......core.abstract_rapiddocs_service import AbstractRapiddocsService
from ......security import ApiAuth
from .....types.types.file import File
import abc
import fastapi
import inspect
import typing
from ......security import RapiddocsAuth
from .....types.errors.not_found_error import NotFoundError
from ......core.exceptions.rapiddocs_http_exception import RapiddocsHTTPException
import logging
import functools
from ......core.route_args import get_route_args


class AbstractFileServiceService(AbstractRapiddocsService):
    """
    AbstractFileServiceService is an abstract class containing the methods that you should implement.

    Each method is associated with an API route, which will be registered
    with FastAPI when you register your implementation using Rapiddocs's register()
    function.
    """

    @abc.abstractmethod
    def get_file(self, *, filename: str, auth: ApiAuth) -> File:
        """
        This endpoint returns a file by its name.
        """
        ...

    """
    Below are internal methods used by Rapiddocs to register your implementation.
    You can ignore them.
    """

    @classmethod
    def _init_rapiddocs(cls, router: fastapi.APIRouter) -> None:
        cls.__init_get_file(router=router)

    @classmethod
    def __init_get_file(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.get_file)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(
            endpoint_function.parameters.items()
        ):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "filename":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            elif parameter_name == "auth":
                new_parameters.append(
                    parameter.replace(default=fastapi.Depends(RapiddocsAuth))
                )
            else:
                new_parameters.append(parameter)
        setattr(
            cls.get_file,
            "__signature__",
            endpoint_function.replace(parameters=new_parameters),
        )

        @functools.wraps(cls.get_file)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> File:
            try:
                return cls.get_file(*args, **kwargs)
            except NotFoundError as e:
                raise e
            except RapiddocsHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'get_file' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Rapiddocs Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.get_file.__globals__)

        router.get(
            path="/file/{filename}",
            response_model=File,
            description=AbstractFileServiceService.get_file.__doc__,
            **get_route_args(cls.get_file, default_tag="file.service"),
        )(wrapper)
