# This file was auto-generated by Rapiddocs from our API Definition.

from ......core.exceptions.rapiddocs_http_exception import RapiddocsHTTPException
from ..types.object_with_required_field import ObjectWithRequiredField


class ObjectWithRequiredFieldError(RapiddocsHTTPException):
    def __init__(self, error: ObjectWithRequiredField):
        super().__init__(
            status_code=400, name="ObjectWithRequiredFieldError", content=error
        )
