/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface MultipleBaseUrlsEnvironmentSchema extends RapiddocsDefinition.WithAudiences, RapiddocsDefinition.WithDocsSchema {
    urls: Record<string, string>;
}
