/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../../../index";

export type EnvironmentSchema =
    | string
    | RapiddocsDefinition.rapiddocsDefinition.SingleBaseUrlEnvironmentSchema
    | RapiddocsDefinition.rapiddocsDefinition.MultipleBaseUrlsEnvironmentSchema;
