/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { WithDocsSchema } from "../../commons/types/WithDocsSchema";

export const WebhookReferencedPayloadSchema: core.serialization.ObjectSchema<
    serializers.WebhookReferencedPayloadSchema.Raw,
    RapiddocsDefinition.WebhookReferencedPayloadSchema
> = core.serialization
    .object({
        type: core.serialization.string(),
    })
    .extend(WithDocsSchema);

export declare namespace WebhookReferencedPayloadSchema {
    export interface Raw extends WithDocsSchema.Raw {
        type: string;
    }
}
