/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../../index";

export interface StoreTracedWorkspaceRequest {
    workspaceRunDetails: SeedTrace.WorkspaceRunDetails;
    traceResponses: SeedTrace.TraceResponse[];
}
