/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../../../index";

export interface GetGeneratedTestCaseFileRequest {
    template?: SeedTrace.v2.TestCaseTemplate;
    testCase: SeedTrace.v2.TestCaseV2;
}
