/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

/**
 * @example
 *     {
 *         docs: "Types extend this type to include a docs property."
 *     }
 */
export interface Docs {
    docs: string;
}
