// This file was auto-generated by Rapiddocs from our API Definition.

package client

import (
	core "github.com/multi-line-docs/rapiddocs/core"
	internal "github.com/multi-line-docs/rapiddocs/internal"
	option "github.com/multi-line-docs/rapiddocs/option"
	user "github.com/multi-line-docs/rapiddocs/user"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	User *user.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
		User:   user.NewClient(opts...),
	}
}
