/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../../../index";

export type AuthValues =
    | RapiddocsIr.dynamic.AuthValues.Basic
    | RapiddocsIr.dynamic.AuthValues.Bearer
    | RapiddocsIr.dynamic.AuthValues.Header
    | RapiddocsIr.dynamic.AuthValues.Oauth;

export namespace AuthValues {
    export interface Basic extends RapiddocsIr.dynamic.BasicAuthValues, _Utils {
        type: "basic";
    }

    export interface Bearer extends RapiddocsIr.dynamic.BearerAuthValues, _Utils {
        type: "bearer";
    }

    export interface Header extends RapiddocsIr.dynamic.HeaderAuthValues, _Utils {
        type: "header";
    }

    export interface Oauth extends RapiddocsIr.dynamic.OAuthValues, _Utils {
        type: "oauth";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.dynamic.AuthValues._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        basic: (value: RapiddocsIr.dynamic.BasicAuthValues) => _Result;
        bearer: (value: RapiddocsIr.dynamic.BearerAuthValues) => _Result;
        header: (value: RapiddocsIr.dynamic.HeaderAuthValues) => _Result;
        oauth: (value: RapiddocsIr.dynamic.OAuthValues) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const AuthValues = {
    basic: (value: RapiddocsIr.dynamic.BasicAuthValues): RapiddocsIr.dynamic.AuthValues.Basic => {
        return {
            ...value,
            type: "basic",
            _visit: function <_Result>(
                this: RapiddocsIr.dynamic.AuthValues.Basic,
                visitor: RapiddocsIr.dynamic.AuthValues._Visitor<_Result>,
            ) {
                return RapiddocsIr.dynamic.AuthValues._visit(this, visitor);
            },
        };
    },

    bearer: (value: RapiddocsIr.dynamic.BearerAuthValues): RapiddocsIr.dynamic.AuthValues.Bearer => {
        return {
            ...value,
            type: "bearer",
            _visit: function <_Result>(
                this: RapiddocsIr.dynamic.AuthValues.Bearer,
                visitor: RapiddocsIr.dynamic.AuthValues._Visitor<_Result>,
            ) {
                return RapiddocsIr.dynamic.AuthValues._visit(this, visitor);
            },
        };
    },

    header: (value: RapiddocsIr.dynamic.HeaderAuthValues): RapiddocsIr.dynamic.AuthValues.Header => {
        return {
            ...value,
            type: "header",
            _visit: function <_Result>(
                this: RapiddocsIr.dynamic.AuthValues.Header,
                visitor: RapiddocsIr.dynamic.AuthValues._Visitor<_Result>,
            ) {
                return RapiddocsIr.dynamic.AuthValues._visit(this, visitor);
            },
        };
    },

    oauth: (value: RapiddocsIr.dynamic.OAuthValues): RapiddocsIr.dynamic.AuthValues.Oauth => {
        return {
            ...value,
            type: "oauth",
            _visit: function <_Result>(
                this: RapiddocsIr.dynamic.AuthValues.Oauth,
                visitor: RapiddocsIr.dynamic.AuthValues._Visitor<_Result>,
            ) {
                return RapiddocsIr.dynamic.AuthValues._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsIr.dynamic.AuthValues,
        visitor: RapiddocsIr.dynamic.AuthValues._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "basic":
                return visitor.basic(value);
            case "bearer":
                return visitor.bearer(value);
            case "header":
                return visitor.header(value);
            case "oauth":
                return visitor.oauth(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
