/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../../../index";

export interface BasicAuth {
    username: RapiddocsIr.Name;
    password: RapiddocsIr.Name;
}
