/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import express from "express";
import { OptionalService } from "./api/resources/optional/service/OptionalService";

export function register(
    expressApp: express.Express | express.Router,
    services: {
        optional: OptionalService;
    },
): void {
    (expressApp as any).use("", services.optional.toRouter());
}
