/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedUndiscriminatedUnions from "../../../index";

export interface TypeWithOptionalUnion {
    myUnion?: SeedUndiscriminatedUnions.MyUnion;
}
