/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export type Shape = "SQUARE" | "CIRCLE" | "TRIANGLE";
export const Shape = {
    Square: "SQUARE",
    Circle: "CIRCLE",
    Triangle: "TRIANGLE",
} as const;
