/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as Fiddle from "../../../../../index";

export interface DoubleOptional {
    optionalAlias?: Fiddle.types.OptionalAlias | undefined;
}
