/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsIr from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { NameAndWireValue } from "../../../../commons/types/NameAndWireValue";
import { NamedParameter } from "./NamedParameter";

export const SingleDiscriminatedUnionTypeNoProperties: core.serialization.ObjectSchema<
    serializers.dynamic.SingleDiscriminatedUnionTypeNoProperties.Raw,
    RapiddocsIr.dynamic.SingleDiscriminatedUnionTypeNoProperties
> = core.serialization.objectWithoutOptionalProperties({
    discriminantValue: NameAndWireValue,
    properties: core.serialization.list(NamedParameter).optional(),
});

export declare namespace SingleDiscriminatedUnionTypeNoProperties {
    export interface Raw {
        discriminantValue: NameAndWireValue.Raw;
        properties?: NamedParameter.Raw[] | null;
    }
}
