/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface GeneratorGroupSchema {
    audiences?: string[];
    generators: RapiddocsDefinition.GeneratorInvocationSchema[];
    metadata?: RapiddocsDefinition.OutputMetadataSchema;
    reviewers?: RapiddocsDefinition.ReviewersSchema;
}
