/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export type GithubCommitAndReleaseMode = "commit" | "release";
export const GithubCommitAndReleaseMode = {
    Commit: "commit",
    Release: "release",
} as const;
