/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface GithubPushSchema {
    repository: string;
    license?: RapiddocsDefinition.GithubLicenseSchema;
    mode: "push";
    branch?: string;
}
