/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export interface PostmanOutputLocationSchema {
    "api-key": string;
    "workspace-id": string;
    "collection-id"?: string;
}
