/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface PypiOutputMetadataSchema extends RapiddocsDefinition.OutputMetadataSchema {
    keywords?: string[];
    "documentation-link"?: string;
    "homepage-link"?: string;
}
