/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../../../../../index";

export interface GetBasicSolutionFileResponse {
    solutionFileByLanguage: Record<SeedTrace.Language, SeedTrace.v2.v3.FileInfoV2 | undefined>;
}
