/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface ExampleQueryParameter {
    name: RapiddocsIr.NameAndWireValue;
    value: RapiddocsIr.ExampleTypeReference;
    shape: RapiddocsIr.ExampleQueryParameterShape | undefined;
}
