/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export type ExampleRequestBody = RapiddocsIr.ExampleRequestBody.InlinedRequestBody | RapiddocsIr.ExampleRequestBody.Reference;

export namespace ExampleRequestBody {
    export interface InlinedRequestBody extends RapiddocsIr.ExampleInlinedRequestBody, _Utils {
        type: "inlinedRequestBody";
    }

    export interface Reference extends RapiddocsIr.ExampleTypeReference, _Utils {
        type: "reference";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.ExampleRequestBody._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        inlinedRequestBody: (value: RapiddocsIr.ExampleInlinedRequestBody) => _Result;
        reference: (value: RapiddocsIr.ExampleTypeReference) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const ExampleRequestBody = {
    inlinedRequestBody: (value: RapiddocsIr.ExampleInlinedRequestBody): RapiddocsIr.ExampleRequestBody.InlinedRequestBody => {
        return {
            ...value,
            type: "inlinedRequestBody",
            _visit: function <_Result>(
                this: RapiddocsIr.ExampleRequestBody.InlinedRequestBody,
                visitor: RapiddocsIr.ExampleRequestBody._Visitor<_Result>,
            ) {
                return RapiddocsIr.ExampleRequestBody._visit(this, visitor);
            },
        };
    },

    reference: (value: RapiddocsIr.ExampleTypeReference): RapiddocsIr.ExampleRequestBody.Reference => {
        return {
            ...value,
            type: "reference",
            _visit: function <_Result>(
                this: RapiddocsIr.ExampleRequestBody.Reference,
                visitor: RapiddocsIr.ExampleRequestBody._Visitor<_Result>,
            ) {
                return RapiddocsIr.ExampleRequestBody._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsIr.ExampleRequestBody,
        visitor: RapiddocsIr.ExampleRequestBody._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "inlinedRequestBody":
                return visitor.inlinedRequestBody(value);
            case "reference":
                return visitor.reference(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
