/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export type ExampleResponse = RapiddocsIr.ExampleResponse.Ok | RapiddocsIr.ExampleResponse.Error_;

export namespace ExampleResponse {
    export interface Ok extends _Utils {
        type: "ok";
        value: RapiddocsIr.ExampleEndpointSuccessResponse;
    }

    export interface Error_ extends RapiddocsIr.ExampleEndpointErrorResponse, _Utils {
        type: "error";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.ExampleResponse._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        ok: (value: RapiddocsIr.ExampleEndpointSuccessResponse) => _Result;
        error: (value: RapiddocsIr.ExampleEndpointErrorResponse) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const ExampleResponse = {
    ok: (value: RapiddocsIr.ExampleEndpointSuccessResponse): RapiddocsIr.ExampleResponse.Ok => {
        return {
            value: value,
            type: "ok",
            _visit: function <_Result>(
                this: RapiddocsIr.ExampleResponse.Ok,
                visitor: RapiddocsIr.ExampleResponse._Visitor<_Result>,
            ) {
                return RapiddocsIr.ExampleResponse._visit(this, visitor);
            },
        };
    },

    error: (value: RapiddocsIr.ExampleEndpointErrorResponse): RapiddocsIr.ExampleResponse.Error_ => {
        return {
            ...value,
            type: "error",
            _visit: function <_Result>(
                this: RapiddocsIr.ExampleResponse.Error_,
                visitor: RapiddocsIr.ExampleResponse._Visitor<_Result>,
            ) {
                return RapiddocsIr.ExampleResponse._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(value: RapiddocsIr.ExampleResponse, visitor: RapiddocsIr.ExampleResponse._Visitor<_Result>): _Result => {
        switch (value.type) {
            case "ok":
                return visitor.ok(value.value);
            case "error":
                return visitor.error(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
