/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface ExampleServerSideEvent {
    event: string;
    data: RapiddocsIr.ExampleTypeReference;
}
