/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface ExampleEndpointCall extends RapiddocsIr.WithDocs {
    id: string | undefined;
    name: RapiddocsIr.Name | undefined;
    url: string;
    rootPathParameters: RapiddocsIr.ExamplePathParameter[];
    servicePathParameters: RapiddocsIr.ExamplePathParameter[];
    endpointPathParameters: RapiddocsIr.ExamplePathParameter[];
    serviceHeaders: RapiddocsIr.ExampleHeader[];
    endpointHeaders: RapiddocsIr.ExampleHeader[];
    queryParameters: RapiddocsIr.ExampleQueryParameter[];
    request: RapiddocsIr.ExampleRequestBody | undefined;
    response: RapiddocsIr.ExampleResponse;
}
