/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export type JsonResponse = RapiddocsIr.JsonResponse.Response | RapiddocsIr.JsonResponse.NestedPropertyAsResponse;

export namespace JsonResponse {
    export interface Response extends RapiddocsIr.JsonResponseBody, _Utils {
        type: "response";
    }

    export interface NestedPropertyAsResponse extends RapiddocsIr.JsonResponseBodyWithProperty, _Utils {
        type: "nestedPropertyAsResponse";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.JsonResponse._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        response: (value: RapiddocsIr.JsonResponseBody) => _Result;
        nestedPropertyAsResponse: (value: RapiddocsIr.JsonResponseBodyWithProperty) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const JsonResponse = {
    response: (value: RapiddocsIr.JsonResponseBody): RapiddocsIr.JsonResponse.Response => {
        return {
            ...value,
            type: "response",
            _visit: function <_Result>(
                this: RapiddocsIr.JsonResponse.Response,
                visitor: RapiddocsIr.JsonResponse._Visitor<_Result>,
            ) {
                return RapiddocsIr.JsonResponse._visit(this, visitor);
            },
        };
    },

    nestedPropertyAsResponse: (
        value: RapiddocsIr.JsonResponseBodyWithProperty,
    ): RapiddocsIr.JsonResponse.NestedPropertyAsResponse => {
        return {
            ...value,
            type: "nestedPropertyAsResponse",
            _visit: function <_Result>(
                this: RapiddocsIr.JsonResponse.NestedPropertyAsResponse,
                visitor: RapiddocsIr.JsonResponse._Visitor<_Result>,
            ) {
                return RapiddocsIr.JsonResponse._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(value: RapiddocsIr.JsonResponse, visitor: RapiddocsIr.JsonResponse._Visitor<_Result>): _Result => {
        switch (value.type) {
            case "response":
                return visitor.response(value);
            case "nestedPropertyAsResponse":
                return visitor.nestedPropertyAsResponse(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
