/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface JsonStreamChunk extends RapiddocsIr.WithDocs {
    payload: RapiddocsIr.TypeReference;
    terminator: string | undefined;
}
