/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export type NonStreamHttpResponseBody =
    | RapiddocsIr.NonStreamHttpResponseBody.Json
    | RapiddocsIr.NonStreamHttpResponseBody.FileDownload
    | RapiddocsIr.NonStreamHttpResponseBody.Text
    | RapiddocsIr.NonStreamHttpResponseBody.Bytes;

export namespace NonStreamHttpResponseBody {
    export interface Json extends _Utils {
        type: "json";
        value: RapiddocsIr.JsonResponse;
    }

    export interface FileDownload extends RapiddocsIr.FileDownloadResponse, _Utils {
        type: "fileDownload";
    }

    export interface Text extends RapiddocsIr.TextResponse, _Utils {
        type: "text";
    }

    export interface Bytes extends RapiddocsIr.BytesResponse, _Utils {
        type: "bytes";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.NonStreamHttpResponseBody._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        json: (value: RapiddocsIr.JsonResponse) => _Result;
        fileDownload: (value: RapiddocsIr.FileDownloadResponse) => _Result;
        text: (value: RapiddocsIr.TextResponse) => _Result;
        bytes: (value: RapiddocsIr.BytesResponse) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const NonStreamHttpResponseBody = {
    json: (value: RapiddocsIr.JsonResponse): RapiddocsIr.NonStreamHttpResponseBody.Json => {
        return {
            value: value,
            type: "json",
            _visit: function <_Result>(
                this: RapiddocsIr.NonStreamHttpResponseBody.Json,
                visitor: RapiddocsIr.NonStreamHttpResponseBody._Visitor<_Result>,
            ) {
                return RapiddocsIr.NonStreamHttpResponseBody._visit(this, visitor);
            },
        };
    },

    fileDownload: (value: RapiddocsIr.FileDownloadResponse): RapiddocsIr.NonStreamHttpResponseBody.FileDownload => {
        return {
            ...value,
            type: "fileDownload",
            _visit: function <_Result>(
                this: RapiddocsIr.NonStreamHttpResponseBody.FileDownload,
                visitor: RapiddocsIr.NonStreamHttpResponseBody._Visitor<_Result>,
            ) {
                return RapiddocsIr.NonStreamHttpResponseBody._visit(this, visitor);
            },
        };
    },

    text: (value: RapiddocsIr.TextResponse): RapiddocsIr.NonStreamHttpResponseBody.Text => {
        return {
            ...value,
            type: "text",
            _visit: function <_Result>(
                this: RapiddocsIr.NonStreamHttpResponseBody.Text,
                visitor: RapiddocsIr.NonStreamHttpResponseBody._Visitor<_Result>,
            ) {
                return RapiddocsIr.NonStreamHttpResponseBody._visit(this, visitor);
            },
        };
    },

    bytes: (value: RapiddocsIr.BytesResponse): RapiddocsIr.NonStreamHttpResponseBody.Bytes => {
        return {
            ...value,
            type: "bytes",
            _visit: function <_Result>(
                this: RapiddocsIr.NonStreamHttpResponseBody.Bytes,
                visitor: RapiddocsIr.NonStreamHttpResponseBody._Visitor<_Result>,
            ) {
                return RapiddocsIr.NonStreamHttpResponseBody._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsIr.NonStreamHttpResponseBody,
        visitor: RapiddocsIr.NonStreamHttpResponseBody._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "json":
                return visitor.json(value.value);
            case "fileDownload":
                return visitor.fileDownload(value);
            case "text":
                return visitor.text(value);
            case "bytes":
                return visitor.bytes(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
