/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface SdkRequestWrapper {
    wrapperName: RapiddocsIr.Name;
    bodyKey: RapiddocsIr.Name;
    includePathParameters: boolean | undefined;
    onlyPathParameters: boolean | undefined;
}
