/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface UserSpecifiedEndpointExample {
    /** Manually written code samples specified by the user */
    codeSamples: RapiddocsIr.ExampleCodeSample[] | undefined;
    /** Manually written example specified by the user */
    example: RapiddocsIr.ExampleEndpointCall | undefined;
}
