/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";

export const DatetimeWithExample: core.serialization.ObjectSchema<
    serializers.DatetimeWithExample.Raw,
    RapiddocsOpenapiIr.DatetimeWithExample
> = core.serialization.objectWithoutOptionalProperties({
    example: core.serialization.string().optional(),
});

export declare namespace DatetimeWithExample {
    export interface Raw {
        example?: string | null;
    }
}
