/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";

export const OneOfSchemaWithExample: core.serialization.Schema<
    serializers.OneOfSchemaWithExample.Raw,
    RapiddocsOpenapiIr.OneOfSchemaWithExample
> = core.serialization
    .union("type", {
        discriminated: core.serialization.lazyObject(() => serializers.DiscriminatedOneOfSchemaWithExample),
        undiscriminated: core.serialization.lazyObject(() => serializers.UnDiscriminatedOneOfSchemaWithExample),
    })
    .transform<RapiddocsOpenapiIr.OneOfSchemaWithExample>({
        transform: (value) => {
            switch (value.type) {
                case "discriminated":
                    return RapiddocsOpenapiIr.OneOfSchemaWithExample.discriminated(value);
                case "undiscriminated":
                    return RapiddocsOpenapiIr.OneOfSchemaWithExample.undiscriminated(value);
                default:
                    return value as RapiddocsOpenapiIr.OneOfSchemaWithExample;
            }
        },
        untransform: ({ _visit, ...value }) => value as any,
    });

export declare namespace OneOfSchemaWithExample {
    export type Raw = OneOfSchemaWithExample.Discriminated | OneOfSchemaWithExample.Undiscriminated;

    export interface Discriminated extends serializers.DiscriminatedOneOfSchemaWithExample.Raw {
        type: "discriminated";
    }

    export interface Undiscriminated extends serializers.UnDiscriminatedOneOfSchemaWithExample.Raw {
        type: "undiscriminated";
    }
}
