export { RapiddocsIr as V57 } from "@khulnasoft/ir-sdk";
export * as V1 from "@rapiddocs-rapiddocs/ir-v1-model";
export * as V10 from "@rapiddocs-rapiddocs/ir-v10-model";
export * as V11 from "@rapiddocs-rapiddocs/ir-v11-model";
export * as V12 from "@rapiddocs-rapiddocs/ir-v12-model";
export * as V13 from "@rapiddocs-rapiddocs/ir-v13-model";
export * as V14 from "@rapiddocs-rapiddocs/ir-v14-model";
export * as V15 from "@rapiddocs-rapiddocs/ir-v15-model";
export * as V16 from "@rapiddocs-rapiddocs/ir-v16-model";
export * as V17 from "@rapiddocs-rapiddocs/ir-v17-model";
export * as V18 from "@rapiddocs-rapiddocs/ir-v18-model";
export * as V19 from "@rapiddocs-rapiddocs/ir-v19-model";
export * as V2 from "@rapiddocs-rapiddocs/ir-v2-model";
export * as V20 from "@rapiddocs-rapiddocs/ir-v20-model";
export * as V21 from "@rapiddocs-rapiddocs/ir-v21-model";
export * as V22 from "@rapiddocs-rapiddocs/ir-v22-model";
export { RapiddocsIrV23 as V23 } from "@rapiddocs-rapiddocs/ir-v23-sdk";
export { RapiddocsIrV24 as V24 } from "@rapiddocs-rapiddocs/ir-v24-sdk";
export { RapiddocsIrV25 as V25 } from "@rapiddocs-rapiddocs/ir-v25-sdk";
export { RapiddocsIrV26 as V26 } from "@rapiddocs-rapiddocs/ir-v26-sdk";
export { RapiddocsIrV27 as V27 } from "@rapiddocs-rapiddocs/ir-v27-sdk";
export { RapiddocsIrV28 as V28 } from "@rapiddocs-rapiddocs/ir-v28-sdk";
export { RapiddocsIrV29 as V29 } from "@rapiddocs-rapiddocs/ir-v29-sdk";
export * as V3 from "@rapiddocs-rapiddocs/ir-v3-model";
export { RapiddocsIrV30 as V30 } from "@rapiddocs-rapiddocs/ir-v30-sdk";
export { RapiddocsIrV31 as V31 } from "@rapiddocs-rapiddocs/ir-v31-sdk";
export { RapiddocsIrV32 as V32 } from "@rapiddocs-rapiddocs/ir-v32-sdk";
export { RapiddocsIrV33 as V33 } from "@rapiddocs-rapiddocs/ir-v33-sdk";
export { RapiddocsIrV34 as V34 } from "@rapiddocs-rapiddocs/ir-v34-sdk";
export { RapiddocsIrV35 as V35 } from "@rapiddocs-rapiddocs/ir-v35-sdk";
export { RapiddocsIrV36 as V36 } from "@rapiddocs-rapiddocs/ir-v36-sdk";
export { RapiddocsIrV37 as V37 } from "@rapiddocs-rapiddocs/ir-v37-sdk";
export { RapiddocsIrV38 as V38 } from "@rapiddocs-rapiddocs/ir-v38-sdk";
export { RapiddocsIrV39 as V39 } from "@rapiddocs-rapiddocs/ir-v39-sdk";
export * as V4 from "@rapiddocs-rapiddocs/ir-v4-model";
export { RapiddocsIrV40 as V40 } from "@rapiddocs-rapiddocs/ir-v40-sdk";
export { RapiddocsIrV41 as V41 } from "@rapiddocs-rapiddocs/ir-v41-sdk";
export { RapiddocsIrV42 as V42 } from "@rapiddocs-rapiddocs/ir-v42-sdk";
export { RapiddocsIrV43 as V43 } from "@rapiddocs-rapiddocs/ir-v43-sdk";
export { RapiddocsIrV44 as V44 } from "@rapiddocs-rapiddocs/ir-v44-sdk";
export { RapiddocsIrV45 as V45 } from "@rapiddocs-rapiddocs/ir-v45-sdk";
export { RapiddocsIrV46 as V46 } from "@rapiddocs-rapiddocs/ir-v46-sdk";
export { RapiddocsIrV47 as V47 } from "@rapiddocs-rapiddocs/ir-v47-sdk";
export { RapiddocsIrV48 as V48 } from "@rapiddocs-rapiddocs/ir-v48-sdk";
export { RapiddocsIrV49 as V49 } from "@rapiddocs-rapiddocs/ir-v49-sdk";
export * as V5 from "@rapiddocs-rapiddocs/ir-v5-model";
export { RapiddocsIrV50 as V50 } from "@rapiddocs-rapiddocs/ir-v50-sdk";
export { RapiddocsIrV51 as V51 } from "@rapiddocs-rapiddocs/ir-v51-sdk";
export { RapiddocsIrV52 as V52 } from "@rapiddocs-rapiddocs/ir-v52-sdk";
export { RapiddocsIrV53 as V53 } from "@rapiddocs-rapiddocs/ir-v53-sdk";
export { RapiddocsIrV54 as V54 } from "@rapiddocs-rapiddocs/ir-v54-sdk";
export { RapiddocsIrV55 as V55 } from "@rapiddocs-rapiddocs/ir-v55-sdk";
export { RapiddocsIrV56 as V56 } from "@rapiddocs-rapiddocs/ir-v56-sdk";
export * as V6 from "@rapiddocs-rapiddocs/ir-v6-model";
export * as V7 from "@rapiddocs-rapiddocs/ir-v7-model";
export * as V8 from "@rapiddocs-rapiddocs/ir-v8-model";
export * as V9 from "@rapiddocs-rapiddocs/ir-v9-model";
