/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const Base64Type: core.serialization.ObjectSchema<serializers.Base64Type.Raw, RapiddocsIr.Base64Type> =
    core.serialization.objectWithoutOptionalProperties({});

export declare namespace Base64Type {
    export interface Raw {}
}
