/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const BigIntegerType: core.serialization.ObjectSchema<serializers.BigIntegerType.Raw, RapiddocsIr.BigIntegerType> =
    core.serialization.objectWithoutOptionalProperties({
        default: core.serialization.string().optional(),
    });

export declare namespace BigIntegerType {
    export interface Raw {
        default?: string | null;
    }
}
