/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const BooleanType: core.serialization.ObjectSchema<serializers.BooleanType.Raw, RapiddocsIr.BooleanType> =
    core.serialization.objectWithoutOptionalProperties({
        default: core.serialization.boolean().optional(),
    });

export declare namespace BooleanType {
    export interface Raw {
        default?: boolean | null;
    }
}
