/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { JsonEncoding } from "./JsonEncoding";
import { ProtoEncoding } from "./ProtoEncoding";

export const Encoding: core.serialization.ObjectSchema<serializers.Encoding.Raw, RapiddocsIr.Encoding> =
    core.serialization.objectWithoutOptionalProperties({
        json: JsonEncoding.optional(),
        proto: ProtoEncoding.optional(),
    });

export declare namespace Encoding {
    export interface Raw {
        json?: JsonEncoding.Raw | null;
        proto?: ProtoEncoding.Raw | null;
    }
}
