/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { EnumValue } from "./EnumValue";
import { DeclaredTypeName } from "./DeclaredTypeName";

export const EnumTypeReference: core.serialization.ObjectSchema<
    serializers.EnumTypeReference.Raw,
    RapiddocsIr.EnumTypeReference
> = core.serialization.objectWithoutOptionalProperties({
    default: EnumValue.optional(),
    name: DeclaredTypeName,
});

export declare namespace EnumTypeReference {
    export interface Raw {
        default?: EnumValue.Raw | null;
        name: DeclaredTypeName.Raw;
    }
}
