/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { EnumValue } from "./EnumValue";

export const EnumTypeDeclaration: core.serialization.ObjectSchema<
    serializers.EnumTypeDeclaration.Raw,
    RapiddocsIr.EnumTypeDeclaration
> = core.serialization.objectWithoutOptionalProperties({
    default: EnumValue.optional(),
    values: core.serialization.list(EnumValue),
});

export declare namespace EnumTypeDeclaration {
    export interface Raw {
        default?: EnumValue.Raw | null;
        values: EnumValue.Raw[];
    }
}
