/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const ExampleKeyValuePair: core.serialization.ObjectSchema<
    serializers.ExampleKeyValuePair.Raw,
    RapiddocsIr.ExampleKeyValuePair
> = core.serialization.objectWithoutOptionalProperties({
    key: core.serialization.lazyObject(() => serializers.ExampleTypeReference),
    value: core.serialization.lazyObject(() => serializers.ExampleTypeReference),
});

export declare namespace ExampleKeyValuePair {
    export interface Raw {
        key: serializers.ExampleTypeReference.Raw;
        value: serializers.ExampleTypeReference.Raw;
    }
}
