/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const ExampleSetContainer: core.serialization.ObjectSchema<
    serializers.ExampleSetContainer.Raw,
    RapiddocsIr.ExampleSetContainer
> = core.serialization.objectWithoutOptionalProperties({
    set: core.serialization.list(core.serialization.lazyObject(() => serializers.ExampleTypeReference)),
    itemType: core.serialization.lazy(() => serializers.TypeReference),
});

export declare namespace ExampleSetContainer {
    export interface Raw {
        set: serializers.ExampleTypeReference.Raw[];
        itemType: serializers.TypeReference.Raw;
    }
}
