/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const ExampleNullableContainer: core.serialization.ObjectSchema<
    serializers.ExampleNullableContainer.Raw,
    RapiddocsIr.ExampleNullableContainer
> = core.serialization.objectWithoutOptionalProperties({
    nullable: core.serialization.lazyObject(() => serializers.ExampleTypeReference).optional(),
    valueType: core.serialization.lazy(() => serializers.TypeReference),
});

export declare namespace ExampleNullableContainer {
    export interface Raw {
        nullable?: serializers.ExampleTypeReference.Raw | null;
        valueType: serializers.TypeReference.Raw;
    }
}
