/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { TypeId } from "../../commons/types/TypeId";

export const ExampleObjectTypeWithTypeId: core.serialization.ObjectSchema<
    serializers.ExampleObjectTypeWithTypeId.Raw,
    RapiddocsIr.ExampleObjectTypeWithTypeId
> = core.serialization.objectWithoutOptionalProperties({
    typeId: TypeId,
    object: core.serialization.lazyObject(() => serializers.ExampleObjectType),
});

export declare namespace ExampleObjectTypeWithTypeId {
    export interface Raw {
        typeId: TypeId.Raw;
        object: serializers.ExampleObjectType.Raw;
    }
}
