/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { ExampleLiteralContainer } from "./ExampleLiteralContainer";

export const ExampleContainer: core.serialization.Schema<serializers.ExampleContainer.Raw, RapiddocsIr.ExampleContainer> =
    core.serialization
        .union("type", {
            list: core.serialization.lazyObject(() => serializers.ExampleListContainer),
            set: core.serialization.lazyObject(() => serializers.ExampleSetContainer),
            optional: core.serialization.lazyObject(() => serializers.ExampleOptionalContainer),
            nullable: core.serialization.lazyObject(() => serializers.ExampleNullableContainer),
            map: core.serialization.lazyObject(() => serializers.ExampleMapContainer),
            literal: ExampleLiteralContainer,
        })
        .transform<RapiddocsIr.ExampleContainer>({
            transform: (value) => {
                switch (value.type) {
                    case "list":
                        return RapiddocsIr.ExampleContainer.list(value);
                    case "set":
                        return RapiddocsIr.ExampleContainer.set(value);
                    case "optional":
                        return RapiddocsIr.ExampleContainer.optional(value);
                    case "nullable":
                        return RapiddocsIr.ExampleContainer.nullable(value);
                    case "map":
                        return RapiddocsIr.ExampleContainer.map(value);
                    case "literal":
                        return RapiddocsIr.ExampleContainer.literal(value);
                    default:
                        return value as RapiddocsIr.ExampleContainer;
                }
            },
            untransform: ({ _visit, ...value }) => value as any,
        });

export declare namespace ExampleContainer {
    export type Raw =
        | ExampleContainer.List
        | ExampleContainer.Set
        | ExampleContainer.Optional
        | ExampleContainer.Nullable
        | ExampleContainer.Map
        | ExampleContainer.Literal;

    export interface List extends serializers.ExampleListContainer.Raw {
        type: "list";
    }

    export interface Set extends serializers.ExampleSetContainer.Raw {
        type: "set";
    }

    export interface Optional extends serializers.ExampleOptionalContainer.Raw {
        type: "optional";
    }

    export interface Nullable extends serializers.ExampleNullableContainer.Raw {
        type: "nullable";
    }

    export interface Map extends serializers.ExampleMapContainer.Raw {
        type: "map";
    }

    export interface Literal extends ExampleLiteralContainer.Raw {
        type: "literal";
    }
}
