/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { NameAndWireValue } from "../../commons/types/NameAndWireValue";

export const ExampleUnionType: core.serialization.ObjectSchema<
    serializers.ExampleUnionType.Raw,
    RapiddocsIr.ExampleUnionType
> = core.serialization.objectWithoutOptionalProperties({
    discriminant: NameAndWireValue,
    singleUnionType: core.serialization.lazyObject(() => serializers.ExampleSingleUnionType),
});

export declare namespace ExampleUnionType {
    export interface Raw {
        discriminant: NameAndWireValue.Raw;
        singleUnionType: serializers.ExampleSingleUnionType.Raw;
    }
}
