/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const ExampleListContainer: core.serialization.ObjectSchema<
    serializers.ExampleListContainer.Raw,
    RapiddocsIr.ExampleListContainer
> = core.serialization.objectWithoutOptionalProperties({
    list: core.serialization.list(core.serialization.lazyObject(() => serializers.ExampleTypeReference)),
    itemType: core.serialization.lazy(() => serializers.TypeReference),
});

export declare namespace ExampleListContainer {
    export interface Raw {
        list: serializers.ExampleTypeReference.Raw[];
        itemType: serializers.TypeReference.Raw;
    }
}
