/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const LongType: core.serialization.ObjectSchema<serializers.LongType.Raw, RapiddocsIr.LongType> =
    core.serialization.objectWithoutOptionalProperties({
        default: core.serialization.number().optional(),
    });

export declare namespace LongType {
    export interface Raw {
        default?: number | null;
    }
}
