/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const ObjectPropertyAccess: core.serialization.Schema<
    serializers.ObjectPropertyAccess.Raw,
    RapiddocsIr.ObjectPropertyAccess
> = core.serialization.enum_(["READ_ONLY", "WRITE_ONLY"]);

export declare namespace ObjectPropertyAccess {
    export type Raw = "READ_ONLY" | "WRITE_ONLY";
}
