/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { ResolvedNamedType } from "./ResolvedNamedType";
import { PrimitiveType } from "./PrimitiveType";

export const ResolvedTypeReference: core.serialization.Schema<
    serializers.ResolvedTypeReference.Raw,
    RapiddocsIr.ResolvedTypeReference
> = core.serialization
    .union(core.serialization.discriminant("type", "_type"), {
        container: core.serialization.object({
            container: core.serialization.lazy(() => serializers.ContainerType),
        }),
        named: ResolvedNamedType,
        primitive: core.serialization.object({
            primitive: PrimitiveType,
        }),
        unknown: core.serialization.object({}),
    })
    .transform<RapiddocsIr.ResolvedTypeReference>({
        transform: (value) => {
            switch (value.type) {
                case "container":
                    return RapiddocsIr.ResolvedTypeReference.container(value.container);
                case "named":
                    return RapiddocsIr.ResolvedTypeReference.named(value);
                case "primitive":
                    return RapiddocsIr.ResolvedTypeReference.primitive(value.primitive);
                case "unknown":
                    return RapiddocsIr.ResolvedTypeReference.unknown();
                default:
                    return value as RapiddocsIr.ResolvedTypeReference;
            }
        },
        untransform: ({ _visit, ...value }) => value as any,
    });

export declare namespace ResolvedTypeReference {
    export type Raw =
        | ResolvedTypeReference.Container
        | ResolvedTypeReference.Named
        | ResolvedTypeReference.Primitive
        | ResolvedTypeReference.Unknown;

    export interface Container {
        _type: "container";
        container: serializers.ContainerType.Raw;
    }

    export interface Named extends ResolvedNamedType.Raw {
        _type: "named";
    }

    export interface Primitive {
        _type: "primitive";
        primitive: PrimitiveType.Raw;
    }

    export interface Unknown {
        _type: "unknown";
    }
}
