/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface BaseTypeDeclarationSchema
    extends RapiddocsDefinition.WithDocsSchema,
        RapiddocsDefinition.WithAvailability,
        RapiddocsDefinition.WithAudiences {
    examples?: RapiddocsDefinition.ExampleTypeSchema[];
    encoding?: RapiddocsDefinition.EncodingSchema;
    source?: RapiddocsDefinition.SourceSchema;
    inline?: boolean;
}
