/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface EnumValueSchema extends RapiddocsDefinition.WithDocsSchema, RapiddocsDefinition.WithName {
    value: string;
    casing?: RapiddocsDefinition.CasingOverridesSchema;
}
