/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export type ObjectPropertyAccess = "read-only" | "write-only";
export const ObjectPropertyAccess = {
    ReadOnly: "read-only",
    WriteOnly: "write-only",
} as const;
