/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface ObjectPropertyWithAccessSchema extends RapiddocsDefinition.TypeReferenceDeclarationWithName {
    access?: RapiddocsDefinition.ObjectPropertyAccess;
}
