/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export type TypeDeclarationSchema =
    | string
    | RapiddocsDefinition.ObjectSchema
    | RapiddocsDefinition.EnumSchema
    | RapiddocsDefinition.DiscriminatedUnionSchema
    | RapiddocsDefinition.UndiscriminatedUnionSchema
    | RapiddocsDefinition.AliasSchema;
