/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface TypeReferenceDeclarationWithName
    extends RapiddocsDefinition.BaseTypeReferenceSchema,
        RapiddocsDefinition.WithName,
        RapiddocsDefinition.WithAudiences {
    type: string;
}
