/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "Jennifer Lawrence",
 *         id: "actor_456"
 *     }
 */
export interface Actress {
    name: string;
    id: string;
}
