/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedExamples from "../../../index";

/**
 * @example
 *     {
 *         nodes: [{
 *                 name: "left"
 *             }, {
 *                 name: "right"
 *             }]
 *     }
 */
export interface Tree {
    nodes?: SeedExamples.Node[];
}
