# This file was auto-generated by Rapiddocs from our API Definition.

from __future__ import annotations
import typing

JsonLike = typing.Union[typing.List["JsonLike"], typing.Dict[str, "JsonLike"], str, int, bool]
