/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

package resources.errors.exceptions;

import core.APIException;

public final class BadRequest extends APIException {
  public static final int STATUS_CODE = 400;
}
