/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */
package com.seed.responseProperty.types;

import java.util.Map;

public interface IWithMetadata {
    Map<String, String> getMetadata();
}
