# This file was auto-generated by Rapiddocs from our API Definition.

from ......core.exceptions.rapiddocs_http_exception import RapiddocsHTTPException
from ..types.object_with_optional_field import ObjectWithOptionalField


class ObjectWithOptionalFieldError(RapiddocsHTTPException):
    def __init__(self, error: ObjectWithOptionalField):
        super().__init__(
            status_code=400, name="ObjectWithOptionalFieldError", content=error
        )
