/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export type WebSocketMessageBody = RapiddocsIr.WebSocketMessageBody.InlinedBody | RapiddocsIr.WebSocketMessageBody.Reference;

export namespace WebSocketMessageBody {
    export interface InlinedBody extends RapiddocsIr.InlinedWebSocketMessageBody, _Utils {
        type: "inlinedBody";
    }

    export interface Reference extends RapiddocsIr.WebSocketMessageBodyReference, _Utils {
        type: "reference";
    }

    export interface _Utils {
        _visit: <_Result>(visitor: RapiddocsIr.WebSocketMessageBody._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        inlinedBody: (value: RapiddocsIr.InlinedWebSocketMessageBody) => _Result;
        reference: (value: RapiddocsIr.WebSocketMessageBodyReference) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const WebSocketMessageBody = {
    inlinedBody: (value: RapiddocsIr.InlinedWebSocketMessageBody): RapiddocsIr.WebSocketMessageBody.InlinedBody => {
        return {
            ...value,
            type: "inlinedBody",
            _visit: function <_Result>(
                this: RapiddocsIr.WebSocketMessageBody.InlinedBody,
                visitor: RapiddocsIr.WebSocketMessageBody._Visitor<_Result>,
            ) {
                return RapiddocsIr.WebSocketMessageBody._visit(this, visitor);
            },
        };
    },

    reference: (value: RapiddocsIr.WebSocketMessageBodyReference): RapiddocsIr.WebSocketMessageBody.Reference => {
        return {
            ...value,
            type: "reference",
            _visit: function <_Result>(
                this: RapiddocsIr.WebSocketMessageBody.Reference,
                visitor: RapiddocsIr.WebSocketMessageBody._Visitor<_Result>,
            ) {
                return RapiddocsIr.WebSocketMessageBody._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: RapiddocsIr.WebSocketMessageBody,
        visitor: RapiddocsIr.WebSocketMessageBody._Visitor<_Result>,
    ): _Result => {
        switch (value.type) {
            case "inlinedBody":
                return visitor.inlinedBody(value);
            case "reference":
                return visitor.reference(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
