/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface WebSocketMessage extends RapiddocsIr.Declaration {
    type: RapiddocsIr.WebSocketMessageId;
    displayName: string | undefined;
    origin: RapiddocsIr.WebSocketMessageOrigin;
    body: RapiddocsIr.WebSocketMessageBody;
}
