/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../index";

export interface SinglyLinkedListValue {
    head?: SeedTrace.NodeId;
    nodes: Record<SeedTrace.NodeId, SeedTrace.SinglyLinkedListNodeValue>;
}
