# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/rapiddocs/main/rapiddocs.schema.json

imports:
  commons: commons.yml
types:
  EnvironmentId: string
  Environment:
    extends: commons.WithDocs
    properties:
      id: EnvironmentId
      name: commons.Name
      url: string
