/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { HttpInlineFileRequestBodyPropertySchema } from "./HttpInlineFileRequestBodyPropertySchema";

export const HttpInlineRequestBodyPropertySchema: core.serialization.Schema<
    serializers.HttpInlineRequestBodyPropertySchema.Raw,
    RapiddocsDefinition.HttpInlineRequestBodyPropertySchema
> = core.serialization.undiscriminatedUnion([core.serialization.string(), HttpInlineFileRequestBodyPropertySchema]);

export declare namespace HttpInlineRequestBodyPropertySchema {
    export type Raw = string | HttpInlineFileRequestBodyPropertySchema.Raw;
}
