/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";

export const HttpMethodSchema: core.serialization.Schema<
    serializers.HttpMethodSchema.Raw,
    RapiddocsDefinition.HttpMethodSchema
> = core.serialization.enum_(["GET", "POST", "PUT", "PATCH", "DELETE"]);

export declare namespace HttpMethodSchema {
    export type Raw = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
}
