/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { GrpcTransport } from "./GrpcTransport";

export const ServiceTransport: core.serialization.ObjectSchema<
    serializers.ServiceTransport.Raw,
    RapiddocsDefinition.ServiceTransport
> = core.serialization.object({
    grpc: GrpcTransport.optional(),
});

export declare namespace ServiceTransport {
    export interface Raw {
        grpc?: GrpcTransport.Raw | null;
    }
}
