/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../../../index";

export interface WithHeadersSchema {
    /** Global Headers for the entire API */
    headers?: Record<string, RapiddocsDefinition.rapiddocsDefinition.HttpHeaderSchema>;
}
