/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface VariableReferenceSchema extends RapiddocsDefinition.WithAvailability, RapiddocsDefinition.WithDocsSchema {
    variable: string;
}
