/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */
export declare type MyEnum = "one" | "two" | "three" | "four";
export declare const MyEnum: {
    readonly One: "one";
    readonly Two: "two";
    readonly Three: "three";
    readonly Four: "four";
};
