openapi: 3.0.1
info:
  title: no-environment
  version: ''
paths:
  /dummy:
    get:
      operationId: dummy_getDummy
      tags:
        - Dummy
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
      security:
        - BearerAuth: []
components:
  schemas: {}
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
