/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export const SeedExamplesEnvironment = {
    Production: "https://production.com/api",
    Staging: "https://staging.com/api",
} as const;

export type SeedExamplesEnvironment =
    | typeof SeedExamplesEnvironment.Production
    | typeof SeedExamplesEnvironment.Staging;
