openapi: 3.0.1
info:
  title: error-property
  version: ''
paths:
  /property-based-error:
    get:
      description: GET request that always throws an error
      operationId: propertyBasedError_ThrowError
      tags:
        - PropertyBasedError
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
        '400':
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      errorName:
                        type: string
                        enum:
                          - PropertyBasedErrorTest
                      content:
                        $ref: '#/components/schemas/PropertyBasedErrorTestBody'
components:
  schemas:
    PropertyBasedErrorTestBody:
      title: PropertyBasedErrorTestBody
      type: object
      properties:
        message:
          type: string
      required:
        - message
  securitySchemes: {}
