/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

/**
 * @example
 *     {
 *         body: "string"
 *     }
 */
export interface ModifyResourceAtInlinedPath {
    body: string;
}
