/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { ErrorId } from "../../commons/types/ErrorId";
import { RapiddocsFilepath } from "../../commons/types/RapiddocsFilepath";
import { Name } from "../../commons/types/Name";

export const DeclaredErrorName: core.serialization.ObjectSchema<
    serializers.DeclaredErrorName.Raw,
    RapiddocsIr.DeclaredErrorName
> = core.serialization.objectWithoutOptionalProperties({
    errorId: ErrorId,
    rapiddocsFilepath: RapiddocsFilepath,
    name: Name,
});

export declare namespace DeclaredErrorName {
    export interface Raw {
        errorId: ErrorId.Raw;
        rapiddocsFilepath: RapiddocsFilepath.Raw;
        name: Name.Raw;
    }
}
