/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export type BasicType = "primitive" | "literal";
export const BasicType = {
    Primitive: "primitive",
    Literal: "literal",
} as const;
