/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../../../index";

export interface BaseTypeReferenceSchema
    extends RapiddocsDefinition.rapiddocsDefinition.WithDocsSchema,
        RapiddocsDefinition.rapiddocsDefinition.WithAvailability {
    default?: unknown;
    encoding?: RapiddocsDefinition.rapiddocsDefinition.EncodingSchema;
    validation?: RapiddocsDefinition.rapiddocsDefinition.ValidationSchema;
}
