/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../../../index";

export interface FunctionImplementationForMultipleLanguages {
    codeByLanguage: Record<SeedTrace.Language, SeedTrace.v2.FunctionImplementation | undefined>;
}
