/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../../../index";

export interface TestCaseWithActualResultImplementation {
    getActualResult: SeedTrace.v2.NonVoidFunctionDefinition;
    assertCorrectnessCheck: SeedTrace.v2.AssertCorrectnessCheck;
}
