/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../../../index";

export interface VoidFunctionDefinition {
    parameters: SeedTrace.v2.Parameter[];
    code: SeedTrace.v2.FunctionImplementationForMultipleLanguages;
}
