/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedExamples from "../index";

export interface Identifier {
    type: SeedExamples.Type;
    value: string;
    label: string;
}
