// This file was auto-generated by Rapiddocs from our API Definition.

package client

import (
	complex "github.com/pagination/rapiddocs/complex"
	core "github.com/pagination/rapiddocs/core"
	internal "github.com/pagination/rapiddocs/internal"
	option "github.com/pagination/rapiddocs/option"
	users "github.com/pagination/rapiddocs/users"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Complex *complex.Client
	Users   *users.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:  options.ToHeader(),
		Complex: complex.NewClient(opts...),
		Users:   users.NewClient(opts...),
	}
}
