/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

/**
 * Several different types are accepted.
 */
export type MyUnion = string | string[] | number | number[] | number[][] | Set<string>;
