/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../index";

export interface WorkspaceStarterFilesResponseV2 {
    filesByLanguage: Record<SeedTrace.Language, SeedTrace.v2.Files | undefined>;
}
