/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../index";

export interface GetDefaultStarterFilesResponse {
    files: Record<SeedTrace.Language, SeedTrace.ProblemFiles | undefined>;
}
