/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsDefinition from "../../../../api/index";
import * as core from "../../../../core";
import { WithAudiences } from "../../commons/types/WithAudiences";
import { WithDocsSchema } from "../../commons/types/WithDocsSchema";

export const SingleBaseUrlEnvironmentSchema: core.serialization.ObjectSchema<
    serializers.SingleBaseUrlEnvironmentSchema.Raw,
    RapiddocsDefinition.SingleBaseUrlEnvironmentSchema
> = core.serialization
    .object({
        url: core.serialization.string(),
    })
    .extend(WithAudiences)
    .extend(WithDocsSchema);

export declare namespace SingleBaseUrlEnvironmentSchema {
    export interface Raw extends WithAudiences.Raw, WithDocsSchema.Raw {
        url: string;
    }
}
