/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsIr from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { Name } from "../../../../commons/types/Name";

export const BearerAuth: core.serialization.ObjectSchema<
    serializers.dynamic.BearerAuth.Raw,
    RapiddocsIr.dynamic.BearerAuth
> = core.serialization.objectWithoutOptionalProperties({
    token: Name,
});

export declare namespace BearerAuth {
    export interface Raw {
        token: Name.Raw;
    }
}
