/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsIr from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const OAuthValues: core.serialization.ObjectSchema<
    serializers.dynamic.OAuthValues.Raw,
    RapiddocsIr.dynamic.OAuthValues
> = core.serialization.objectWithoutOptionalProperties({
    clientId: core.serialization.string(),
    clientSecret: core.serialization.string(),
});

export declare namespace OAuthValues {
    export interface Raw {
        clientId: string;
        clientSecret: string;
    }
}
