/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as RapiddocsIr from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { Name } from "../../../../commons/types/Name";

export const OAuth: core.serialization.ObjectSchema<serializers.dynamic.OAuth.Raw, RapiddocsIr.dynamic.OAuth> =
    core.serialization.objectWithoutOptionalProperties({
        clientId: Name,
        clientSecret: Name,
    });

export declare namespace OAuth {
    export interface Raw {
        clientId: Name.Raw;
        clientSecret: Name.Raw;
    }
}
