/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsSeedConfig from "../../../index";

/**
 * Configuration for publishing from a command, assuming something packaged up, like with the TypeScript generator.
 * ex. `pnpm --filter @rapiddocs-typescript/express-generator-cli dockerTagVersion "$VERSION"`
 * Commands can be multi-line, we'll run them all!
 */
export interface PublishCommand {
    workingDirectory?: string;
    /** The string to substitute for the version in the command. ex. `"$VERSION"` */
    versionSubstitution?: string;
    command: RapiddocsSeedConfig.DockerCommand;
}
