/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsSeedConfig from "../../../index";

export type ReadmeEndpoint = string | RapiddocsSeedConfig.ReadmeEndpointObject;
