/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsSeedConfig from "../../../index";

export interface SeedWorkspaceConfiguration {
    image: string;
    displayName: string;
    irVersion: string;
    test: RapiddocsSeedConfig.TestConfiguration;
    publish: RapiddocsSeedConfig.PublishConfiguration;
    /** The location of the changelog file, the schema of which must follow FDR's `GeneratorReleaseRequest` object. */
    changelogLocation?: string;
    language?: RapiddocsSeedConfig.Language;
    defaultCustomConfig?: Record<string, unknown>;
    defaultOutputMode: RapiddocsSeedConfig.OutputMode;
    generatorType: RapiddocsSeedConfig.GeneratorType;
    buildScripts?: RapiddocsSeedConfig.BuildScripts;
    /** Configuration that will be used for any custom fixture specified by --custom-fixture */
    customFixtureConfig?: RapiddocsSeedConfig.FixtureConfigurations;
    fixtures?: Record<string, RapiddocsSeedConfig.FixtureConfigurations[]>;
    scripts?: RapiddocsSeedConfig.DockerScriptConfig[];
    /**
     * List any fixtures that are okay to fail. For normal fixtures
     * just list the fixture name. For configured fixture list {fixture}:{outputFolder}.
     */
    allowedFailures?: string[];
    features?: RapiddocsSeedConfig.GeneratorFeatures;
}
