/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsSeedConfig from "../../../index";

export interface TestConfiguration {
    docker: RapiddocsSeedConfig.TestDockerConfiguration;
    local?: RapiddocsSeedConfig.LocalBuildInfo;
}
