# This file was auto-generated by Rapiddocs from our API Definition.

from . import dataservice
from .dataservice import (
    DeleteRequest,
    DescribeRequest,
    QueryRequest,
    UpdateRequest,
    UploadRequest,
)

__all__ = [
    "DeleteRequest",
    "DescribeRequest",
    "QueryRequest",
    "UpdateRequest",
    "UploadRequest",
    "dataservice",
]
