# This file was auto-generated by Rapiddocs from our API Definition.

import typing
from .key import Key

"""
from seed.undiscriminated_unions.resources.union import KeyType

{KeyType.NAME: "exampleName", KeyType.VALUE: "exampleValue"}
"""
Metadata = typing.Dict[Key, str]
