# This file was auto-generated by Rapiddocs from our API Definition.

import typing

MyUnion = typing.Union[
    str,
    typing.List[str],
    int,
    typing.List[int],
    typing.List[typing.List[int]],
    typing.Set[str],
]
