/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export class RapiddocsDefinitionTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, RapiddocsDefinitionTimeoutError.prototype);
    }
}
