/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";
import { SchemaId } from "../../commons/types/SchemaId";

export const AllOfPropertyConflict: core.serialization.ObjectSchema<
    serializers.AllOfPropertyConflict.Raw,
    RapiddocsOpenapiIr.AllOfPropertyConflict
> = core.serialization.objectWithoutOptionalProperties({
    propertyKey: core.serialization.string(),
    allOfSchemaIds: core.serialization.list(SchemaId),
    conflictingTypeSignatures: core.serialization.boolean(),
});

export declare namespace AllOfPropertyConflict {
    export interface Raw {
        propertyKey: string;
        allOfSchemaIds: SchemaId.Raw[];
        conflictingTypeSignatures: boolean;
    }
}
