/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";

export const CasingOverrides: core.serialization.ObjectSchema<
    serializers.CasingOverrides.Raw,
    RapiddocsOpenapiIr.CasingOverrides
> = core.serialization.objectWithoutOptionalProperties({
    snake: core.serialization.string().optional(),
    camel: core.serialization.string().optional(),
    screamingSnake: core.serialization.string().optional(),
    pascal: core.serialization.string().optional(),
});

export declare namespace CasingOverrides {
    export interface Raw {
        snake?: string | null;
        camel?: string | null;
        screamingSnake?: string | null;
        pascal?: string | null;
    }
}
