/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";

export const CustomPagination: core.serialization.ObjectSchema<
    serializers.CustomPagination.Raw,
    RapiddocsOpenapiIr.CustomPagination
> = core.serialization.objectWithoutOptionalProperties({
    results: core.serialization.string(),
});

export declare namespace CustomPagination {
    export interface Raw {
        results: string;
    }
}
