/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";

export const DoubleSchema: core.serialization.ObjectSchema<serializers.DoubleSchema.Raw, RapiddocsOpenapiIr.DoubleSchema> =
    core.serialization.objectWithoutOptionalProperties({
        default: core.serialization.number().optional(),
        minimum: core.serialization.number().optional(),
        maximum: core.serialization.number().optional(),
        exclusiveMinimum: core.serialization.boolean().optional(),
        exclusiveMaximum: core.serialization.boolean().optional(),
        multipleOf: core.serialization.number().optional(),
    });

export declare namespace DoubleSchema {
    export interface Raw {
        default?: number | null;
        minimum?: number | null;
        maximum?: number | null;
        exclusiveMinimum?: boolean | null;
        exclusiveMaximum?: boolean | null;
        multipleOf?: number | null;
    }
}
