/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";
import { SdkGroupName } from "../../commons/types/SdkGroupName";
import { SdkGroup } from "../../commons/types/SdkGroup";

export const EndpointSdkName: core.serialization.ObjectSchema<
    serializers.EndpointSdkName.Raw,
    RapiddocsOpenapiIr.EndpointSdkName
> = core.serialization.objectWithoutOptionalProperties({
    groupName: SdkGroupName,
    methodName: core.serialization.string(),
});

export declare namespace EndpointSdkName {
    export interface Raw {
        groupName: SdkGroupName.Raw;
        methodName: string;
    }
}
