/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";
import { WithDescription } from "../../commons/types/WithDescription";

export const FileSchema: core.serialization.ObjectSchema<serializers.FileSchema.Raw, RapiddocsOpenapiIr.FileSchema> =
    core.serialization
        .objectWithoutOptionalProperties({
            isOptional: core.serialization.boolean(),
            isArray: core.serialization.boolean(),
        })
        .extend(WithDescription);

export declare namespace FileSchema {
    export interface Raw extends WithDescription.Raw {
        isOptional: boolean;
        isArray: boolean;
    }
}
