/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";

export const HttpMethod: core.serialization.Schema<serializers.HttpMethod.Raw, RapiddocsOpenapiIr.HttpMethod> =
    core.serialization.enum_(["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS", "TRACE"]);

export declare namespace HttpMethod {
    export type Raw = "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS" | "TRACE";
}
