/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";
import { MultipartRequestProperty } from "./MultipartRequestProperty";
import { WithDescription } from "../../commons/types/WithDescription";
import { WithSource } from "../../commons/types/WithSource";

export const MultipartRequest: core.serialization.ObjectSchema<
    serializers.MultipartRequest.Raw,
    RapiddocsOpenapiIr.MultipartRequest
> = core.serialization
    .objectWithoutOptionalProperties({
        name: core.serialization.string().optional(),
        properties: core.serialization.list(MultipartRequestProperty),
    })
    .extend(WithDescription)
    .extend(WithSource);

export declare namespace MultipartRequest {
    export interface Raw extends WithDescription.Raw, WithSource.Raw {
        name?: string | null;
        properties: MultipartRequestProperty.Raw[];
    }
}
