/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";

export const ObjectPropertyConflictInfo: core.serialization.ObjectSchema<
    serializers.ObjectPropertyConflictInfo.Raw,
    RapiddocsOpenapiIr.ObjectPropertyConflictInfo
> = core.serialization.objectWithoutOptionalProperties({
    differentSchema: core.serialization.boolean(),
});

export declare namespace ObjectPropertyConflictInfo {
    export interface Raw {
        differentSchema: boolean;
    }
}
