/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";
import { CursorPagination } from "./CursorPagination";
import { OffsetPagination } from "./OffsetPagination";
import { CustomPagination } from "./CustomPagination";

export const Pagination: core.serialization.Schema<serializers.Pagination.Raw, RapiddocsOpenapiIr.Pagination> =
    core.serialization
        .union("type", {
            cursor: CursorPagination,
            offset: OffsetPagination,
            custom: CustomPagination,
        })
        .transform<RapiddocsOpenapiIr.Pagination>({
            transform: (value) => {
                switch (value.type) {
                    case "cursor":
                        return RapiddocsOpenapiIr.Pagination.cursor(value);
                    case "offset":
                        return RapiddocsOpenapiIr.Pagination.offset(value);
                    case "custom":
                        return RapiddocsOpenapiIr.Pagination.custom(value);
                    default:
                        return value as RapiddocsOpenapiIr.Pagination;
                }
            },
            untransform: ({ _visit, ...value }) => value as any,
        });

export declare namespace Pagination {
    export type Raw = Pagination.Cursor | Pagination.Offset | Pagination.Custom;

    export interface Cursor extends CursorPagination.Raw {
        type: "cursor";
    }

    export interface Offset extends OffsetPagination.Raw {
        type: "offset";
    }

    export interface Custom extends CustomPagination.Raw {
        type: "custom";
    }
}
