/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";
import { IntSchema } from "./IntSchema";
import { LongSchema } from "./LongSchema";
import { DoubleSchema } from "./DoubleSchema";
import { StringSchema } from "./StringSchema";
import { BooleanSchema } from "./BooleanSchema";

export const PrimitiveSchemaValue: core.serialization.Schema<
    serializers.PrimitiveSchemaValue.Raw,
    RapiddocsOpenapiIr.PrimitiveSchemaValue
> = core.serialization
    .union("type", {
        int: IntSchema,
        int64: LongSchema,
        uint: core.serialization.object({}),
        uint64: core.serialization.object({}),
        float: core.serialization.object({}),
        double: DoubleSchema,
        string: StringSchema,
        datetime: core.serialization.object({}),
        date: core.serialization.object({}),
        base64: core.serialization.object({}),
        boolean: BooleanSchema,
    })
    .transform<RapiddocsOpenapiIr.PrimitiveSchemaValue>({
        transform: (value) => {
            switch (value.type) {
                case "int":
                    return RapiddocsOpenapiIr.PrimitiveSchemaValue.int(value);
                case "int64":
                    return RapiddocsOpenapiIr.PrimitiveSchemaValue.int64(value);
                case "uint":
                    return RapiddocsOpenapiIr.PrimitiveSchemaValue.uint();
                case "uint64":
                    return RapiddocsOpenapiIr.PrimitiveSchemaValue.uint64();
                case "float":
                    return RapiddocsOpenapiIr.PrimitiveSchemaValue.float();
                case "double":
                    return RapiddocsOpenapiIr.PrimitiveSchemaValue.double(value);
                case "string":
                    return RapiddocsOpenapiIr.PrimitiveSchemaValue.string(value);
                case "datetime":
                    return RapiddocsOpenapiIr.PrimitiveSchemaValue.datetime();
                case "date":
                    return RapiddocsOpenapiIr.PrimitiveSchemaValue.date();
                case "base64":
                    return RapiddocsOpenapiIr.PrimitiveSchemaValue.base64();
                case "boolean":
                    return RapiddocsOpenapiIr.PrimitiveSchemaValue.boolean(value);
                default:
                    return value as RapiddocsOpenapiIr.PrimitiveSchemaValue;
            }
        },
        untransform: ({ _visit, ...value }) => value as any,
    });

export declare namespace PrimitiveSchemaValue {
    export type Raw =
        | PrimitiveSchemaValue.Int
        | PrimitiveSchemaValue.Int64
        | PrimitiveSchemaValue.Uint
        | PrimitiveSchemaValue.Uint64
        | PrimitiveSchemaValue.Float
        | PrimitiveSchemaValue.Double
        | PrimitiveSchemaValue.String
        | PrimitiveSchemaValue.Datetime
        | PrimitiveSchemaValue.Date
        | PrimitiveSchemaValue.Base64
        | PrimitiveSchemaValue.Boolean;

    export interface Int extends IntSchema.Raw {
        type: "int";
    }

    export interface Int64 extends LongSchema.Raw {
        type: "int64";
    }

    export interface Uint {
        type: "uint";
    }

    export interface Uint64 {
        type: "uint64";
    }

    export interface Float {
        type: "float";
    }

    export interface Double extends DoubleSchema.Raw {
        type: "double";
    }

    export interface String extends StringSchema.Raw {
        type: "string";
    }

    export interface Datetime {
        type: "datetime";
    }

    export interface Date {
        type: "date";
    }

    export interface Base64 {
        type: "base64";
    }

    export interface Boolean extends BooleanSchema.Raw {
        type: "boolean";
    }
}
