/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";

export const QueryParameterExample: core.serialization.ObjectSchema<
    serializers.QueryParameterExample.Raw,
    RapiddocsOpenapiIr.QueryParameterExample
> = core.serialization.objectWithoutOptionalProperties({
    name: core.serialization.string(),
    value: core.serialization.lazy(() => serializers.FullExample),
});

export declare namespace QueryParameterExample {
    export interface Raw {
        name: string;
        value: serializers.FullExample.Raw;
    }
}
