/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";
import { OctetStreamRequest } from "./OctetStreamRequest";
import { MultipartRequest } from "./MultipartRequest";
import { JsonRequest } from "./JsonRequest";

export const Request: core.serialization.Schema<serializers.Request.Raw, RapiddocsOpenapiIr.Request> = core.serialization
    .union("type", {
        octetStream: OctetStreamRequest,
        multipart: MultipartRequest,
        json: JsonRequest,
    })
    .transform<RapiddocsOpenapiIr.Request>({
        transform: (value) => {
            switch (value.type) {
                case "octetStream":
                    return RapiddocsOpenapiIr.Request.octetStream(value);
                case "multipart":
                    return RapiddocsOpenapiIr.Request.multipart(value);
                case "json":
                    return RapiddocsOpenapiIr.Request.json(value);
                default:
                    return value as RapiddocsOpenapiIr.Request;
            }
        },
        untransform: ({ _visit, ...value }) => value as any,
    });

export declare namespace Request {
    export type Raw = Request.OctetStream | Request.Multipart | Request.Json;

    export interface OctetStream extends OctetStreamRequest.Raw {
        type: "octetStream";
    }

    export interface Multipart extends MultipartRequest.Raw {
        type: "multipart";
    }

    export interface Json extends JsonRequest.Raw {
        type: "json";
    }
}
