/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";
import { WithDescription } from "../../commons/types/WithDescription";
import { WithSource } from "../../commons/types/WithSource";
import { WithStatusCode } from "../../commons/types/WithStatusCode";

export const TextResponse: core.serialization.ObjectSchema<serializers.TextResponse.Raw, RapiddocsOpenapiIr.TextResponse> =
    core.serialization
        .objectWithoutOptionalProperties({})
        .extend(WithDescription)
        .extend(WithSource)
        .extend(WithStatusCode);

export declare namespace TextResponse {
    export interface Raw extends WithDescription.Raw, WithSource.Raw, WithStatusCode.Raw {}
}
