/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";

export const WebhookHttpMethod: core.serialization.Schema<
    serializers.WebhookHttpMethod.Raw,
    RapiddocsOpenapiIr.WebhookHttpMethod
> = core.serialization.enum_(["GET", "POST"]);

export declare namespace WebhookHttpMethod {
    export type Raw = "GET" | "POST";
}
