/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsOpenapiIr from "../../../../api/index";
import * as core from "../../../../core";
import { QueryParameter } from "./QueryParameter";
import { Header } from "./Header";
import { PathParameter } from "./PathParameter";

export const WebsocketHandshake: core.serialization.ObjectSchema<
    serializers.WebsocketHandshake.Raw,
    RapiddocsOpenapiIr.WebsocketHandshake
> = core.serialization.objectWithoutOptionalProperties({
    queryParameters: core.serialization.list(QueryParameter),
    headers: core.serialization.list(Header),
    pathParameters: core.serialization.list(PathParameter),
});

export declare namespace WebsocketHandshake {
    export interface Raw {
        queryParameters: QueryParameter.Raw[];
        headers: Header.Raw[];
        pathParameters: PathParameter.Raw[];
    }
}
