/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../index";

export interface DoublyLinkedListValue {
    head?: SeedTrace.NodeId;
    nodes: Record<SeedTrace.NodeId, SeedTrace.DoublyLinkedListNodeValue>;
}
