/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../index";

export interface KeyValuePair {
    key: SeedTrace.VariableValue;
    value: SeedTrace.VariableValue;
}
