/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsIr from "../../../index";

export interface ErrorDeclaration extends RapiddocsIr.WithDocs {
    name: RapiddocsIr.DeclaredErrorName;
    discriminantValue: RapiddocsIr.NameAndWireValue;
    type: RapiddocsIr.TypeReference | undefined;
    statusCode: number;
    examples: RapiddocsIr.ExampleError[];
}
