/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export class SeedBytesTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, SeedBytesTimeoutError.prototype);
    }
}
