/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

package types;

import java.lang.String;
import java.util.List;

public interface IBaseResource {
  String getId();

  List<ResourceList> getRelatedResources();

  Memo getMemo();
}
