/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../index";

export type PlaylistIdNotFoundErrorBody = SeedTrace.PlaylistIdNotFoundErrorBody.PlaylistId;

export namespace PlaylistIdNotFoundErrorBody {
    export interface PlaylistId {
        type: "playlistId";
        value: SeedTrace.PlaylistId;
    }
}
