/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

export type FormDataBodyEncodingStyle = "json" | "exploded" | "form";
export const FormDataBodyEncodingStyle = {
    Json: "json",
    Exploded: "exploded",
    Form: "form",
} as const;
