/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface HttpResponseSchemaDetailed extends RapiddocsDefinition.WithDocsSchema {
    type?: string;
    property?: string;
    "status-code"?: number;
}
