/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const AuthSchemesRequirement: core.serialization.Schema<
    serializers.AuthSchemesRequirement.Raw,
    RapiddocsIr.AuthSchemesRequirement
> = core.serialization.enum_(["ALL", "ANY"]);

export declare namespace AuthSchemesRequirement {
    export type Raw = "ALL" | "ANY";
}
