/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { OAuthClientCredentials } from "./OAuthClientCredentials";

export const OAuthConfiguration: core.serialization.Schema<
    serializers.OAuthConfiguration.Raw,
    RapiddocsIr.OAuthConfiguration
> = core.serialization
    .union("type", {
        clientCredentials: OAuthClientCredentials,
    })
    .transform<RapiddocsIr.OAuthConfiguration>({
        transform: (value) => {
            switch (value.type) {
                case "clientCredentials":
                    return RapiddocsIr.OAuthConfiguration.clientCredentials(value);
                default:
                    return value as RapiddocsIr.OAuthConfiguration;
            }
        },
        untransform: ({ _visit, ...value }) => value as any,
    });

export declare namespace OAuthConfiguration {
    export type Raw = OAuthConfiguration.ClientCredentials;

    export interface ClientCredentials extends OAuthClientCredentials.Raw {
        type: "clientCredentials";
    }
}
