/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { RequestProperty } from "../../http/types/RequestProperty";

export const OAuthRefreshTokenRequestProperties: core.serialization.ObjectSchema<
    serializers.OAuthRefreshTokenRequestProperties.Raw,
    RapiddocsIr.OAuthRefreshTokenRequestProperties
> = core.serialization.objectWithoutOptionalProperties({
    refreshToken: RequestProperty,
});

export declare namespace OAuthRefreshTokenRequestProperties {
    export interface Raw {
        refreshToken: RequestProperty.Raw;
    }
}
