/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedApi from "../index";

export interface DescribeResponse {
    namespaces?: Record<string, SeedApi.NamespaceSummary>;
    dimension?: number;
    fullness?: number;
    totalCount?: number;
}
