/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { AvailabilityStatus } from "./AvailabilityStatus";

export const Availability: core.serialization.ObjectSchema<serializers.Availability.Raw, RapiddocsIr.Availability> =
    core.serialization.objectWithoutOptionalProperties({
        status: AvailabilityStatus,
        message: core.serialization.string().optional(),
    });

export declare namespace Availability {
    export interface Raw {
        status: AvailabilityStatus.Raw;
        message?: string | null;
    }
}
