/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { Availability } from "./Availability";
import { WithDocs } from "./WithDocs";

export const Declaration: core.serialization.ObjectSchema<serializers.Declaration.Raw, RapiddocsIr.Declaration> =
    core.serialization
        .objectWithoutOptionalProperties({
            availability: Availability.optional(),
        })
        .extend(WithDocs);

export declare namespace Declaration {
    export interface Raw extends WithDocs.Raw {
        availability?: Availability.Raw | null;
    }
}
