/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const EndpointId: core.serialization.Schema<serializers.EndpointId.Raw, RapiddocsIr.EndpointId> =
    core.serialization.string();

export declare namespace EndpointId {
    export type Raw = string;
}
