/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const ErrorId: core.serialization.Schema<serializers.ErrorId.Raw, RapiddocsIr.ErrorId> = core.serialization.string();

export declare namespace ErrorId {
    export type Raw = string;
}
