/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const FeatureId: core.serialization.Schema<serializers.FeatureId.Raw, RapiddocsIr.FeatureId> =
    core.serialization.string();

export declare namespace FeatureId {
    export type Raw = string;
}
