/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";
import { Name } from "./Name";

export const NameAndWireValue: core.serialization.ObjectSchema<
    serializers.NameAndWireValue.Raw,
    RapiddocsIr.NameAndWireValue
> = core.serialization.objectWithoutOptionalProperties({
    wireValue: core.serialization.string(),
    name: Name,
});

export declare namespace NameAndWireValue {
    export interface Raw {
        wireValue: string;
        name: Name.Raw;
    }
}
