/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const SubpackageId: core.serialization.Schema<serializers.SubpackageId.Raw, RapiddocsIr.SubpackageId> =
    core.serialization.string();

export declare namespace SubpackageId {
    export type Raw = string;
}
