/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsIr from "../../../../api/index";
import * as core from "../../../../core";

export const WebhookId: core.serialization.Schema<serializers.WebhookId.Raw, RapiddocsIr.WebhookId> =
    core.serialization.string();

export declare namespace WebhookId {
    export type Raw = string;
}
