/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedApi from "../index";

export interface UserModel {
    username?: string;
    email?: string;
    age?: number;
    weight?: number;
    metadata?: SeedApi.Metadata;
}
