/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as RapiddocsDefinition from "../../../index";

export interface AvailabilitySchema {
    status: RapiddocsDefinition.AvailabilityStatusSchema;
    message?: string;
}
