// This file was auto-generated by Rapiddocs from our API Definition.

package api

import (
	json "encoding/json"
)

type UploadRequest struct {
	Status string `json:"status" url:"-"`
	rapiddocs   string
}

func (u *UploadRequest) Rapiddocs() string {
	return u.rapiddocs
}

func (u *UploadRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UploadRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UploadRequest(body)
	u.rapiddocs = "rapiddocs"
	return nil
}

func (u *UploadRequest) MarshalJSON() ([]byte, error) {
	type embed UploadRequest
	var marshaler = struct {
		embed
		Rapiddocs string `json:"rapiddocs"`
	}{
		embed: embed(*u),
		Rapiddocs:  "rapiddocs",
	}
	return json.Marshal(marshaler)
}

type UploadMultiRequest struct {
	Status string `json:"status" url:"-"`
}
