/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as SeedTrace from "../../../../../index";

export interface NonVoidFunctionSignature {
    parameters: SeedTrace.v2.Parameter[];
    returnType: SeedTrace.VariableType;
}
