/**
 * This file was auto-generated by Rapiddocs from our API Definition.
 */

import * as serializers from "../../../index";
import * as RapiddocsConjure from "../../../../api/index";
import * as core from "../../../../core";
import { ConjureDefinitions } from "./ConjureDefinitions";

export const ConjureTypes: core.serialization.ObjectSchema<serializers.ConjureTypes.Raw, RapiddocsConjure.ConjureTypes> =
    core.serialization.objectWithoutOptionalProperties({
        conjureImports: core.serialization.property(
            "conjure-imports",
            core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
        ),
        definitions: ConjureDefinitions.optional(),
    });

export declare namespace ConjureTypes {
    export interface Raw {
        "conjure-imports"?: Record<string, string> | null;
        definitions?: ConjureDefinitions.Raw | null;
    }
}
