name: Release IR SDKs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/ir-sdk/rapiddocs/apis/ir-types-latest/VERSION"

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rapiddocs
        run: npm install -g khulnasoft

      - name: Release SDKs
        env:
          RAPIDDOCS_TOKEN: ${{ secrets.RAPIDDOCS_TOKEN }}
        run: |
          cd packages/ir-sdk
          version=$(cat rapiddocs/apis/ir-types-latest/VERSION)
          rapiddocs generate --api ir-types-latest --group node --version $version

  dynamic-ir:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rapiddocs
        run: npm install -g khulnasoft

      - name: Release SDKs
        env:
          RAPIDDOCS_TOKEN: ${{ secrets.RAPIDDOCS_TOKEN }}
          NPM_TOKEN: ${{ secrets.RAPIDDOCS_NPM_TOKEN }}
        run: |
          cd packages/ir-sdk
          version=$(cat rapiddocs/apis/ir-types-latest/VERSION)
          rapiddocs generate --api ir-types-latest --group dynamic-ir --version $version
  
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rapiddocs
        run: npm install -g khulnasoft

      - name: Release SDKs
        env:
          RAPIDDOCS_TOKEN: ${{ secrets.RAPIDDOCS_TOKEN }}
        run: |
          cd packages/ir-sdk
          version=$(cat rapiddocs/apis/ir-types-latest/VERSION)
          rapiddocs generate --api ir-types-latest --group python --version $version

  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rapiddocs
        run: npm install -g khulnasoft

      - name: Release SDKs
        env:
          RAPIDDOCS_TOKEN: ${{ secrets.RAPIDDOCS_TOKEN }}
        run: |
          cd packages/ir-sdk
          version=$(cat rapiddocs/apis/ir-types-latest/VERSION)
          rapiddocs generate --api ir-types-latest --group go --version $version
  
  java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rapiddocs
        run: npm install -g khulnasoft

      - name: Release SDKs
        env:
          RAPIDDOCS_TOKEN: ${{ secrets.RAPIDDOCS_TOKEN }}
        run: |
          cd packages/ir-sdk
          version=$(cat rapiddocs/apis/ir-types-latest/VERSION)
          rapiddocs generate --api ir-types-latest --group java --version $version
