name: IR Validation

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "packages/ir-sdk/rapiddocs/apis/**"
    branches:
      - main
  push:
    paths:
      - "packages/ir-sdk/rapiddocs/apis/**"
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Install Rapiddocs
        run: npm install -g khulnasoft

      - name: Check IR Definitions
        run: |
          cd packages/ir-sdk
          rapiddocs check

      - name: Check IR Definitions
        env:
          RAPIDDOCS_TOKEN: dummy
        run: |
          cd packages/ir-sdk
          pnpm generate

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code
