name: Publish @khulnasoft/typescript-dynamic-snippets

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the library to publish."
        required: true
        type: string

env:
  PACKAGE_NAME: "@khulnasoft/typescript-dynamic-snippets"
  GITHUB_TOKEN: ${{ secrets.RAPIDDOCS_GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.RAPIDDOCS_NPM_TOKEN }}

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ inputs.version != null }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: 📥 Install
        uses: ./.github/actions/install

      - uses: bufbuild/buf-setup-action@v1.34.0
        with:
          github_token: ${{ github.token }}

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install protoc-gen-openapi
        run: go install github.com/khulnasoft/protoc-gen-openapi/cmd/protoc-gen-openapi@latest

      - name: 🧪 Build
        run: pnpm --filter=${{ env.PACKAGE_NAME }} compile

      - name: 🧪 Test
        run: pnpm --filter=${{ env.PACKAGE_NAME }} test

      - name: Publish @khulnasoft/typescript-dynamic-snippets
        run: |
          cd generators/typescript-v2/dynamic-snippets
          pnpm --filter=${{ env.PACKAGE_NAME }} dist ${{ inputs.version }}
          cd dist
          echo "//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN }}" > ~/.npmrc
          npm publish --access public
