name: Publish @rapiddocs-rapiddocs/docs-parsers-rapiddocs-definition

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Install Rapiddocs
        run: npm install -g khulnasoft

      - name: Get current version and compute next version
        id: version
        run: |
          CURRENT_VERSION=$(npm view @rapiddocs-rapiddocs/docs-parsers-rapiddocs-definition version)
          # Split version into parts
          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          # Increment patch version
          NEW_VERSION="$major.$minor.$((patch + 1))"
          echo "next_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Generate docs parsers
        env:
          RAPIDDOCS_TOKEN: ${{ secrets.RAPIDDOCS_TOKEN }}
        run: |
          rapiddocs generate --api rapiddocs-definition --group docs-parsers --version ${{ steps.version.outputs.next_version }}

