# This file was auto-generated by Rapiddocs from our API Definition.

import typing
from .metadata_value import MetadataValue

Metadata = typing.Union[
    typing.Dict[str, MetadataValue], typing.Dict[str, typing.Optional[typing.Any]]
]
